<?php
/** Modern announcement publishing form. @author Derek Keats @package announcements */
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$txt=fn($key,$fallback)=>html_entity_decode($this->objLanguage->languageText($key,'announcements',$fallback),ENT_QUOTES,'UTF-8');
$systxt=fn($key,$fallback)=>html_entity_decode($this->objLanguage->code2Txt($key,'announcements',NULL,$fallback),ENT_QUOTES,'UTF-8');
$editing=$mode==='edit';$record=$editing?$announcement:array();$action=$editing?'update':'save';
$scope=(string)($record['contextid']??($isAdmin?'site':'context'));$type=(string)($record['announcement_type']??'general');$audience=(string)($record['audience']??'everyone');
$selected=$editing?(array)$contextAnnouncementList:(array)($contexts??array());
$this->loadClass('htmlarea','htmlelements');$editor=$this->newObject('htmlarea','htmlelements');$editor->name='message';$editor->value=(string)($record['message']??($message??''));
?>
<main class="chisimba-workspace chisimba-flow announcements-publisher">
<header class="chisimba-page-header chisimba-card"><div><p class="chisimba-eyebrow"><?php echo $e($txt('mod_announcements_publishlabel','Site communication'));?></p><h1><?php echo $e($editing?$txt('mod_announcements_update','Edit announcement'):$txt('mod_announcements_addnewannouncement','Publish an announcement'));?></h1><p><?php echo $e($systxt('mod_announcements_publishhelp','Make an announcement to all site users, or to selected groups or [-contexts-].'));?></p></div></header>
<?php if($mode==='fixup'):?><div class="chisimba-notice chisimba-notice--error" role="alert"><?php echo $e($errorMessage);?></div><?php endif;?>
<form class="chisimba-card chisimba-form announcements-publisher__form" method="post" action="<?php echo $e($this->uri(array('action'=>$action),'announcements'));?>"><input type="hidden" name="mode" value="<?php echo $editing?'edit':'add';?>"><?php if($editing):?><input type="hidden" name="id" value="<?php echo $e($record['id']);?>"><?php endif;?>
<div class="announcements-publisher__grid"><div class="chisimba-form-field announcements-publisher__wide"><label for="announcement-title"><?php echo $e($this->objLanguage->languageText('word_title','system','Title'));?></label><input id="announcement-title" name="title" maxlength="255" required value="<?php echo $e($record['title']??($title??''));?>"></div>
<div class="chisimba-form-field"><label for="announcement-type"><?php echo $e($txt('mod_announcements_type','Type'));?></label><select id="announcement-type" name="announcement_type"><?php foreach(array('whats_new'=>$txt('mod_announcements_whatsnew','What’s new'),'general'=>$txt('mod_announcements_general','General announcement'),'service'=>$txt('mod_announcements_service','Service notice')) as $value=>$label):?><option value="<?php echo $value;?>"<?php echo $type===$value?' selected':'';?>><?php echo $e($label);?></option><?php endforeach;?></select></div>
<div class="chisimba-form-field"><label for="announcement-audience"><?php echo $e($txt('mod_announcements_audience','Audience'));?></label><select id="announcement-audience" name="audience"><option value="everyone"<?php echo $audience==='everyone'?' selected':'';?>><?php echo $e($txt('mod_announcements_everyone','Everyone'));?></option><option value="admins"<?php echo $audience==='admins'?' selected':'';?>><?php echo $e($txt('mod_announcements_administrators','Administrators'));?></option><option value="authors"<?php echo $audience==='authors'?' selected':'';?>><?php echo $e(ucfirst($this->objLanguage->code2Txt('word_lecturers','system',NULL,'[-authors-]')));?></option><option value="readonlys"<?php echo $audience==='readonlys'?' selected':'';?>><?php echo $e(ucfirst($this->objLanguage->code2Txt('word_students','system',NULL,'[-readonlys-]')));?></option></select></div></div>
<fieldset><legend><?php echo $e($txt('mod_announcements_sendto','Scope'));?></legend><label for="announcement-scope" class="announcements-publisher__visually-hidden"><?php echo $e($txt('mod_announcements_sendto','Scope'));?></label><select id="announcement-scope" name="recipienttarget"><?php if($isAdmin):?><option value="site"<?php echo $scope==='site'?' selected':'';?>><?php echo $e($txt('mod_announcements_allusers','Site'));?></option><?php endif;?><option value="context"<?php echo $scope==='context'?' selected':'';?>><?php echo $e($systxt('mod_announcements_selectedcontexts','Selected [-contexts-]'));?></option></select><div class="announcements-publisher__contexts"><?php foreach((array)$lecturerContext as $code):$row=$this->objContext->getContext($code);if(!is_array($row)||empty($row['title']))continue;?><label><input type="checkbox" name="contexts[]" value="<?php echo $e($code);?>"<?php echo in_array($code,$selected,true)?' checked':'';?>> <?php echo $e($row['title']);?></label><?php endforeach;?></div></fieldset>
<div class="chisimba-form-field"><label><?php echo $e($this->objLanguage->languageText('word_message','system','Message'));?></label><?php echo $editor->show();?></div>
<div class="chisimba-form-field"><label for="announcement-guide"><?php echo $e($txt('mod_announcements_resourceurl','Further information URL'));?></label><input id="announcement-guide" type="url" name="resource_url" maxlength="2048" value="<?php echo $e($record['resource_url']??'');?>"><small><?php echo $e($txt('mod_announcements_guidehelp','Link to the user guide, documentation or download.'));?></small></div>
<fieldset><legend><?php echo $e($txt('mod_announcements_delivery','Delivery'));?></legend><label><input type="checkbox" name="notify" value="Y"> <?php echo $e($txt('mod_announcements_notifyupdates','Notify the selected audience in Updates'));?></label></fieldset>
<div class="chisimba-form-actions"><button class="button" type="submit"><?php echo $e($editing?$txt('mod_announcements_update','Save announcement'):$txt('mod_announcements_postannouncement','Publish announcement'));?></button><a class="chisimba-button-secondary" href="<?php echo $e($this->uri(NULL,'announcements'));?>"><?php echo $e($txt('mod_announcements_back','Back to announcements'));?></a></div></form></main>
<script>(function(){var f=document.querySelector('.announcements-publisher__form');if(!f)return;function sync(){var scope=f.querySelector('[name=recipienttarget]');var contexts=f.querySelector('.announcements-publisher__contexts');var site=scope&&scope.value==='site';contexts.hidden=site;contexts.querySelectorAll('input').forEach(function(b){b.disabled=site;});}f.addEventListener('change',function(e){if(e.target.name==='recipienttarget')sync();});sync();})();</script>
