<?php
/** Scalable lecturer-reviewed Discussion marking workspace. @author Derek Keats */
$e=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$icons=$this->getObject('iconservice','ui');$discussion=(array)$discussionAssessment;$rubric=(array)$discussionRubric;$students=(array)$discussionStudents;
$queue=array_values(array_filter($students,static fn($student)=>!empty($student['needs_review'])));
$reviewed=array_values(array_filter($students,static fn($student)=>!empty($student['mark'])&&empty($student['needs_review'])));
$noEvidence=array_values(array_filter($students,static fn($student)=>empty($student['evidence'])&&empty($student['mark'])));
$reviewable=array_values(array_filter($students,static fn($student)=>!empty($student['evidence'])||!empty($student['mark'])));
$batchCandidates=array_values(array_filter($queue,static function($student){$status=(string)($student['ai_status']['status']??'');return !empty($student['evidence'])&&count($student['evidence'])<=500&&empty($student['ai']['id'])&&!in_array($status,array('queued','running'),true);}));
$messageCode=(string)$this->getParam('message','');$messages=array('marksaved'=>'Reviewed mark saved.','aiqueued'=>'AI suggestion queued.','marksavefailed'=>'The reviewed mark could not be saved.','incompletereview'=>'Enter a score for every rubric criterion before saving.','invalidrequest'=>'The request expired. Please try again.','invalidstudent'=>'That learner is not in the active course.','noevidence'=>'That learner has no contributions to assess.','evidencechanged'=>'Contributions changed while this review was open. Review the latest evidence before saving.');
$renderLearner=function($student,$isReviewed=false,$hidden=false)use($e,$icons,$discussion,$rubric,$discussionAiAvailable){
    $profile=(array)$student['profile'];$ai=(array)($student['ai']['suggestion']??array());$saved=(array)($student['mark']??array());$savedRubric=json_decode((string)($saved['rubric_json']??'[]'),true)?:array();$suggested=(array)($ai['criteria']??array());$preferDraft=!empty($student['needs_review'])&&!empty($student['ai']['id']);$evidenceById=array();foreach((array)$student['evidence'] as $postEvidence){$evidenceById[(string)$postEvidence['postId']]=$postEvidence;}$name=trim(($profile['firstname']??'').' '.($profile['surname']??''))?:($profile['username']??'Learner');$aiStatus=(array)($student['ai_status']??array());
?>
<details class="chisimba-card discussion-learner-mark<?php echo $hidden?' discussion-queue-hidden':''; ?><?php echo $isReviewed?' discussion-reviewed-hidden':''; ?>" data-student-id="<?php echo $e($student['id']); ?>" data-reviewed="<?php echo $isReviewed?'1':'0'; ?>" data-ai-state="<?php echo $e((empty($student['evidence'])||count($student['evidence'])>500)?'manual':(!empty($student['ai']['id'])?'completed':($aiStatus['status']??'none'))); ?>">
<summary><span><strong><?php echo $e($name); ?></strong><small><?php echo count((array)$student['evidence']); ?> contribution<?php echo count((array)$student['evidence'])===1?'':'s'; ?></small></span><span class="discussion-mark-badge"><?php echo !empty($student['needs_review'])?($saved?'Evidence needs review — prior mark '.$e($saved['mark']).' / '.$e($discussion['assessment_total_mark']):'Awaiting review'):($saved?'Marked: '.$e($saved['mark']).' / '.$e($discussion['assessment_total_mark']):'Awaiting review'); ?></span></summary>
<div class="discussion-learner-mark__body">
<p class="discussion-card-feedback" role="status" aria-live="polite"></p>
<details class="discussion-evidence"><summary>Review contributions (<?php echo count($student['evidence']); ?>)</summary><?php foreach($student['evidence'] as $item): ?><article><h3><a href="<?php echo $e($this->uri(array('action'=>'viewtopic','id'=>$item['topicId'],'post'=>$item['postId']),'discussion')); ?>"><?php echo $e($item['title']?:'View contribution'); ?></a></h3><p><?php echo $e($item['date']); ?></p><p><?php echo nl2br($e($item['text'])); ?></p></article><?php endforeach; ?></details>
<?php if(count($student['evidence'])>500): ?><p class="chisimba-field-help">This learner has more than 500 contributions. Review manually; AI marking would exceed the supported evidence limit.</p><?php endif; ?>
<?php if($discussionAiAvailable): ?><form method="post" action="<?php echo $e($this->uri(array('action'=>'requestdiscussionaimark'),'discussion')); ?>" class="discussion-ai-action"><input type="hidden" name="csrf_token" value="<?php echo $e($student['ai_csrf']); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><input type="hidden" name="student_id" value="<?php echo $e($student['id']); ?>"><button class="button chisimba-button-secondary chisimba-button-compact" type="submit"<?php echo ($isReviewed||empty($student['evidence'])||count($student['evidence'])>500||!empty($student['ai']['id'])||in_array(($aiStatus['status']??''),array('queued','running'),true))?' disabled':''; ?>><?php echo $icons->render('sparkles',array('decorative'=>true)); ?><span><?php echo !empty($student['ai']['id'])?'Already AI marked':($isReviewed?'Reviewed without AI':(in_array(($aiStatus['status']??''),array('queued','running'),true)?'AI marking in progress':'Submit for AI marking')); ?></span></button></form><?php else: ?><p class="chisimba-field-help">AI suggestions are unavailable. Manual marking remains available.</p><?php endif; ?>
<p class="discussion-ai-status chisimba-field-help"><?php if(($aiStatus['status']??'')==='failed'): ?>AI suggestion failed: <?php echo $e($aiStatus['error_code']??'provider_failed'); ?><?php elseif(in_array(($aiStatus['status']??''),array('queued','running'),true)): ?>AI suggestion is <?php echo $e($aiStatus['status']); ?>.<?php endif; ?></p>
<form method="post" action="<?php echo $e($this->uri(array('action'=>'savediscussionmark'),'discussion')); ?>" class="chisimba-form discussion-mark-form"><input type="hidden" name="evidence_fingerprint" value="<?php echo $e($student['evidence_fingerprint']); ?>"><input type="hidden" name="csrf_token" value="<?php echo $e($student['save_csrf']); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><input type="hidden" name="student_id" value="<?php echo $e($student['id']); ?>"><?php if(!empty($student['ai']['id'])): ?><input type="hidden" name="ai_job_id" value="<?php echo $e($student['ai']['id']); ?>"><?php endif; ?>
<div class="discussion-mark-criteria"><?php foreach((array)($rubric['criteria']??array()) as $index=>$criterion): $draft=$suggested[$index]??array();$prior=$savedRubric[$index]??array();$score=$preferDraft?($draft['score']??''):($prior['score']??($draft['score']??'')); ?><div class="discussion-mark-criterion"><label for="criterion-<?php echo $e($student['id'].'-'.$index); ?>"><?php echo $e($criterion['objective']); ?><span>Maximum <?php echo $e($criterion['maximumMark']); ?></span></label><input id="criterion-<?php echo $e($student['id'].'-'.$index); ?>" type="number" name="criterion[<?php echo $index; ?>]" min="0" max="<?php echo $e($criterion['maximumMark']); ?>" step="0.5" value="<?php echo $e($score); ?>" required><?php if(!empty($draft['rationale'])): ?><details class="discussion-ai-notes"><summary>AI reasoning &amp; evidence</summary><p><?php echo $e($draft['rationale']); ?><?php if(!empty($draft['evidencePostIds'])): ?> </p><div class="discussion-evidence-links"><strong>Contributions cited</strong> <?php foreach((array)$draft['evidencePostIds'] as $postId): if(!isset($evidenceById[(string)$postId]))continue;$item=$evidenceById[(string)$postId]; ?><a href="<?php echo $e($this->uri(array('action'=>'viewtopic','id'=>$item['topicId'],'post'=>$postId),'discussion')); ?>"><?php echo $e($item['title']?:$postId); ?></a> <?php endforeach; ?></div><?php else: ?></p><?php endif; ?></details><?php endif; ?></div><?php endforeach; ?></div>
<div class="chisimba-form-field"><label for="feedback-<?php echo $e($student['id']); ?>">Lecturer feedback</label><textarea id="feedback-<?php echo $e($student['id']); ?>" name="feedback" rows="4" maxlength="2000"><?php echo $e($preferDraft?($ai['feedback']??''):($saved['feedback']??($ai['feedback']??''))); ?></textarea></div><div class="chisimba-form-actions discussion-mark-actions"><output class="discussion-mark-total" aria-live="polite">Total mark</output><button class="button chisimba-button-compact" type="submit"><?php echo $icons->render('check',array('decorative'=>true)); ?><span>Save reviewed mark</span></button></div></form>
</div></details>
<?php };
ob_start();
?>
<main class="chisimba-workspace chisimba-flow discussion-workspace discussion-marking" data-queue-count="<?php echo count($queue); ?>" data-reviewed-count="<?php echo count($reviewed); ?>">
<header class="chisimba-page-header chisimba-card"><div><p class="chisimba-eyebrow">Discussion assessment</p><h1><?php echo $e($discussion['discussion_name']??'Marked discussion'); ?></h1><p>Review contributions, refine suggested scores, and save your assessment.</p></div><a class="button chisimba-button-secondary chisimba-button-compact" href="<?php echo $e($this->uri(array('action'=>'administration'),'discussion')); ?>"><?php echo $icons->render('arrow-left',array('decorative'=>true)); ?><span>Discussion administration</span></a></header>
<p id="discussion-review-feedback" class="chisimba-notice<?php echo isset($messages[$messageCode])?'':' discussion-feedback-empty'; ?>" role="status" aria-live="polite"><?php echo $e($messages[$messageCode]??''); ?></p>
<section class="chisimba-card discussion-review-progress" aria-label="Review progress"><div><strong id="discussion-awaiting-count"><?php echo count($queue); ?></strong><span>awaiting review</span></div><div><strong id="discussion-reviewed-count"><?php echo count($reviewed); ?></strong><span>reviewed</span></div><div><strong><?php echo count($noEvidence); ?></strong><span>without contributions</span></div></section>
<details class="chisimba-card discussion-rubric-summary"><summary>Participation and quality rubric</summary><p>Improvement may strengthen the evidence, but consistently strong work does not need to demonstrate improvement.</p><div class="discussion-rubric-weights"><?php foreach((array)($rubric['criteria']??array()) as $criterion): ?><span class="discussion-setting-badge discussion-setting-badge--on"><?php echo $e($criterion['objective']); ?> · <?php echo $e($criterion['maximumMark']); ?>%</span><?php endforeach; ?></div></details>
<section class="discussion-review-section" id="discussion-review-queue"><header><div><p class="chisimba-eyebrow">Assessment workspace</p><h2>Learner reviews</h2></div><div class="discussion-review-controls"><button type="button" class="button chisimba-button-secondary chisimba-button-compact" id="discussion-toggle-reviewed" aria-pressed="false">Show reviewed learners (<?php echo count($reviewed); ?>)</button><?php if($discussionAiAvailable&&$queue): ?><form method="post" action="<?php echo $e($this->uri(array('action'=>'requestdiscussionaibatch'),'discussion')); ?>" id="discussion-ai-batch"><input type="hidden" name="csrf_token" value="<?php echo $e($discussionBatchCsrf); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><?php foreach(array_slice($batchCandidates,0,10) as $student): ?><input type="hidden" name="student_ids[]" value="<?php echo $e($student['id']); ?>"><?php endforeach; ?><button type="submit" class="button chisimba-button-secondary chisimba-button-compact"<?php echo $batchCandidates?'':' disabled'; ?>><?php echo $icons->render('sparkles',array('decorative'=>true)); ?><span><?php echo $batchCandidates?'Submit batch for AI marking':'Batch already AI marked'; ?></span></button></form><?php endif; ?></div></header>
<div id="discussion-queue-items"><?php $queueIndex=0;foreach($reviewable as $student){$isReviewed=!empty($student['mark'])&&empty($student['needs_review']);$renderLearner($student,$isReviewed,!$isReviewed&&$queueIndex++>=10);} ?></div>
<?php if(!$queue): ?><div class="chisimba-card discussion-empty-state" id="discussion-queue-empty"><div><h2>Review queue complete</h2><p>There are no contributing learners awaiting review.</p></div></div><?php endif; ?>
<?php if(count($queue)>10): ?><button type="button" class="button chisimba-button-secondary" id="discussion-load-more">Show next 10</button><?php endif; ?></section>
<?php if($noEvidence): ?><details class="chisimba-card discussion-no-evidence"><summary>Without contributions (<?php echo count($noEvidence); ?>)</summary><p>These learners are excluded from the marking queue because there is no Discussion evidence.</p><ul><?php foreach($noEvidence as $student): $profile=(array)$student['profile']; ?><li><?php echo $e(trim(($profile['firstname']??'').' '.($profile['surname']??''))); ?></li><?php endforeach; ?></ul></details><?php endif; ?>
</main>
<script>
(function(){
var root=document.querySelector('.discussion-marking');if(!root||!window.fetch||!window.FormData)return;
var notice=document.getElementById('discussion-review-feedback'),queue=document.getElementById('discussion-queue-items'),showReviewed=false,maximum=<?php echo json_encode((float)($discussion['assessment_total_mark']??100)); ?>;
function feedback(message,error){notice.textContent=message;notice.classList.remove('discussion-feedback-empty','chisimba-notice--error');if(error)notice.classList.add('chisimba-notice--error');}
function updateCounts(){var waiting=queue.querySelectorAll('.discussion-learner-mark[data-reviewed="0"]').length,done=queue.querySelectorAll('.discussion-learner-mark[data-reviewed="1"]').length;document.getElementById('discussion-awaiting-count').textContent=waiting;document.getElementById('discussion-reviewed-count').textContent=done;var toggle=document.getElementById('discussion-toggle-reviewed');if(toggle)toggle.textContent=(showReviewed?'Hide':'Show')+' reviewed learners ('+done+')';}
function updateTotal(form){var inputs=Array.prototype.slice.call(form.querySelectorAll('.discussion-mark-criterion input')),complete=inputs.every(function(input){return input.value!=='';}),rubric=inputs.reduce(function(sum,input){return sum+Number(input.value||0);},0),mark=rubric/100*maximum,output=form.querySelector('.discussion-mark-total');output.textContent=complete?'Rubric total: '+rubric.toFixed(1).replace('.0','')+' / 100 · Total mark: '+mark.toFixed(1).replace('.0','')+' / '+maximum:'Complete all criteria to calculate the total mark';}
function visibleBatch(){return Array.prototype.slice.call(queue.querySelectorAll('.discussion-learner-mark[data-reviewed="0"]:not(.discussion-queue-hidden)')).filter(function(card){return !['completed','queued','running','manual'].includes(card.dataset.aiState);}).slice(0,10);}
function refreshBatchForm(){var form=document.getElementById('discussion-ai-batch');if(!form)return;var batch=visibleBatch(),button=form.querySelector('button'),label=button.querySelector('span');form.querySelectorAll('input[name="student_ids[]"]').forEach(function(input){input.remove();});batch.forEach(function(card){var input=document.createElement('input');input.type='hidden';input.name='student_ids[]';input.value=card.dataset.studentId;form.appendChild(input);});button.disabled=batch.length===0;label.textContent=batch.length?'Submit batch for AI marking':'Batch already AI marked';}
function revealNext(){var hidden=Array.prototype.slice.call(queue.querySelectorAll('.discussion-queue-hidden')).slice(0,10);hidden.forEach(function(item){item.classList.remove('discussion-queue-hidden');});var button=document.getElementById('discussion-load-more');if(button&&!queue.querySelector('.discussion-queue-hidden'))button.remove();refreshBatchForm();}
var more=document.getElementById('discussion-load-more');if(more)more.addEventListener('click',revealNext);var toggle=document.getElementById('discussion-toggle-reviewed');if(toggle)toggle.addEventListener('click',function(){showReviewed=!showReviewed;root.classList.toggle('discussion-show-reviewed',showReviewed);toggle.setAttribute('aria-pressed',showReviewed?'true':'false');updateCounts();});root.querySelectorAll('.discussion-mark-form').forEach(function(form){updateTotal(form);form.addEventListener('input',function(){updateTotal(form);});});
root.addEventListener('submit',function(event){var form=event.target;if(!form.matches('.discussion-mark-form,.discussion-ai-action,#discussion-ai-batch'))return;event.preventDefault();if(form.id==='discussion-ai-batch')refreshBatchForm();var button=form.querySelector('button[type="submit"]'),data=new FormData(form);data.append('response_format','json');button.disabled=true;
fetch(form.action,{method:'POST',body:data,headers:{'Accept':'application/json'}}).then(function(response){return response.json().then(function(body){if(body.csrfToken)form.querySelector('input[name="csrf_token"]').value=body.csrfToken;if(!response.ok||!body.ok)throw new Error(body.message||'The request failed.');return body;});}).then(function(body){feedback(body.message,false);if(body.csrfToken)form.querySelector('input[name="csrf_token"]').value=body.csrfToken;if(form.classList.contains('discussion-ai-action')){var aiCard=form.closest('.discussion-learner-mark');aiCard.dataset.aiState='queued';aiCard.querySelector('.discussion-ai-status').textContent='AI suggestion is queued.';button.dataset.locked='1';button.querySelector('span').textContent='AI marking in progress';}if(form.id==='discussion-ai-batch'){visibleBatch().filter(function(card){return (body.studentIds||[]).includes(card.dataset.studentId);}).forEach(function(card){card.dataset.aiState='queued';card.querySelector('.discussion-ai-status').textContent='AI suggestion is queued.';});button.dataset.locked='1';button.querySelector('span').textContent='AI marking in progress';}if(form.classList.contains('discussion-mark-form')){var card=form.closest('.discussion-learner-mark');card.dataset.reviewed='1';card.open=false;var aiButton=card.querySelector('.discussion-ai-action button');if(aiButton)aiButton.disabled=true;card.querySelector('.discussion-mark-badge').textContent='Marked: '+Number(body.mark).toFixed(1).replace('.0','')+' / '+body.maximum;card.classList.remove('discussion-queue-hidden');card.classList.toggle('discussion-reviewed-hidden',true);updateCounts();revealNext();}}).catch(function(error){feedback(error.message,true);}).finally(function(){button.disabled=button.dataset.locked==='1';});
});
})();
</script>
<?php
$pageContent=ob_get_contents();ob_end_clean();$this->setVar('pageContent',$pageContent);
?>
