<?php
/** Scalable lecturer-reviewed Discussion marking workspace. @author Derek Keats */
$e=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$icons=$this->getObject('iconservice','ui');$discussion=(array)$discussionAssessment;$rubric=(array)$discussionRubric;$students=(array)$discussionStudents;
$queue=array_values(array_filter($students,static fn($student)=>!empty($student['evidence'])&&empty($student['mark'])));
$reviewed=array_values(array_filter($students,static fn($student)=>!empty($student['mark'])));
$noEvidence=array_values(array_filter($students,static fn($student)=>empty($student['evidence'])&&empty($student['mark'])));
$messageCode=(string)$this->getParam('message','');$messages=array('marksaved'=>'Reviewed mark saved.','aiqueued'=>'AI suggestion queued.','marksavefailed'=>'The reviewed mark could not be saved.','invalidrequest'=>'The request expired. Please try again.','invalidstudent'=>'That learner is not in the active course.','noevidence'=>'That learner has no contributions to assess.');
$renderLearner=function($student,$isReviewed=false,$hidden=false)use($e,$icons,$discussion,$rubric,$discussionAiAvailable){
    $profile=(array)$student['profile'];$ai=(array)($student['ai']['suggestion']??array());$saved=(array)($student['mark']??array());$savedRubric=json_decode((string)($saved['rubric_json']??'[]'),true)?:array();$suggested=(array)($ai['criteria']??array());$evidenceById=array();foreach((array)$student['evidence'] as $postEvidence){$evidenceById[(string)$postEvidence['postId']]=$postEvidence;}$name=trim(($profile['firstname']??'').' '.($profile['surname']??''))?:($profile['username']??'Learner');$aiStatus=(array)($student['ai_status']??array());
?>
<details class="chisimba-card discussion-learner-mark<?php echo $hidden?' discussion-queue-hidden':''; ?>" data-student-id="<?php echo $e($student['id']); ?>" data-reviewed="<?php echo $isReviewed?'1':'0'; ?>">
<summary><span><strong><?php echo $e($name); ?></strong><small><?php echo count((array)$student['evidence']); ?> contribution<?php echo count((array)$student['evidence'])===1?'':'s'; ?></small></span><span class="discussion-mark-badge"><?php echo $saved?'Marked: '.$e($saved['mark']).' / '.$e($discussion['assessment_total_mark']):'Awaiting review'; ?></span></summary>
<div class="discussion-learner-mark__body">
<p class="discussion-card-feedback" role="status" aria-live="polite"></p>
<?php if($discussionAiAvailable): ?><form method="post" action="<?php echo $e($this->uri(array('action'=>'requestdiscussionaimark'),'discussion')); ?>" class="discussion-ai-action"><input type="hidden" name="csrf_token" value="<?php echo $e($student['ai_csrf']); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><input type="hidden" name="student_id" value="<?php echo $e($student['id']); ?>"><button class="button chisimba-button-secondary chisimba-button-compact" type="submit"><?php echo $icons->render('sparkles',array('decorative'=>true)); ?><span>Prepare AI suggestion</span></button></form><?php else: ?><p class="chisimba-field-help">AI suggestions are unavailable. Manual marking remains available.</p><?php endif; ?>
<p class="discussion-ai-status chisimba-field-help"><?php if(($aiStatus['status']??'')==='failed'): ?>AI suggestion failed: <?php echo $e($aiStatus['error_code']??'provider_failed'); ?><?php elseif(in_array(($aiStatus['status']??''),array('queued','running'),true)): ?>AI suggestion is <?php echo $e($aiStatus['status']); ?>.<?php endif; ?></p>
<form method="post" action="<?php echo $e($this->uri(array('action'=>'savediscussionmark'),'discussion')); ?>" class="chisimba-form discussion-mark-form"><input type="hidden" name="csrf_token" value="<?php echo $e($student['save_csrf']); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><input type="hidden" name="student_id" value="<?php echo $e($student['id']); ?>"><?php if(!empty($student['ai']['id'])): ?><input type="hidden" name="ai_job_id" value="<?php echo $e($student['ai']['id']); ?>"><?php endif; ?>
<div class="discussion-mark-criteria"><?php foreach((array)($rubric['criteria']??array()) as $index=>$criterion): $draft=$suggested[$index]??array();$prior=$savedRubric[$index]??array();$score=$prior['score']??($draft['score']??0); ?><div class="discussion-mark-criterion"><label for="criterion-<?php echo $e($student['id'].'-'.$index); ?>"><?php echo $e($criterion['objective']); ?><span>Maximum <?php echo $e($criterion['maximumMark']); ?></span></label><input id="criterion-<?php echo $e($student['id'].'-'.$index); ?>" type="number" name="criterion[<?php echo $index; ?>]" min="0" max="<?php echo $e($criterion['maximumMark']); ?>" step="0.5" value="<?php echo $e($score); ?>" required><?php if(!empty($draft['rationale'])): ?><p><?php echo $e($draft['rationale']); ?><?php if(!empty($draft['evidencePostIds'])): ?> <strong>Evidence:</strong> <?php foreach((array)$draft['evidencePostIds'] as $postId): if(!isset($evidenceById[(string)$postId]))continue;$item=$evidenceById[(string)$postId]; ?><a href="<?php echo $e($this->uri(array('action'=>'viewtopic','id'=>$item['topicId'],'post'=>$postId),'discussion')); ?>"><?php echo $e($item['title']?:$postId); ?></a> <?php endforeach; ?><?php endif; ?></p><?php endif; ?></div><?php endforeach; ?></div>
<div class="chisimba-form-field"><label for="feedback-<?php echo $e($student['id']); ?>">Lecturer feedback</label><textarea id="feedback-<?php echo $e($student['id']); ?>" name="feedback" rows="4" maxlength="2000"><?php echo $e($saved['feedback']??($ai['feedback']??'')); ?></textarea></div><div class="chisimba-form-actions"><button class="button chisimba-button-compact" type="submit"><?php echo $icons->render('check',array('decorative'=>true)); ?><span>Save reviewed mark</span></button></div></form>
</div></details>
<?php };
ob_start();
?>
<main class="chisimba-workspace chisimba-flow discussion-workspace discussion-marking" data-queue-count="<?php echo count($queue); ?>" data-reviewed-count="<?php echo count($reviewed); ?>">
<header class="chisimba-page-header chisimba-card"><div><p class="chisimba-eyebrow">Discussion assessment</p><h1><?php echo $e($discussion['discussion_name']??'Marked discussion'); ?></h1><p>Review a focused batch, then approve ordinary results by exception. AI suggestions remain editable until saved.</p></div><a class="button chisimba-button-secondary chisimba-button-compact" href="<?php echo $e($this->uri(array('action'=>'administration'),'discussion')); ?>"><?php echo $icons->render('arrow-left',array('decorative'=>true)); ?><span>Discussion administration</span></a></header>
<p id="discussion-review-feedback" class="chisimba-notice<?php echo isset($messages[$messageCode])?'':' discussion-feedback-empty'; ?>" role="status" aria-live="polite"><?php echo $e($messages[$messageCode]??''); ?></p>
<section class="chisimba-card discussion-review-progress" aria-label="Review progress"><div><strong id="discussion-awaiting-count"><?php echo count($queue); ?></strong><span>awaiting review</span></div><div><strong id="discussion-reviewed-count"><?php echo count($reviewed); ?></strong><span>reviewed</span></div><div><strong><?php echo count($noEvidence); ?></strong><span>without contributions</span></div></section>
<details class="chisimba-card discussion-rubric-summary"><summary>Participation and quality rubric</summary><p>Improvement may strengthen the evidence, but consistently strong work does not need to demonstrate improvement.</p><div class="discussion-rubric-weights"><?php foreach((array)($rubric['criteria']??array()) as $criterion): ?><span class="discussion-setting-badge discussion-setting-badge--on"><?php echo $e($criterion['objective']); ?> · <?php echo $e($criterion['maximumMark']); ?>%</span><?php endforeach; ?></div></details>
<section class="discussion-review-section" id="discussion-review-queue"><header><div><p class="chisimba-eyebrow">Current batch</p><h2>Awaiting review</h2></div><?php if($discussionAiAvailable&&$queue): ?><form method="post" action="<?php echo $e($this->uri(array('action'=>'requestdiscussionaibatch'),'discussion')); ?>" id="discussion-ai-batch"><input type="hidden" name="csrf_token" value="<?php echo $e($discussionBatchCsrf); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><?php foreach(array_slice($queue,0,10) as $student): ?><input type="hidden" name="student_ids[]" value="<?php echo $e($student['id']); ?>"><?php endforeach; ?><button type="submit" class="button chisimba-button-secondary chisimba-button-compact"><?php echo $icons->render('sparkles',array('decorative'=>true)); ?><span>Prepare AI for this batch</span></button></form><?php endif; ?></header>
<div id="discussion-queue-items"><?php foreach($queue as $index=>$student){$renderLearner($student,false,$index>=10);} ?></div>
<?php if(!$queue): ?><div class="chisimba-card discussion-empty-state" id="discussion-queue-empty"><div><h2>Review queue complete</h2><p>There are no contributing learners awaiting review.</p></div></div><?php endif; ?>
<?php if(count($queue)>10): ?><button type="button" class="button chisimba-button-secondary" id="discussion-load-more">Show next 10</button><?php endif; ?></section>
<details class="chisimba-card discussion-reviewed-panel" id="discussion-reviewed-panel"><summary>Reviewed learners (<span id="discussion-reviewed-summary-count"><?php echo count($reviewed); ?></span>)</summary><div id="discussion-reviewed-items"><?php foreach($reviewed as $student){$renderLearner($student,true,false);} ?></div><p id="discussion-reviewed-empty"<?php echo $reviewed?' hidden':''; ?>>No reviews have been saved yet.</p></details>
<?php if($noEvidence): ?><details class="chisimba-card discussion-no-evidence"><summary>Without contributions (<?php echo count($noEvidence); ?>)</summary><p>These learners are excluded from the marking queue because there is no Discussion evidence.</p><ul><?php foreach($noEvidence as $student): $profile=(array)$student['profile']; ?><li><?php echo $e(trim(($profile['firstname']??'').' '.($profile['surname']??''))); ?></li><?php endforeach; ?></ul></details><?php endif; ?>
</main>
<script>
(function(){
var root=document.querySelector('.discussion-marking');if(!root||!window.fetch||!window.FormData)return;
var notice=document.getElementById('discussion-review-feedback'),queue=document.getElementById('discussion-queue-items'),reviewed=document.getElementById('discussion-reviewed-items');
function feedback(message,error){notice.textContent=message;notice.classList.remove('discussion-feedback-empty','chisimba-notice--error');if(error)notice.classList.add('chisimba-notice--error');}
function updateCounts(){var waiting=queue.querySelectorAll('.discussion-learner-mark[data-reviewed="0"]').length,done=reviewed.querySelectorAll('.discussion-learner-mark').length;document.getElementById('discussion-awaiting-count').textContent=waiting;document.getElementById('discussion-reviewed-count').textContent=done;document.getElementById('discussion-reviewed-summary-count').textContent=done;document.getElementById('discussion-reviewed-empty').hidden=done>0;}
function visibleBatch(){return Array.prototype.slice.call(queue.querySelectorAll('.discussion-learner-mark[data-reviewed="0"]:not(.discussion-queue-hidden)')).slice(0,10);}
function refreshBatchForm(){var form=document.getElementById('discussion-ai-batch');if(!form)return;form.querySelectorAll('input[name="student_ids[]"]').forEach(function(input){input.remove();});visibleBatch().forEach(function(card){var input=document.createElement('input');input.type='hidden';input.name='student_ids[]';input.value=card.dataset.studentId;form.appendChild(input);});form.hidden=visibleBatch().length===0;}
function revealNext(){var hidden=Array.prototype.slice.call(queue.querySelectorAll('.discussion-queue-hidden')).slice(0,10);hidden.forEach(function(item){item.classList.remove('discussion-queue-hidden');});var button=document.getElementById('discussion-load-more');if(button&&!queue.querySelector('.discussion-queue-hidden'))button.remove();refreshBatchForm();}
var more=document.getElementById('discussion-load-more');if(more)more.addEventListener('click',revealNext);
root.addEventListener('submit',function(event){var form=event.target;if(!form.matches('.discussion-mark-form,.discussion-ai-action,#discussion-ai-batch'))return;event.preventDefault();if(form.id==='discussion-ai-batch')refreshBatchForm();var button=form.querySelector('button[type="submit"]'),data=new FormData(form);data.append('response_format','json');button.disabled=true;
fetch(form.action,{method:'POST',body:data,headers:{'Accept':'application/json'}}).then(function(response){return response.json().then(function(body){if(!response.ok||!body.ok)throw new Error(body.message||'The request failed.');return body;});}).then(function(body){feedback(body.message,false);if(body.csrfToken)form.querySelector('input[name="csrf_token"]').value=body.csrfToken;if(form.classList.contains('discussion-ai-action')){form.closest('.discussion-learner-mark').querySelector('.discussion-ai-status').textContent='AI suggestion is queued.';}if(form.id==='discussion-ai-batch'){visibleBatch().forEach(function(card){card.querySelector('.discussion-ai-status').textContent='AI suggestion is queued.';});}if(form.classList.contains('discussion-mark-form')){var card=form.closest('.discussion-learner-mark');card.dataset.reviewed='1';card.open=false;card.querySelector('.discussion-mark-badge').textContent='Marked: '+Number(body.mark).toFixed(1).replace('.0','')+' / '+body.maximum;card.classList.remove('discussion-queue-hidden');reviewed.appendChild(card);updateCounts();revealNext();}}).catch(function(error){feedback(error.message,true);}).finally(function(){button.disabled=false;});
});
})();
</script>
<?php
$pageContent=ob_get_contents();ob_end_clean();$this->setVar('pageContent',$pageContent);
?>
