<?php
/** Lecturer-reviewed Discussion marking workspace. @author Derek Keats */
$e=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$icons=$this->getObject('iconservice','ui');$discussion=(array)$discussionAssessment;$rubric=(array)$discussionRubric;$students=(array)$discussionStudents;
ob_start();
?>
<main class="chisimba-workspace chisimba-flow discussion-workspace discussion-marking">
<header class="chisimba-page-header chisimba-card"><div><p class="chisimba-eyebrow">Discussion assessment</p><h1><?php echo $e($discussion['discussion_name']??'Marked discussion'); ?></h1><p>Review each learner’s participation and quality evidence. AI suggestions remain editable drafts until you save them.</p></div><a class="button chisimba-button-secondary chisimba-button-compact" href="<?php echo $e($this->uri(array('action'=>'administration'),'discussion')); ?>"><?php echo $icons->render('arrow-left',array('decorative'=>true)); ?><span>Discussion administration</span></a></header>
<section class="chisimba-card discussion-rubric-summary"><h2>Participation and quality rubric</h2><p>Improvement may strengthen the evidence, but consistently strong work does not need to demonstrate improvement.</p><div class="discussion-rubric-weights"><?php foreach((array)($rubric['criteria']??array()) as $criterion): ?><span class="discussion-setting-badge discussion-setting-badge--on"><?php echo $e($criterion['objective']); ?> · <?php echo $e($criterion['maximumMark']); ?>%</span><?php endforeach; ?></div></section>
<?php if(!$students): ?><section class="chisimba-card discussion-empty-state"><h2>No learners to mark</h2><p>This course currently has no student members.</p></section><?php endif; ?>
<?php foreach($students as $student): $profile=(array)$student['profile'];$ai=(array)($student['ai']['suggestion']??array());$saved=(array)($student['mark']??array());$savedRubric=json_decode((string)($saved['rubric_json']??'[]'),true)?:array();$suggested=(array)($ai['criteria']??array());$evidenceById=array();foreach((array)$student['evidence'] as $postEvidence){$evidenceById[(string)$postEvidence['postId']]=$postEvidence;} ?>
<article class="chisimba-card discussion-learner-mark"><header><div><h2><?php echo $e(trim(($profile['firstname']??'').' '.($profile['surname']??''))); ?></h2><p><?php echo count((array)$student['evidence']); ?> contribution<?php echo count((array)$student['evidence'])===1?'':'s'; ?> available as evidence.</p></div><?php if($saved): ?><span class="discussion-setting-badge discussion-setting-badge--on">Marked: <?php echo $e($saved['mark']); ?> / <?php echo $e($discussion['assessment_total_mark']); ?></span><?php endif; ?></header>
<?php if($discussionAiAvailable): ?><form method="post" action="<?php echo $e($this->uri(array('action'=>'requestdiscussionaimark'),'discussion')); ?>" class="discussion-ai-action"><input type="hidden" name="csrf_token" value="<?php echo $e($student['ai_csrf']); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><input type="hidden" name="student_id" value="<?php echo $e($student['id']); ?>"><button class="button chisimba-button-secondary chisimba-button-compact" type="submit"><?php echo $icons->render('sparkles',array('decorative'=>true)); ?><span>Prepare AI suggestion</span></button></form><?php else: ?><p class="chisimba-field-help">AI suggestions are unavailable. Manual rubric marking remains available.</p><?php endif; ?>
<form method="post" action="<?php echo $e($this->uri(array('action'=>'savediscussionmark'),'discussion')); ?>" class="chisimba-form discussion-mark-form"><input type="hidden" name="csrf_token" value="<?php echo $e($student['save_csrf']); ?>"><input type="hidden" name="id" value="<?php echo $e($discussion['id']); ?>"><input type="hidden" name="student_id" value="<?php echo $e($student['id']); ?>"><?php if(!empty($student['ai']['id'])): ?><input type="hidden" name="ai_job_id" value="<?php echo $e($student['ai']['id']); ?>"><?php endif; ?>
<div class="discussion-mark-criteria"><?php foreach((array)($rubric['criteria']??array()) as $index=>$criterion): $draft=$suggested[$index]??array();$prior=$savedRubric[$index]??array();$score=$draft['score']??($prior['score']??0); ?><div class="discussion-mark-criterion"><label for="criterion-<?php echo $e($student['id'].'-'.$index); ?>"><?php echo $e($criterion['objective']); ?><span>Maximum <?php echo $e($criterion['maximumMark']); ?></span></label><input id="criterion-<?php echo $e($student['id'].'-'.$index); ?>" type="number" name="criterion[<?php echo $index; ?>]" min="0" max="<?php echo $e($criterion['maximumMark']); ?>" step="0.5" value="<?php echo $e($score); ?>" required><?php if(!empty($draft['rationale'])): ?><p><?php echo $e($draft['rationale']); ?><?php if(!empty($draft['evidencePostIds'])): ?> <strong>Evidence:</strong> <?php foreach((array)$draft['evidencePostIds'] as $postId): if(!isset($evidenceById[(string)$postId]))continue;$item=$evidenceById[(string)$postId]; ?><a href="<?php echo $e($this->uri(array('action'=>'viewtopic','id'=>$item['topicId'],'post'=>$postId),'discussion')); ?>"><?php echo $e($item['title']?:$postId); ?></a> <?php endforeach; ?><?php endif; ?></p><?php endif; ?></div><?php endforeach; ?></div>
<div class="chisimba-form-field"><label for="feedback-<?php echo $e($student['id']); ?>">Lecturer feedback</label><textarea id="feedback-<?php echo $e($student['id']); ?>" name="feedback" rows="5" maxlength="2000"><?php echo $e($ai['feedback']??($saved['feedback']??'')); ?></textarea></div><div class="chisimba-form-actions"><button class="button chisimba-button-compact" type="submit"><?php echo $icons->render('check',array('decorative'=>true)); ?><span>Save reviewed mark</span></button></div></form></article>
<?php endforeach; ?></main>
<?php
$pageContent = ob_get_contents();
ob_end_clean();
$this->setVar('pageContent', $pageContent);
?>
