<?php
$r=$this->getObject('audiencerenderer','audience');$e=['audiencerenderer','escape'];$view=$this->getVar('audienceView');$record=$this->getVar('audienceRecord');$error=$this->getVar('audienceError');$campaigns=$this->getObject('audiencecampaigns','audience');$cfg=$this->getObject('dbsysconfig','sysconfig');
$input=$this->getVar('audienceInput')?:($record?(isset($record['payload'])?json_decode($record['payload'],true)+$record:$record):[]);
if(!$record&&!$this->getVar('audienceInput'))$input+=['greeting'=>$r->text('greeting_default'),'latest_recording'=>true];
$field=function($key,$type='text')use($input,$r,$e){$v=$input[$key]??'';return '<div class="chisimba-form-field"><label for="aud-'.$key.'">'.$e($r->text($key)).'</label>'.($type==='textarea'?'<textarea id="aud-'.$key.'" name="'.$key.'" rows="10">'.$e($v).'</textarea>':'<input id="aud-'.$key.'" name="'.$key.'" type="'.$type.'" value="'.$e($v).'">').'</div>';};
$check=function($key,$checked)use($r,$e){return '<p><label><input type="checkbox" name="'.$key.'" value="1"'.($checked?' checked':'').'> '.$e($r->text($key)).'</label></p>';};
$hidden=function($key,$value)use($e){return '<input type="hidden" name="'.$key.'" value="'.$e($value).'">';};
echo '<section class="chisimba-form-card chisimba-form-card--wide"><header class="chisimba-form-actions"><h1>'.$e($r->text($view)).'</h1>'.$this->getObject('contextualhelp','help')->show('audience','administration',true).'</header><nav class="chisimba-form-actions">'.$r->link('users','users',['action'=>'users']).$r->link('campaigns','mail',['action'=>'campaigns']).$r->link('new','plus',['action'=>'compose']).$r->link('settings','settings',['action'=>'settings']).'</nav><p>'.$e($r->text('scope')).'</p>';
if(in_array($view,['compose','campaigns','settings'],true)&&($cfg->getValue('COMMUNICATION_TRANSPORT','communications')==='null'||trim((string)$cfg->getValue('COMMUNICATION_ALLOWED_RECIPIENTS','communications'))!==''))echo '<p role="status">'.$e($r->text('delivery_restricted')).'</p>';
if($view==='users'){
 $q=$this->getParam('q','');$q=is_string($q)?trim($q):'';$state=$this->getParam('state','subscribed');$state=is_string($state)?$state:'';
 $list=$this->getObject('audienceadmin','audience')->search($q,$state,$this->getParam('page',1));
 echo '<form method="get" class="chisimba-form-actions">'.$hidden('module','audience').$hidden('action','users').'<label>'.$e($r->text('search')).' <input name="q" value="'.$e($q).'" type="search"></label><label>'.$e($r->text('state')).' <select name="state">';foreach(['all','subscribed','unsubscribed','pending','suppressed'] as $v)echo '<option value="'.$v.'"'.($v===$state?' selected':'').'>'.$e($r->text($v)).'</option>';echo '</select></label>'.$r->button('search','search').'</form><p>'.$e(sprintf($r->text('count'),$list['count'])).'</p><div class="chisimba-table-wrap"><table class="table"><thead><tr>';foreach(['name','email','state','edit'] as $k)echo '<th>'.$e($r->text($k)).'</th>';echo '</tr></thead><tbody>';
 foreach($list['rows'] as $c)echo '<tr><td>'.$e($c['name']).'</td><td>'.$e($c['email']).'</td><td>'.$e($r->text($c['state'])).'</td><td>'.$r->link('edit','pencil',['action'=>'contact','id'=>$c['id']]).'</td></tr>';echo '</tbody></table></div><nav class="chisimba-form-actions">';
 if($list['page']>1)echo $r->link('previous','chevron-left',['action'=>'users','q'=>$q,'state'=>$state,'page'=>$list['page']-1]);if($list['page']*40<$list['count'])echo $r->link('next','chevron-right',['action'=>'users','q'=>$q,'state'=>$state,'page'=>$list['page']+1]);echo '</nav>';
}elseif($view==='campaigns'){
 echo '<div class="chisimba-table-wrap"><table class="table"><thead><tr>';foreach(['subject','state','updated','edit'] as $k)echo '<th>'.$e($r->text($k)).'</th>';echo '</tr></thead><tbody>';foreach($campaigns->listing() as $c)echo '<tr><td>'.$e($c['subject']).'</td><td>'.$e($r->text($c['state'])).'</td><td>'.$e($c['updated_at']).'</td><td>'.$r->link('open','eye',['action'=>'compose','id'=>$c['id']]).'</td></tr>';echo '</tbody></table></div>';
}else{
 $save=['contact'=>'savecontact','compose'=>'savecampaign','settings'=>'savesettings'][$view];
 echo '<p role="status" data-audience-status>'.$e($error?$r->text($error):'').'</p><form method="post" data-audience-form data-failed="'.$e($r->text('failed_draft')).'" data-saving="'.$e($r->text('saving')).'" data-confirm="'.$e($r->text('confirm_queue')).'" action="'.$e($this->uri(['action'=>$save],'audience')).'">'.$hidden('csrf_token',$this->getVar('audienceCsrf')).$hidden('id',$record['id']??'').$hidden('version',$record['version']??0).$hidden('revision',$record['revision']??0).$hidden('create_id',$input['create_id']??bin2hex(random_bytes(16)));
 if($view==='contact'){
  echo $field('name').$field('email','email').'<div class="chisimba-form-field"><label for="aud-state">'.$e($r->text('state')).'</label><select id="aud-state" name="state">';foreach(['subscribed','unsubscribed','pending','suppressed'] as $v)echo '<option value="'.$v.'"'.(($input['state']??'')===$v?' selected':'').'>'.$e($r->text($v)).'</option>';echo '</select></div><p>'.$e($r->text('consent_help')).'</p>'.$check('consent',false).$field('evidence','textarea').$r->button('save','save');
 }elseif($view==='compose'){
  $progress=$record?$campaigns->progress($record['id']):null;
  echo '<div class="chisimba-notification chisimba-notification--'.($progress?$e($progress['tone']):'info').'" role="status" aria-live="polite" data-mail-progress data-progress-url="'.$e($this->uri(['action'=>'progress'],'audience')).'"'.(!$record?' hidden':'').'><strong data-mail-label>'.$e($progress['label']??'').'</strong><p data-mail-count>'.$e($progress['message']??'').'</p></div>';
  $editable=!$record||$record['state']==='draft';echo '<p role="status" data-campaign-state>'.$e($r->text($record['state']??'draft')).'</p><fieldset data-draft-fields'.(!$editable?' disabled':'').'>'.$field('subject').$field('greeting').$check('latest_recording',!empty($input['latest_recording'])).$field('body','textarea').$check('upcoming',!empty($input['upcoming'])).$check('support',!empty($input['support'])).'<p>'.$e($r->text('compose_help')).'</p>'.$r->button('save_preview','save').'</fieldset>';
  echo '<section class="chisimba-form-section"><h2>'.$e($r->text('preview')).'</h2><iframe sandbox title="'.$e($r->text('preview')).'" width="100%" height="520" data-audience-html-preview srcdoc="'.$e($record?$campaigns->composeHtml($record):'').'"></iframe><details><summary>'.$e($r->text('text_alternative')).'</summary><pre class="chisimba-text-preview" data-audience-preview>'.$e($record?($input['rendered']??$campaigns->compose($record)):'').'</pre></details><p>'.$e($r->text('banner_help')).' '.$e($r->text('footer_help')).'</p></section><div class="chisimba-form-actions">';
  echo $r->button($record&&$record['state']!=='draft'?'mail_queued':'queue',$record&&$record['state']!=='draft'?'check':'send','data-campaign-queue data-queued-label="'.$e($r->text('mail_queued')).'" '.(!$record||!$editable?'disabled ':'').'formaction="'.$e($this->uri(['action'=>'queue'],'audience')).'"');
  echo $r->button('cancel','x','data-campaign-cancel '.(!$record||$record['state']==='cancelled'?'disabled ':'').'formaction="'.$e($this->uri(['action'=>'cancel'],'audience')).'"').'</div><p role="status" aria-live="polite" data-campaign-feedback>'.$e($record&&$record['state']==='queued'?sprintf($r->text('queued_count'),count($input['recipients']??[])):'').'</p><p>'.$e($r->text('delivery_help')).'</p>';
 }else{
  if(!$this->getVar('audienceInput'))$input=['support_message'=>$cfg->getValue('AUDIENCE_SUPPORT_MESSAGE','audience',''),'hour'=>$cfg->getValue('WEBINAR_ANNOUNCEMENTS_HOUR','webinar',8),'timezone'=>$cfg->getValue('WEBINAR_ANNOUNCEMENTS_TIMEZONE','webinar','Africa/Johannesburg'),'enabled'=>$cfg->getValue('WEBINAR_ANNOUNCEMENTS_ENABLED','webinar')==='TRUE'];
  // Fields use current settings while preserving submitted values after an error.
  foreach(['support_message','hour','timezone'] as $k)echo '<div class="chisimba-form-field"><label for="aud-'.$k.'">'.$e($r->text($k)).'</label>'.($k==='support_message'?'<textarea id="aud-'.$k.'" name="'.$k.'" rows="6">'.$e($input[$k]).'</textarea>':'<input id="aud-'.$k.'" name="'.$k.'" '.($k==='hour'?'type="number" min="0" max="23"':'type="text"').'  value="'.$e($input[$k]).'">').'</div>';
  echo $check('enabled',!empty($input['enabled'])).'<p>'.$e($r->text('schedule_help')).'</p>'.$r->button('save','save');
 }
 echo '</form><script src="'.$e($this->getResourceUri('admin.js','audience').'?v=0.011').'"></script>';
}
echo '</section>';
