<?php
if (empty($GLOBALS['kewl_entry_point_run'])) die('You cannot view this page directly');
class administrationoverview extends ChisimbaObject
{
 private function text($language,$key,$fallback,$tokens=null){return $tokens===null?$language->languageText('mod_myadmin_'.$key,'myadmin',$fallback):$language->code2Txt('mod_myadmin_'.$key,'myadmin',$tokens,$fallback);}
 /** Assign every active person to exactly one highest system role. */
 private function presenceSummary($people){
  $user=$this->getObject('user','security');$contexts=$this->getObject('usercontext','context');
  $summary=array('administrators'=>0,'authors'=>0,'readonlys'=>0,'other'=>0,'in_contexts'=>0,'lobby'=>0);
  foreach((array)$people as $person){$userId=(string)$person['userid'];$scope=strtolower((string)$person['coursecode']);
   if($scope===''||$scope==='root'||$scope==='lobby')$summary['lobby']++;else $summary['in_contexts']++;
   if($user->inAdminGroup($userId))$summary['administrators']++;
   elseif(count((array)$contexts->getContextWhereLecturer($userId))>0)$summary['authors']++;
   elseif(count((array)$contexts->getContextWhereStudent($userId))>0)$summary['readonlys']++;
   else $summary['other']++;
  }
  return $summary;
 }
 public function show($queueToken='',$registrationToken='',$queueNotice=''){
  $metrics=$this->getObject('sitemetrics');$language=$this->getObject('language','language');$people=$this->getObject('loggedinusers','security')->getActiveUsers();$roles=$this->presenceSummary($people);$registrations=$metrics->newRegistrations()+$this->getObject('registrationservice','registration-service')->administrationSummary();$clock=$this->getObject('timeanddateservice','timeanddate-service');$icons=$this->getObject('iconservice','ui');$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
  $stats=array(array($this->text($language,'users','Users'),$metrics->countUsers(),$this->text($language,'users_help','Registered accounts')),array($language->code2Txt('mod_myadmin_courses','myadmin',null,'[-contexts-]'),$metrics->countCourses(),$language->code2Txt('mod_myadmin_courseshelp','myadmin',null,'[-contexts-] on this site')),array($this->text($language,'online','Online now'),count($people),$this->text($language,'online_help','Recently active people')));
  $roleCards=array(array('administrators',$this->text($language,'administrators','Administrators')),array('authors',$this->text($language,'authors','[-authors-]',array())),array('readonlys',$this->text($language,'readonlys','[-readonlys-]',array())),array('other',$this->text($language,'other_users','Other users')));
  $html='<section class="student-learning-overview site-health-overview" aria-labelledby="site-health-title"><header class="student-learning-overview__header"><div><p class="student-learning-overview__eyebrow">'.$e($this->text($language,'eyebrow','Site overview')).'</p><h1 id="site-health-title">'.$e($this->text($language,'name','My Administration')).'</h1><p>'.$e($this->text($language,'intro','See the health and current activity of this site.')).'</p></div><span class="student-learning-overview__count">'.$e($this->text($language,'live','Live')).'</span></header><div class="site-health-grid">';
  foreach($stats as $stat)$html.='<article class="site-health-card"><span>'.$e($stat[0]).'</span><strong>'.$e(number_format($stat[1])).'</strong><p>'.$e($stat[2]).'</p></article>';
  $html.='</div><section class="presence-overview" aria-labelledby="presence-title"><header><div><p class="student-learning-overview__eyebrow">'.$e($this->text($language,'presence_eyebrow','Live activity')).'</p><h2 id="presence-title">'.$e($this->text($language,'presence_title','Who is online')).'</h2></div><div class="presence-scope-summary"><span>'.$e($roles['in_contexts'].' '.$this->text($language,'in_contexts','in [-contexts-]',array())).'</span><span>'.$e($roles['lobby'].' '.$this->text($language,'in_lobby','in the site lobby')).'</span></div></header><div class="presence-role-grid">';
  foreach($roleCards as $card)$html.='<article class="presence-role-card presence-role-card--'.$e($card[0]).'"><span class="presence-role-card__icon" aria-hidden="true">●</span><div><strong>'.$e(number_format($roles[$card[0]])).'</strong><span>'.$e($card[1]).'</span></div></article>';
  $html.='</div><p class="presence-overview__help">'.$e($this->text($language,'presence_help','Each person is counted once using their highest role.')).'</p></section>';
  $html.='<section class="registration-health" aria-labelledby="registration-health-title"><header><div><p class="student-learning-overview__eyebrow">'.$e($this->text($language,'registration_eyebrow','Account activity')).'</p><h2 id="registration-health-title">'.$e($this->text($language,'registration_title','New registrations')).'</h2></div></header><div class="registration-health__metrics">';
  foreach(array('today','week','month') as $period)$html.='<article><span>'.$e($this->text($language,'registration_'.$period,ucfirst($period))).'</span><strong>'.$e(number_format($registrations[$period])).'</strong></article>';
  $html.='</div><div class="registration-health__columns"><section><h3>'.$e($this->text($language,'registration_recent','Latest registrations')).'</h3>';
  if(empty($registrations['recent']))$html.='<p class="chisimba-notice">'.$e($this->text($language,'registration_none','No completed registrations yet.')).'</p>';else{$html.='<ol class="registration-health__recent">';foreach($registrations['recent'] as $person)$html.='<li><span>'.$e(trim($person['firstname'].' '.$person['surname'])).'</span><time>'.$e($clock->formatDate($person['creationdate'])).'</time></li>';$html.='</ol>';}
  $html.='</section><section><h3>'.$e($this->text($language,'registration_unconfirmed','Waiting for confirmation')).'</h3><p>'.$e($this->text($language,'registration_unconfirmed_help','These people registered more than 24 hours ago and have not yet confirmed their email address.')).'</p>';
  if(empty($registrations['unconfirmed']))$html.='<p class="chisimba-notice chisimba-notice--success">'.$e($this->text($language,'nothing_requiring_action','Nothing requiring action')).'</p>';else{$html.='<div class="registration-health__pending">';foreach($registrations['unconfirmed'] as $pending){$recentReminder=!empty($pending['last_reminder_at'])&&strtotime($pending['last_reminder_at'])>strtotime('-24 hours');$html.='<article><div><strong>'.$e(trim($pending['first_name'].' '.$pending['surname'])).'</strong><span>'.$e($pending['email_address']).'</span><small>'.$e($clock->formatDateTime($pending['created_at'])).'</small></div>';if($recentReminder)$html.='<span class="registration-health__reminded">'.$e($this->text($language,'registration_reminded','Reminder sent recently')).'</span>';else $html.='<form method="post" action="index.php?module=myadmin&amp;action=sendregistrationreminder"><input type="hidden" name="csrf_token" value="'.$e($registrationToken).'"><input type="hidden" name="pending_id" value="'.$e($pending['id']).'"><button type="submit" class="button chisimba-button-secondary">'.$icons->render('mail-plus',array('size'=>18,'decorative'=>true)).' '.$e($this->text($language,'registration_send_reminder','Send reminder and offer help')).'</button></form>';$html.='</article>';}$html.='</div>';}
  $html.='</section></div></section>';
  $mail=$this->getObject('mailqueuehealth')->summary();$state=$mail['timer'];$stateLabel=$this->text($language,'mail_'.$state,$state==='running'?'Running':($state==='stalled'?'Stalled':'Not yet observed'));$last=$mail['last_sent']?$clock->formatDateTime($mail['last_sent']):$this->text($language,'mail_never','Never');
  $html.='<section class="mail-health mail-health--'.$e($state).'" aria-labelledby="mail-health-title"><header><div><p class="student-learning-overview__eyebrow">'.$e($this->text($language,'mail_eyebrow','Communications')).'</p><h2 id="mail-health-title">'.$e($this->text($language,'mail_title','Mail queue health')).'</h2></div><span class="mail-health__state"><span aria-hidden="true">●</span> '.$e($stateLabel).'</span></header>';
  if($queueNotice!=='')$html.='<p class="chisimba-notice chisimba-notice--info">'.$e($queueNotice).'</p>';
  $html.='<div class="mail-health__grid"><article><span>'.$e($this->text($language,'mail_timer','Mail timer')).'</span><strong>'.$e($stateLabel).'</strong><small>'.($mail['last_run']?$e($clock->formatDateTime($mail['last_run'])):$e($this->text($language,'mail_never','Never'))).'</small></article><article><span>'.$e($this->text($language,'mail_queued','Mails in queue')).'</span><strong>'.$e(number_format($mail['queued'])).'</strong></article><article><span>'.$e($this->text($language,'mail_last_sent','Last mail sent')).'</span><strong class="mail-health__date">'.$e($last).'</strong></article><article><span>'.$e($this->text($language,'mail_sent','Emails sent')).'</span><strong>'.$e(number_format($mail['sent'])).'</strong><small>'.$e(number_format($mail['failed'])).' '.$e($this->text($language,'mail_failed','Failed')).'</small></article></div><footer><p>'.$e($this->text($language,'mail_help','The timer should check the queue every minute. Run the queue now to recover waiting mail and confirm that delivery can start.')).'</p><form method="post" action="index.php?module=myadmin&amp;action=runmailqueue"><input type="hidden" name="csrf_token" value="'.$e($queueToken).'"/><button type="submit" class="button">'.$e($this->text($language,'mail_run','Run mail queue now')).'</button></form></footer></section><section class="site-health-attention"><div><p class="student-learning-overview__eyebrow">'.$e($this->text($language,'attention','Needs attention')).'</p><h2>'.$e($this->text($language,'nothing_requiring_action','Nothing requiring action')).'</h2><p>'.$e($this->text($language,'attention_help','Administrative requests and service warnings will appear here as those services provide them.')).'</p></div></section></section>';
  return $html;
 }
}
?>
