const {chromium}=require('playwright-core');const fs=require('fs'),assert=require('assert');
(async()=>{const f=JSON.parse(fs.readFileSync('/tmp/mcq-counts-fixture.json'));const base='https://chisimba.test:8445/ch/index.php?module=mcqgenerator';const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--host-resolver-rules=MAP chisimba.test 127.0.0.1']});try{const c=await b.newContext({ignoreHTTPSErrors:true});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.locator('[name=username]').fill(f.users.teacher);await p.locator('[name=password]').fill(f.password);await p.waitForTimeout(1100);await Promise.all([p.waitForNavigation({waitUntil:'networkidle'}),p.getByRole('button',{name:'Login',exact:true}).click()]);
await p.waitForTimeout(1500);
const picker=base+'&action=examview&id='+f.exams[0]+'&setid='+f.sets[0];await p.goto(picker);
for(let i=0;i<3;i++)await p.locator('[name="selected[]"]').nth(i).check();assert.equal(await p.locator('[data-selected-count]').innerText(),'3');assert.equal(await p.locator('[data-add-total]').innerText(),'3');await p.locator('[name="selected[]"]').nth(2).uncheck();assert.equal(await p.locator('[data-add-total]').innerText(),'2');
await p.locator('[name="selected[]"]').nth(14).scrollIntoViewIfNeeded();assert.equal(await p.locator('[data-exam-add-count]').evaluate(e=>getComputedStyle(e).position),'sticky');assert(await p.locator('[data-exam-add-count]').evaluate(e=>e.getBoundingClientRect().top>=0&&e.getBoundingClientRect().top<100));await p.screenshot({path:'/tmp/mcq-count-selection.png'});
await p.locator('[data-exam-add-count] button').click();await p.waitForURL(/saved=1/);await p.reload();assert.equal(await p.locator('[data-keep-count]').innerText(),'2');
await p.getByRole('link',{name:'Review or remove questions',exact:true}).click();const first=p.locator('[data-exam-entry]').first();await first.locator('[data-exam-remove]').click();assert.equal(await p.locator('[data-keep-count]').innerText(),'1');assert.equal(await p.locator('[data-remove-count]').innerText(),'1');assert(await first.getByText('Removed when you save',{exact:true}).isVisible());await first.getByRole('button',{name:'Undo removal',exact:true}).click();assert.equal(await p.locator('[data-keep-count]').innerText(),'2');await first.getByRole('button',{name:'Remove from exam',exact:true}).click();await p.locator('[data-exam-edit-count] button').click();await p.waitForURL(/saved=1/);await p.reload();assert.equal(await p.locator('[data-exam-entry]').count(),1);assert.equal(await p.locator('[data-keep-count]').innerText(),'1');
await p.goto(picker);assert.equal(await p.locator('[name="selected[]"]').count(),15);assert.equal(await p.locator('[name="selected[]"]:disabled').count(),1);await p.locator('[name="selected[]"]').first().check();assert.equal(await p.locator('[data-add-total]').innerText(),'2');
// In-document review links must preserve pending selection without a leave-page dialog.
let dialogs=0;p.on('dialog',async d=>{dialogs++;await d.dismiss();});await p.locator('[data-exam-add-count] a').click();assert.equal(dialogs,0);assert.equal(await p.locator('[data-selected-count]').innerText(),'1');
await p.setViewportSize({width:390,height:844});await p.locator('[name="selected[]"]').nth(14).scrollIntoViewIfNeeded();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert(await p.locator('[data-exam-add-count]').evaluate(e=>e.getBoundingClientRect().top>=0&&e.getBoundingClientRect().bottom<innerHeight));await p.screenshot({path:'/tmp/mcq-count-mobile.png'});
// Save the pending addition then test removal through the visible action.
await p.locator('[data-exam-add-count] button').click();await p.waitForURL(/saved=1/);await p.locator('[data-exam-remove]').first().click();assert.equal(await p.locator('[data-keep-count]').innerText(),'1');await p.locator('[data-exam-edit-count] button').click();await p.waitForURL(/saved=1/);await p.reload();assert.equal(await p.locator('[data-keep-count]').innerText(),'1');assert.deepEqual(errors,[]);
console.log('PASS live selection/deselection totals; sticky desktop/mobile summary; remove/undo/save/reload; source unchanged and re-addable; checkbox removal; anchor preserves pending selection; no JS errors.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
