const {chromium}=require('playwright-core'),fs=require('fs'),assert=require('assert');
(async()=>{const f=JSON.parse(fs.readFileSync('/tmp/short-browser-ids.json'));const base='https://chisimba.test:8445/ch/index.php?module=mcqgenerator';const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--host-resolver-rules=MAP chisimba.test 127.0.0.1']});try{const c=await b.newContext({ignoreHTTPSErrors:true,storageState:'/tmp/short-browser-state.json'});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'&action=view&id='+f.short);assert.equal(await p.locator('[data-question-review]').count(),2);assert.equal(await p.locator('[name*="[options]"]').count(),0);
await p.locator('#modelAnswer0').fill('Reduced heat and shelter.');await p.locator('#markingPoints0').fill('One mark for each of reduced heat and shelter.');await p.locator('[name=reviewed]').check();await p.getByRole('button',{name:'Save questions',exact:true}).click();await p.waitForURL(/action=view/);await p.reload();assert.equal(await p.locator('#modelAnswer0').inputValue(),'Reduced heat and shelter.');assert.equal(await p.locator('#marks1').inputValue(),'4');
// Server validation retains the draft rather than losing an overlong answer.
const long='word '.repeat(121);await p.locator('#modelAnswer0').fill(long);await p.getByRole('button',{name:'Save questions',exact:true}).click();await p.waitForURL(/action=save/);assert.equal(await p.locator('#modelAnswer0').inputValue(),long);assert((await p.locator('body').innerText()).includes('at most 120 words'));await p.locator('#modelAnswer0').fill('Reduced heat and shelter.');await p.getByRole('button',{name:'Save questions',exact:true}).click();await p.waitForURL(/action=view/);
for(const answers of [0,1]){const res=await c.request.get(base+'&action=download&id='+f.short+'&format=txt&answers='+answers);assert.equal(res.status(),200);const text=await res.text();assert.equal(text.includes('Reduced heat and shelter.'),!!answers);assert.equal(text.includes('One mark for each'),!!answers);}
await p.locator('[data-question-review]').first().screenshot({path:'/tmp/short-answer-review.png'});
// Assemble both types in the same exam. Suggested short-answer marks carry across.
for(const [id,n] of [[f.original,1],[f.short,2]]){await p.goto(base+'&action=examview&id='+f.exam+'&setid='+id);for(let i=0;i<n;i++)await p.locator('[name="selected[]"]').nth(i).check();await p.locator('[data-exam-add-count] button').click();await p.waitForURL(/saved=1/);}
await p.reload();assert.equal(await p.locator('[data-exam-entry]').count(),3);const marks=await p.locator('[data-exam-entry] input[name$="[marks]"]').evaluateAll(es=>es.map(e=>Number(e.value)));assert.deepEqual(marks,[1,2,4]);await p.locator('[name="exam[mixAnswers]"]').check();await p.locator('[data-exam-edit-count] button').click();await p.waitForURL(/saved=1/);await p.reload();const shortCard=p.locator('[data-exam-entry]').nth(1);await shortCard.locator('summary').click();assert((await shortCard.innerText()).includes('Reduced heat and shelter.'));await shortCard.screenshot({path:'/tmp/short-answer-exam.png'});
for(const answers of [0,1]){const res=await c.request.get(base+'&action=examdownload&id='+f.exam+'&answers='+answers);assert.equal(res.status(),200);fs.writeFileSync('/tmp/short-mixed-'+(answers?'key':'paper')+'.odt',await res.body());}
// Help, mobile form, negative ownership and CSRF.
await p.goto(base+'&action=view&id='+f.short);const help=p.getByRole('button',{name:'Help with this page',exact:true});await help.click();const drawer=p.locator('#'+await help.getAttribute('aria-controls'));assert((await drawer.innerText()).includes('Short answers from saved chapters'));await p.keyboard.press('Escape');assert.equal(await help.getAttribute('aria-expanded'),'false');await p.setViewportSize({width:390,height:844});await p.reload();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('[data-question-review]').first().screenshot({path:'/tmp/short-answer-review-mobile.png'});
let res=await c.request.post(base+'&action=derive&id='+f.original,{form:{csrf_token:'invalid',title:'Must not clone'}});assert.equal(res.status(),422);
for(const role of ['other','student']){const oc=await b.newContext({ignoreHTTPSErrors:true});const op=await oc.newPage();await op.goto(base);await op.locator('[name=username]').fill(f.users[role]);await op.locator('[name=password]').fill(f.password);await op.waitForTimeout(1100);await Promise.all([op.waitForNavigation({waitUntil:'networkidle'}),op.getByRole('button',{name:'Login',exact:true}).click()]);res=await oc.request.get(base+'&action=download&id='+f.short+'&format=txt&answers=1');assert.equal(res.status(),role==='other'?404:403);await oc.close();}
assert.deepEqual(errors,[]);console.log('PASS editable short answers/criteria/marks; invalid draft recovery; save/reload; answer-safe downloads; mixed paper/suggested marks/MCQ mixing; Help; 390px form; ownership and CSRF.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
