<?php
if(empty($GLOBALS['kewl_entry_point_run']))die('You cannot view this page directly');
class liveclassreminderservice extends ChisimbaObject
{
 public function init(){$this->jobs=$this->getObject('dbliveclassreminders');$this->sessions=$this->getObject('dbliveclasssessions');$this->members=$this->getObject('usercontext','context');$this->users=$this->getObject('user','security');$this->mail=$this->getObject('communicationservice','communications');$this->language=$this->getObject('language','language');$this->clock=$this->getObject('timeanddateservice','timeanddate-service');$this->config=$this->getObject('altconfig','config');}
 public function schedule(array $session,array $leads){$start=strtotime($session['starts_at']);foreach(array_unique(array_map('intval',$leads)) as $lead){if(!in_array($lead,array(1440,60),true))continue;$due=$start-($lead*60);if($due>time())$this->jobs->schedule($session['id'],$lead,date('Y-m-d H:i:s',$due));}}
 public function cancel($sessionId){$this->jobs->cancelSession($sessionId);}
 public function run($limit=20){$summary=array('selected'=>0,'queued'=>0,'recipients'=>0,'failed'=>0);foreach($this->jobs->due($limit) as $job){$summary['selected']++;$session=$this->sessions->one($job['session_id']);if(!$session||$session['status']!=='scheduled'||empty($session['context_code'])){$this->jobs->cancelSession($job['session_id']);continue;}$result=$this->dispatch($session,$job);if($result['ok']){$this->jobs->complete($job['id'],$result['count']);$summary['queued']++;$summary['recipients']+=$result['count'];}else $summary['failed']++;}return $summary;}
 private function dispatch(array $session,array $job){$lead=(int)$job['lead_minutes'];$subject=$this->text($lead===1440?'reminder_subject_24h':'reminder_subject_1h');$body=$this->text($lead===1440?'reminder_body_24h':'reminder_body_1h');$url=rtrim($this->config->getSiteRoot(),'/').'/index.php?module=liveclass&action=view&id='.rawurlencode($session['id']);$replace=array('{session}'=>$session['name'],'{starts}'=>$this->clock->formatDateTime($session['starts_at']),'{url}'=>$url);$subject=strtr($subject,$replace);$body=strtr($body,$replace);$count=0;$failed=false;foreach((array)$this->members->getContextStudents($session['context_code']) as $member){$id=(string)($member['userid']??$member['userId']??$member['id']??'');$email=trim((string)$this->users->email($id));if(!filter_var($email,FILTER_VALIDATE_EMAIL))continue;$name=trim((string)($member['firstname']??'').' '.(string)($member['surname']??''));$queued=$this->mail->queueEmail(array('to'=>$email,'toName'=>$name,'subject'=>$subject,'text'=>$body,'idempotencyKey'=>'liveclass:'.$job['id'].':'.hash('sha256',$id),'metadata'=>array('purpose'=>'live_session_reminder','session_id'=>$session['id'],'context_code'=>$session['context_code'],'lead_minutes'=>$lead)));if(empty($queued['ok']))$failed=true;else $count++;}return array('ok'=>!$failed,'count'=>$count);}
 private function text($key){return $this->language->languageText('mod_liveclass_'.$key,'liveclass');}
}
?>
