<?php
if (empty($GLOBALS['kewl_entry_point_run'])) die('You cannot view this page directly');
class liveclasscontentrenderer extends ChisimbaObject
{
    public function init(){ $this->sessions=$this->getObject('dbliveclasssessions','liveclass');$this->life=$this->getObject('liveclasslifecycle','liveclass');$this->language=$this->getObject('language','language');$this->clock=$this->getObject('timeanddateservice','timeanddate-service');$this->icons=$this->getObject('iconservice','ui'); }
    public function render(array $page,$contextCode,$mayManage=false){
        $session=$this->sessions->one((string)($page['provideritemid']??''));if(!$session||(string)$session['context_code']!==(string)$contextCode)return '';
        $state=$this->life->state($session);$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$minutes=$this->life->joinWindowMinutes();
        $url=$this->uri(array('action'=>$state['phase']==='finished'?'view':'join','id'=>$session['id']),'liveclass');
        $label=$state['phase']==='live'?$this->t('join'):($state['phase']==='finished'?$this->t('review_session'):$this->t('join'));
        $image=$this->safeUrl($session['image_url']??'');$visual=$image!==null?'<img src="'.$e($image).'" alt="">':'<div class="liveclass-flow-art" aria-hidden="true">'.$this->icons->render('video',array('decorative'=>true)).'<span>'.$e($this->t('context_type')).'</span></div>';
        $disabled=$state['phase']==='upcoming'||$state['phase']==='cancelled';$action=$disabled?'<span class="button chisimba-button-primary liveclass-join-disabled" aria-disabled="true">'.$this->icons->render('lock',array('decorative'=>true)).'<span>'.$e($label).'</span></span>':'<a class="button chisimba-button-primary" href="'.$e($url).'">'.$this->icons->render($state['phase']==='finished'?'play':'log-in',array('decorative'=>true)).'<span>'.$e($label).'</span></a>';
        $notice=$state['phase']==='upcoming'?strtr($this->t('join_locked'),array('{minutes}'=>$minutes)):($state['phase']==='live'?$this->t('live_now'):$this->t('session_finished'));
        return '<section class="liveclass-flow-card"><div class="liveclass-flow-visual">'.$visual.'<time datetime="'.$e(date('c',$state['starts_at'])).'">'.$e($this->clock->formatDateTime($session['starts_at'])).'</time></div><div class="liveclass-flow-copy"><p class="chisimba-eyebrow">'.$e($this->t('context_type')).'</p><h2>'.$e($session['name']).'</h2><p>'.$e($session['description']).'</p><p class="liveclass-flow-state liveclass-flow-state-'.$e($state['phase']).'">'.$this->icons->render($state['phase']==='live'?'radio':'clock',array('decorative'=>true)).'<span>'.$e($notice).'</span></p><div class="chisimba-form-actions">'.$action.($mayManage?'<a class="button chisimba-button-secondary" href="'.$e($this->uri(array('action'=>'view','id'=>$session['id']),'liveclass')).'">'.$this->icons->render('settings',array('decorative'=>true)).'<span>'.$e($this->t('start')).'</span></a>':'').'</div></div></section>'.$this->styles();
    }
    private function safeUrl($value){if(!filter_var($value,FILTER_VALIDATE_URL))return null;$p=parse_url($value);return strtolower((string)($p['scheme']??''))==='https'?$value:null;}
    private function t($key){return $this->language->languageText('mod_liveclass_'.$key,'liveclass');}
    private function styles(){return '<style>.contextcontent-live-session{max-width:1050px;margin:1rem auto}.liveclass-flow-card{display:grid;grid-template-columns:minmax(260px,42%) 1fr;overflow:hidden;border:1px solid var(--chisimba-border,#d7dce2);border-radius:18px;background:var(--chisimba-surface,#fff);box-shadow:0 14px 38px rgba(20,30,50,.12)}.liveclass-flow-visual{position:relative;min-height:290px;background:linear-gradient(145deg,var(--canvas-primary,#1769aa),var(--canvas-secondary,#38a169));color:#fff}.liveclass-flow-visual img{width:100%;height:100%;min-height:290px;object-fit:cover}.liveclass-flow-art{display:flex;height:100%;min-height:290px;flex-direction:column;align-items:center;justify-content:center;gap:1rem;background:radial-gradient(circle at 25% 15%,rgba(255,255,255,.28),transparent 36%),linear-gradient(135deg,var(--canvas-primary,#1769aa),var(--canvas-secondary,#38a169))}.liveclass-flow-art svg{width:72px;height:72px}.liveclass-flow-art span{font-size:1.15rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.liveclass-flow-visual time{position:absolute;left:1rem;bottom:1rem;padding:.55rem .75rem;border-radius:9px;background:rgba(12,20,28,.82);font-weight:800}.liveclass-flow-copy{padding:clamp(1.25rem,4vw,2.5rem)}.liveclass-flow-copy h2{margin:.2rem 0 .7rem;font-size:clamp(1.55rem,3vw,2.35rem)}.liveclass-flow-state{display:flex;align-items:center;gap:.5rem;margin:1.2rem 0;padding:.7rem .85rem;border-radius:9px;background:var(--chisimba-surface-muted,#edf3f6);font-weight:750}.liveclass-flow-state svg{width:20px}.liveclass-flow-state-live{background:#e2f6e9;color:#176c36}.liveclass-join-disabled{cursor:not-allowed;filter:saturate(.35);opacity:.62}.liveclass-join-disabled:hover{transform:none}@media(max-width:720px){.liveclass-flow-card{grid-template-columns:1fr}.liveclass-flow-visual,.liveclass-flow-art,.liveclass-flow-visual img{min-height:210px}}</style>';}
}
?>
