<?php
if (empty($GLOBALS['kewl_entry_point_run'])) die('You cannot view this page directly');
class liveclass extends controller
{
    const CSRF='liveclass_mutation';
    public function init(){
        $this->user=$this->getObject('user','security');$this->context=$this->getObject('dbcontext','context');$this->sessions=$this->getObject('dbliveclasssessions');
        $this->auth=$this->getObject('liveclassauthorizationservice');$this->service=$this->getObject('liveclassservice');$this->reminders=$this->getObject('liveclassreminderservice');$this->life=$this->getObject('liveclasslifecycle');$this->clock=$this->getObject('timeanddateservice','timeanddate-service');$this->lang=$this->getObject('language','language');
        $this->csrf=$this->getObject('nativeauthwebcomposition','security')->build()['csrf'];$this->setLayoutTemplate('liveclass_layout_tpl.php');
        $this->appendArrayVar('headerParams','<link rel="stylesheet" href="'.$this->getResourceUri('liveclass.css').'">');
        $this->appendArrayVar('headerParams','<script defer src="'.$this->getResourceUri('liveclass.js').'"></script>');
    }
    public function requiresLogin($action=null){return true;}
    public function dispatch($action){$action=(string)$action;if(in_array($action,array('save','cancel','end'),true))return $this->{$action}();if($action==='add')return $this->form();if($action==='join')return $this->join();if($action==='view')return $this->view();return $this->index();}
    private function index($message='',$error=''){
        $contextCode=(string)$this->context->getContextCode();$rows=$contextCode!==''?$this->sessions->forContext($contextCode):$this->sessions->webinars();
        $rows=array_values(array_filter($rows,function($row){return $this->auth->canView($row);}));
        $this->common();$this->setVar('liveclassSessions',$rows);$this->setVar('liveclassCanCreate',$this->auth->canCreate($contextCode!==''?'context':'webinar',$contextCode));$this->setVar('liveclassMessage',$message);$this->setVar('liveclassError',$error);return 'index_tpl.php';
    }
    private function form($message='',$error=''){$contextCode=(string)$this->context->getContextCode();$type=$contextCode!==''?'context':'webinar';if(!$this->auth->canCreate($type,$contextCode))return $this->index('',$this->t('forbidden'));$this->common();$config=$this->getObject('dbsysconfig','sysconfig');$provider=strtolower(trim((string)$config->getValue('LIVECLASS_PROVIDER','liveclass')));if(!in_array($provider,array('google_meet','zoom','external','bigbluebutton'),true)||($provider==='bigbluebutton'&&!$this->service->available()))$provider='external';$this->setVar('liveclassDefaultProvider',$provider);$this->setVar('liveclassType',$type);$this->setVar('liveclassContextCode',$contextCode);$this->setVar('liveclassFlowChapter',$this->param('flow_chapter'));$this->setVar('liveclassFlowParent',$this->param('flow_parent'));$this->setVar('liveclassDateExample',$this->clock->formatDate(date('Y-m-d H:i:s',strtotime('+21 days'))));$this->setVar('liveclassCsrf',$this->csrf->issue(self::CSRF));$this->setVar('liveclassMessage',$message);$this->setVar('liveclassError',$error);return 'form_tpl.php';}
    private function save(){if(!$this->validPost())return $this->form('',$this->t('invalid'));$contextCode=(string)$this->context->getContextCode();$type=$contextCode!==''?'context':'webinar';if(!$this->auth->canCreate($type,$contextCode))return $this->index('',$this->t('forbidden'));$name=mb_substr($this->param('name'),0,255);$instant=$this->clock->parseConfiguredLocalDateTime($this->param('start_date'),$this->param('start_time'));$starts=$instant===null?null:$this->clock->toStorage($instant);$duration=(int)$this->param('duration_minutes');$provider=$this->param('provider_code');$url=$this->secureUrl($this->param('meeting_url'));$image=$this->param('image_url');if($image!==''&&$this->secureUrl($image)===null)return $this->form('',$this->t('invalid'));if($name===''||$starts===null||$duration<5||$duration>1440||!in_array($provider,array('google_meet','zoom','external','bigbluebutton'),true)||($provider!=='bigbluebutton'&&$url===null))return $this->form('',$this->t('invalid'));$id=bin2hex(random_bytes(16));$now=date('Y-m-d H:i:s');$session=array('id'=>$id,'session_type'=>$type,'context_code'=>$type==='context'?$contextCode:null,'name'=>$name,'description'=>mb_substr($this->param('description'),0,10000),'image_url'=>$image===''?null:$image,'starts_at'=>$starts,'duration_minutes'=>$duration,'record_session'=>$provider==='bigbluebutton'&&$this->boolParam('record_session')?1:0,'provider_code'=>$provider,'meeting_url'=>$url,'provider_meeting_id'=>'chisimba-'.$id,'status'=>'scheduled','created_by'=>$this->user->userId(),'created_at'=>$now,'updated_at'=>$now);$this->sessions->createSession($session);$leads=array();if($this->boolParam('reminder_24h'))$leads[]=1440;if($this->boolParam('reminder_1h'))$leads[]=60;$this->reminders->schedule($session,$leads);$chapter=$this->param('flow_chapter');if($type==='context'&&$chapter!==''){$page=$this->getObject('contentauthoringservice','contextcontent')->createNativePage(array('contextcode'=>$contextCode,'chapterid'=>$chapter,'parentid'=>$this->param('flow_parent'),'contenttype'=>'live_session','title'=>$name,'body'=>'','language'=>'en','providermodule'=>'liveclass','provideritemid'=>$id));return $this->nextAction('viewpage',array('id'=>$page,'message'=>'pagesaved'),'contextcontent');}return $this->index($this->t('saved'));}
    private function view($message='',$error=''){$session=$this->session();if(!$session||!$this->auth->canView($session))return $this->index('',$this->t('not_found'));$this->common();$mayManage=$this->auth->canManage($session);$this->setVar('liveclassSession',$session);$this->setVar('liveclassLifecycle',$this->life->state($session));$this->setVar('liveclassJoinWindow',$this->life->joinWindowMinutes());$this->setVar('liveclassMayManage',$mayManage);$this->setVar('liveclassReminderJobs',$mayManage?$this->getObject('dbliveclassreminders')->forSession($session['id']):array());$this->setVar('liveclassRecordings',$session['provider_code']==='bigbluebutton'&&$this->service->available()?$this->service->recordings($session):array());$this->setVar('liveclassCsrf',$this->csrf->issue(self::CSRF));$this->setVar('liveclassMessage',$message);$this->setVar('liveclassError',$error);return 'view_tpl.php';}
    private function join(){$session=$this->session();if(!$session||!$this->auth->canView($session))return $this->index('',$this->t('not_found'));if(!$this->life->state($session)['can_join'])return $this->view('',$this->lockedMessage());if($session['provider_code']!=='bigbluebutton'){$url=$this->secureUrl($session['meeting_url']??'');if($url===null)return $this->view('',$this->t('provider_error'));header('Location: '.$url,true,303);exit;}if(!$this->service->available())return $this->view('',$this->t('provider_missing'));$moderator=$this->auth->canManage($session);if($moderator){$prepared=$this->service->prepare($session,$this->absoluteUrl(array('action'=>'view','id'=>$session['id'])));if(empty($prepared['ok']))return $this->view('',$this->t('provider_error'));}$url=$this->service->joinUrl($session,$this->user->fullname(),$this->user->userId(),$moderator);header('Location: '.$url,true,303);exit;}
    private function cancel(){return $this->stateMutation('cancelled','cancelled');}
    private function end(){if(!$this->validPost())return $this->index('',$this->t('invalid'));$session=$this->session();if(!$session||!$this->auth->canManage($session))return $this->index('',$this->t('forbidden'));if($session['provider_code']==='bigbluebutton'&&$this->service->available())$this->service->end($session);$this->sessions->saveSession($session['id'],array('status'=>'ended','updated_at'=>date('Y-m-d H:i:s')));return $this->view($this->t('ended'));}
    private function stateMutation($status,$message){if(!$this->validPost())return $this->index('',$this->t('invalid'));$session=$this->session();if(!$session||!$this->auth->canManage($session))return $this->index('',$this->t('forbidden'));$this->sessions->saveSession($session['id'],array('status'=>$status,'updated_at'=>date('Y-m-d H:i:s')));if($status==='cancelled')$this->reminders->cancel($session['id']);return $this->index($this->t($message));}
    private function common(){ $keys=array('title','heading','intro','add','empty','session_type','context_type','webinar_type','name','description_field','feature_image','feature_image_help','starts','start_date','start_time','date_format_help','duration','record','yes','no','provider','google_meet','zoom','external','bigbluebutton','meeting_url','meeting_url_help','reminders','reminder_24h','reminder_1h','reminder_pending','reminder_queued','reminder_cancelled','reminder_recipients','save','cancel_action','join','join_locked','live_now','session_finished','review_session','start','cancel_session','end','recordings','no_recordings','provider_missing','status_scheduled','status_cancelled','status_ended');$labels=array();foreach($keys as $key)$labels[$key]=$this->t($key);$this->setVar('liveclassLabels',$labels);$this->setVar('liveclassProviderAvailable',$this->service->available()); }
    private function lockedMessage(){return strtr($this->t('join_locked'),array('{minutes}'=>$this->life->joinWindowMinutes()));}
    private function session(){ $id=$this->param('id');return preg_match('/^[a-f0-9]{32}$/',$id)?$this->sessions->one($id):null; }
    private function validPost(){return strtoupper((string)($_SERVER['REQUEST_METHOD']??''))==='POST'&&$this->csrf->consume(self::CSRF,$this->param('csrf_token'));}
    private function param($name){$value=$this->getParam($name,'');return is_scalar($value)?trim((string)$value):'';}
    private function boolParam($name){return in_array(strtolower($this->param($name)),array('1','yes','true','on'),true);}
    private function timestamp($value){$time=strtotime($value);return $time===false?null:date('Y-m-d H:i:s',$time);}
    private function secureUrl($value){if(!filter_var($value,FILTER_VALIDATE_URL))return null;$parts=parse_url($value);return strtolower((string)($parts['scheme']??''))==='https'?$value:null;}
    private function t($key){return $this->lang->languageText('mod_liveclass_'.$key,'liveclass');}
    private function absoluteUrl(array $params){$config=$this->getObject('altconfig','config');return rtrim($config->getSiteRoot(),'/').'/'.ltrim($this->uri($params,'liveclass'),'/');}
}
?>
