const fs=require('fs'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_CORE || 'playwright-core');
(async()=>{
const f=JSON.parse(fs.readFileSync(process.env.SPOKEN_BROWSER_FIXTURE || '/tmp/spoken-fixture.json'));const base='https://chisimba.test:8445/ch/index.php';
const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--host-resolver-rules=MAP chisimba.test 127.0.0.1','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const errors=[];
// One second of synthetic PCM for the file-upload fallback.
const wav=Buffer.alloc(44+44100*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);
for(let i=0;i<44100;i++)wav.writeInt16LE(Math.round(2000*Math.sin(2*Math.PI*440*i/44100)),44+i*2);
fs.writeFileSync('/tmp/spoken-qa.wav',wav);
async function login(role) {
 const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},permissions:['microphone']});const p=await c.newPage();
 p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+'?module=spokenassessment');
 await p.locator('[name=username]').fill(f.users[role]);await p.locator('[name=password]').fill(f.password);
 await p.waitForTimeout(1100);await p.getByRole('button',{name:'Login',exact:true}).click();
 await p.goto(base+'?module=context&action=joincontext&contextcode='+f.context);
 return {c,p};
}
assert(/^spqa[a-f0-9]+$/.test(f.context),'Disposable local fixture required');
const creator=await login('teacher');await creator.p.goto(base+'?module=spokenassessment&action=edit');
await creator.p.locator('[name=title]').fill('Explain an observed adaptation');
await creator.p.locator('[name=prompt]').fill('Observe a leaf. Distinguish observation from inference.');
await creator.p.locator('[name=outcomes]').fill('Describe evidence and acknowledge uncertainty.');
await creator.p.locator('[name=published]').check();await creator.p.getByRole('button',{name:'Save activity',exact:true}).click();
f.activity=new URL(creator.p.url()).searchParams.get('id');assert(f.activity);await creator.c.close();
const {c,p}=await login('student');const activity=base+'?module=spokenassessment&action=activity&id='+f.activity;
await p.goto(activity);assert(await p.locator('[data-record]').isEnabled());fs.writeFileSync('/tmp/spoken-test-page.html',await p.content());
await p.locator('[data-contextual-help-open]').click();await p.keyboard.press('Escape');
await p.locator('[name=audio]').setInputFiles({name:'spoof.mp3',mimeType:'audio/mpeg',buffer:Buffer.from('This is not audio.')});
await p.locator('[name=consent]').check();await p.getByRole('button',{name:'Submit audio',exact:true}).click();
await p.waitForFunction(()=>document.querySelector('[data-record-status]').textContent.includes('supported audio'));
assert(p.url().includes('action=activity'));assert.equal(await p.locator('[name=audio]').evaluate(e=>e.files.length),1);
assert(await p.locator('[data-record-download]').isVisible());
await p.locator('[data-record]').click();await p.waitForTimeout(2200);await p.locator('[data-stop]').click();
await p.waitForFunction(()=>document.querySelector('input[type=file]').files.length===1);
const recorded=await p.locator('input[type=file]').evaluate(async e=>({name:e.files[0].name,data:Array.from(new Uint8Array(await e.files[0].arrayBuffer()))}));
fs.writeFileSync('/tmp/spoken-browser.webm',Buffer.from(recorded.data));
await p.locator('[name=consent]').check();await p.getByRole('button',{name:'Submit audio',exact:true}).click();
await p.waitForURL(/action=attempt/);const attemptUrl=p.url();const attempt=new URL(attemptUrl).searchParams.get('id');
assert(await p.locator('[name=transcript]').count());
let audio=await c.request.get(base+'?module=spokenassessment&action=audio&id='+attempt,{headers:{Range:'bytes=0-15'}});assert.equal(audio.status(),206);assert.equal((await audio.body()).length,16);
assert.equal(audio.headers()['cache-control'],'private, no-store');
const text='I observed a thick leaf. It may reduce water loss, but I need more evidence. 🌿';
await p.locator('[name=transcript]').fill(text);await p.getByRole('button',{name:'Confirm transcript and request feedback'}).click();
assert((await p.locator('body').innerText()).includes(text));
await p.locator('[name=reflection]').fill('Next time I will describe the evidence before inferring a function.');await p.getByRole('button',{name:'Save reflection'}).click();await p.reload();
assert.equal(await p.locator('[name=reflection]').inputValue(),'Next time I will describe the evidence before inferring a function.');
assert.equal((await c.request.post(base+'?module=spokenassessment&action=reflect&id='+attempt,{form:{contextcode:f.context,reflection:'forged'}})).status(),403);
await p.setViewportSize({width:390,height:844});assert(await p.locator('audio').evaluate(e=>e.getBoundingClientRect().right<=e.closest('section.chisimba-form-card').getBoundingClientRect().right));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:'/tmp/spoken-attempt-mobile.png',fullPage:true});
const other=await login('other');assert.equal((await other.c.request.get(attemptUrl)).status(),404);assert.equal((await other.c.request.get(base+'?module=spokenassessment&action=audio&id='+attempt)).status(),404);
const outsider=await login('outsider');assert([403,404].includes((await outsider.c.request.get(attemptUrl)).status()));
const anon=await b.newContext({ignoreHTTPSErrors:true});const anonAudio=await anon.request.get(base+'?module=spokenassessment&action=audio&id='+attempt);assert(!/^audio\//.test(anonAudio.headers()['content-type']||''));
const teacher=await login('teacher');await teacher.p.goto(attemptUrl);await teacher.p.locator('[name=feedback]').fill('Good distinction between observation and inference. Compare two leaves next.');await teacher.p.getByRole('button',{name:'Save feedback'}).click();
await p.reload();assert((await p.locator('body').innerText()).includes('Compare two leaves next.'));
await teacher.p.goto(base+'?module=spokenassessment&action=edit&id='+f.activity);await teacher.p.locator('[name=title]').fill('Explain an observed adaptation — revised');await teacher.p.getByRole('button',{name:'Save activity',exact:true}).click();
await p.goto(attemptUrl);assert((await p.locator('section.chisimba-form-card > h2').first().innerText())==='Explain an observed adaptation');
await p.goto(activity);assert((await p.locator('section.chisimba-form-card > h2').first().innerText()).includes('revised'));
await p.locator('[name=audio]').setInputFiles('/tmp/spoken-qa.wav');await p.locator('[name=consent]').check();await p.getByRole('button',{name:'Submit audio',exact:true}).click();await p.waitForURL(/action=attempt/);
await p.goto(activity);assert.equal(await p.getByRole('link',{name:'View response'}).count(),2);
await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:'/tmp/spoken-activity-tested.png',fullPage:true});
assert.deepEqual(errors,[]);
fs.writeFileSync('/tmp/spoken-browser-result.json',JSON.stringify({attempt,activity:f.activity,context:f.context}));
console.log('PASS native browser recording, WebM upload, WAV upload, private byte ranges, transcript approval, Unicode, reflection save/reload, CSRF rejection, other-student/outsider/anonymous denial, instructor feedback, immutable activity snapshot, two retained attempts, Help/Escape, mobile containment; spoofed upload rejected without losing local file; audio fits mobile card; no page errors.');
await b.close();
})().catch(e=>{console.error(e.stack);process.exit(1)});
