<?php
/** In-memory boundary tests: no payment or email network access. */
require __DIR__.'/fixtures.php';
$store=new ShopMemoryStore;$payments=new ShopFixturePayments;$user=new ShopFixtureUser;$mail=new ShopFixtureMail;$config=new ShopFixtureConfig;
$s=new ShopFixtureService(['shopstore'=>$store,'paymentservice'=>$payments,'user'=>$user,'communicationservice'=>$mail,'dbsysconfig'=>$config,'altconfig'=>$config,'language'=>new ShopFixtureLanguage]);
$count=0;$assert=function($ok,$message)use(&$count){++$count;if(!$ok)throw new RuntimeException($message);};
$reject=function($f,$reason)use($assert){try{$f();throw new RuntimeException('Expected '.$reason);}catch(DomainException $e){$assert($e->getMessage()===$reason,'Unexpected '.$e->getMessage());}};
$assert(!$s->ready(),'Starts closed');
$s->saveSettings(['revision'=>1,'bands'=>[['from'=>'1','amount'=>'110'],['from'=>'5','amount'=>'50'],['from'=>'10','amount'=>'0']],'max_quantity'=>'20','terms'=>'Fixture sales terms','enabled'=>'1']);
$id=str_repeat('a',32);$book=$s->saveBook(['id'=>$id,'revision'=>0,'title'=>'Fixture Book','price'=>'150','stock'=>'10','status'=>'published']);
$reject(fn()=>$s->saveBook(['id'=>$id,'revision'=>0]),'changed_elsewhere');
$user->admin=false;$reject(fn()=>$s->books(true),'forbidden');$reject(fn()=>$s->orders(),'forbidden');$reject(fn()=>$s->saveSettings([]),'forbidden');$user->admin=true;
$details=['name'=>'Fixture Buyer','email'=>'buyer@example.invalid','phone'=>'0123456789','address_line'=>'1 Fixture Road','suburb'=>'','city'=>'Fixture City','province'=>'Limpopo','postal_code'=>'1234','country'=>'ZA','accept_terms'=>'1'];
$make=function($quantity=1,$key=null)use($s,$id,$details){$cart=[$id=>$quantity];return $s->prepare($cart,$details+['quote_hash'=>$s->quoteHash($s->quote($cart))],$key??bin2hex(random_bytes(32)));};
$reject(fn()=>$s->prepare([$id=>1],$details+['quote_hash'=>'forged'],str_repeat('f',64)),'price_changed');
$foreign=$details;$foreign['country']='US';$reject(fn()=>$s->prepare([$id=>1],$foreign,str_repeat('f',64)),'country_unavailable');
$key=bin2hex(random_bytes(32));$o=$make(5,$key);$assert($make(5,$key)['id']===$o['id'],'Duplicate review creates one order');
$assert(json_decode($o['snapshot'],true)['shipping_minor']===5000,'Order snapshots delivery discount');
$reject(fn()=>$make(6),'out_of_stock');
$token=$s->token($o['id']);$reject(fn()=>$s->order($token.'bad'),'forbidden');
$s->checkout($token);$s->checkout($token);$assert($payments->calls===1,'Duplicate checkout reuses approval URL');
$o=$s->order($token);$intent=$payments->rows[$o['intent_id']];
$assert($s->matchesIntent($intent),'Canonical intent accepted');$bad=$intent;$bad['amount_minor']++;$assert(!$s->matchesIntent($bad),'Tampered total rejected');
$assert(!$s->fulfil($intent)['ok'],'Browser/unverified payment cannot fulfil');
$intent['state']='succeeded';$payments->rows[$intent['id']]=$intent;$s->fulfil($intent);$s->fulfil($intent);
$assert($store->one('books',$id)['stock']===5,'Duplicate payment decrements stock once');$assert(count($mail->rows)===1,'Confirmation queued once');
$paid=$s->order($token);$s->dispatchOrder(['id'=>$paid['id'],'revision'=>$paid['revision'],'courier'=>'Fixture Courier','tracking'=>'SYNTHETIC-001']);
$assert(count($mail->rows)===2,'Dispatch notice queued');$s->retryNotice($paid['id']);$assert(count($mail->rows)===2,'Retries do not duplicate mail');
$intent['state']='refunded';$s->reverse($intent);$s->reverse($intent);$assert($store->one('books',$id)['stock']===5,'Refund does not invent returned stock');$assert($s->order($token)['fulfilment_state']==='dispatched','Financial reversal preserves dispatch history');
$late=$make(5);$lateToken=$s->token($late['id']);$s->checkout($lateToken);$late=$s->order($lateToken);$store->save('orders',$late['id'],['hold_until'=>time()-1]);
$other=$make(5);$s->checkout($s->token($other['id']));$other=$store->one('orders',$other['id']);$i=$payments->rows[$other['intent_id']];$i['state']='succeeded';$payments->rows[$i['id']]=$i;$s->fulfil($i);
$i=$payments->rows[$late['intent_id']];$i['state']='succeeded';$payments->rows[$i['id']]=$i;$s->fulfil($i);$assert($s->order($lateToken)['fulfilment_state']==='review','Late payment without stock enters review');$assert($store->one('books',$id)['stock']===0,'Late payment cannot oversell');
$reject(fn()=>$s->dispatchOrder(['id'=>$late['id'],'revision'=>$s->order($lateToken)['revision'],'courier'=>'x','tracking'=>'y']),'cannot_dispatch');
$store->save('books',$id,['stock'=>5]);$uncertain=$make(1);$payments->uncertain=true;$ut=$s->token($uncertain['id']);$reject(fn()=>$s->checkout($ut),'checkout_uncertain');$calls=$payments->calls;$reject(fn()=>$s->checkout($ut),'checkout_uncertain');$assert($calls===$payments->calls,'Uncertain payment not resubmitted');
$store->save('books',$id,['stock'=>10]);
$reviewed=$s->order($lateToken);$allocated=$s->updateFulfilment(['id'=>$late['id'],'revision'=>$reviewed['revision'],'operation'=>'allocate']);
$assert($allocated['fulfilment_state']==='packing'&&$store->one('books',$id)['stock']===5,'Manager can allocate late paid order after stock arrives');
$reject(fn()=>$s->updateFulfilment(['id'=>$late['id'],'revision'=>$allocated['revision'],'operation'=>'allocate']),'invalid_operation');
$lateIntent=$payments->rows[$late['intent_id']];$lateIntent['state']='refunded';$s->reverse($lateIntent);$refunded=$s->order($lateToken);
$restocked=$s->updateFulfilment(['id'=>$late['id'],'revision'=>$refunded['revision'],'operation'=>'restock']);
$assert($store->one('books',$id)['stock']===10&&$restocked['stock_applied']===2,'Explicit unsent refund restocks once');
$reject(fn()=>$s->updateFulfilment(['id'=>$late['id'],'revision'=>$restocked['revision'],'operation'=>'restock']),'invalid_operation');
$cancel=$make(1);$cancelled=$s->updateFulfilment(['id'=>$cancel['id'],'revision'=>$cancel['revision'],'operation'=>'cancel']);
$reject(fn()=>$s->checkout($s->token($cancel['id'])),'order_expired');
$payments->uncertain=false;$mailOrder=$make(1);$mt=$s->token($mailOrder['id']);$s->checkout($mt);$mailOrder=$s->order($mt);$mi=$payments->rows[$mailOrder['intent_id']];$mi['state']='succeeded';$payments->rows[$mi['id']]=$mi;$stockBefore=$store->one('books',$id)['stock'];$mail->fail=true;
try{$s->fulfil($mi);throw new LogicException('Expected queue failure');}catch(RuntimeException $e){$assert($e->getMessage()==='Shop notice could not be queued','Expected mail queue failure');}
$assert($store->one('books',$id)['stock']===$stockBefore-1,'Email failure does not roll back confirmed stock');
$mail->fail=false;$s->fulfil($mi);$assert($store->one('books',$id)['stock']===$stockBefore-1,'Email retry cannot double deduct stock');
echo "PASS: $count shop permissions, stock, snapshots, idempotency and fulfilment checks\n";
