<?php
$e=static function($value){return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');};
$t=function($key){return $this->language->languageText('mod_certificate_service_'.$key,'certificate-service');};
$url=function($params)use($e){return $e(html_entity_decode($this->uri($params,'certificate-service'),ENT_QUOTES,'UTF-8'));};
$searched=$certificateAuditNumber!==''||$certificateAuditIdentity!=='';
$certificateAuditMessage=$certificateAuditMessage!==''?$certificateAuditMessage:(string)$this->getParam('message','');
$certificateAuditError=$certificateAuditError!==''?$certificateAuditError:(string)$this->getParam('error','');
$icons=$this->getObject('iconservice','ui');
?>
<main class="chisimba-workspace certificate-audit" aria-labelledby="certificate-audit-title">
<header><h1 id="certificate-audit-title"><?php echo $e($t('audit_title')); ?></h1><p><?php echo $e($t('audit_intro')); ?></p></header>
<?php if($certificateAuditMessage!==''): ?><p class="chisimba-notice chisimba-notice--success" role="status"><?php echo $e($t('audit_'.$certificateAuditMessage)); ?></p><?php endif; ?>
<?php if($certificateAuditError!==''): ?><p class="chisimba-notice chisimba-notice--error" role="alert"><?php echo $e($t('audit_'.$certificateAuditError)); ?></p><?php endif; ?>
<section class="chisimba-form-card"><form class="chisimba-form" method="get" action="<?php echo $url(array()); ?>"><input type="hidden" name="module" value="certificate-service"><input type="hidden" name="action" value="audit"><div class="chisimba-form-grid"><label class="chisimba-form-field"><?php echo $e($t('audit_certificate_number')); ?><input name="certificate_number" value="<?php echo $e($certificateAuditNumber); ?>"></label><label class="chisimba-form-field"><?php echo $e($t('audit_identity_number')); ?><input name="identity_document_number" value="<?php echo $e($certificateAuditIdentity); ?>"></label></div><div class="chisimba-form-actions"><button class="button" type="submit"><?php echo $icons->render('search',array('size'=>18,'decorative'=>true)); ?> <?php echo $e($t('audit_search')); ?></button></div></form></section>
<?php if($searched): ?><section class="certificate-audit-results"><?php if(!$certificateAuditResults): ?><p class="chisimba-notice"><?php echo $e($t('audit_no_results')); ?></p><?php else: ?><?php foreach($certificateAuditResults as $row): $snapshot=is_array($row['snapshot']??null)?$row['snapshot']:array(); ?><article class="chisimba-form-card certificate-audit-record"><div class="certificate-audit-record__heading"><h2><?php echo $e($row['certificate_number']); ?></h2><a class="button chisimba-button-secondary" target="_blank" rel="noopener" href="<?php echo $url(array('action'=>'downloadaudit','id'=>$row['id'])); ?>"><?php echo $icons->render('file-down',array('size'=>18,'decorative'=>true)); ?> <?php echo $e($t('audit_view_certificate')); ?></a></div><dl><div><dt><?php echo $e($t('audit_recipient')); ?></dt><dd><?php echo $e($snapshot['recipient_name']??''); ?></dd></div><div><dt><?php echo $e($t('audit_context')); ?></dt><dd><?php echo $e($snapshot['resource_title']??''); ?></dd></div><div><dt><?php echo $e($t('audit_identity')); ?></dt><dd><?php echo $e(($snapshot['identity_document_type_label']??'').' '.($snapshot['identity_document_number']??'')); ?></dd></div><div><dt><?php echo $e($t('audit_issued')); ?></dt><dd><?php echo $e($row['issued_at']); ?></dd></div></dl></article><?php endforeach; ?><?php endif; ?></section><?php endif; ?>
<?php if($certificateAuditIsAdmin): ?><details class="chisimba-form-card"><summary><?php echo $e($t('audit_add_identity')); ?></summary><p><?php echo $e($t('audit_add_identity_help')); ?></p><form class="chisimba-form" method="post" action="<?php echo $url(array('action'=>'saveauditidentity')); ?>"><input type="hidden" name="csrf_token" value="<?php echo $e($certificateAuditCsrf); ?>"><label class="chisimba-form-field"><?php echo $e($t('audit_account')); ?><input name="account" required></label><div class="chisimba-form-grid"><label class="chisimba-form-field"><?php echo $e($this->language->languageText('mod_registration_service_identity_document_type','registration-service')); ?><select name="identity_document_type" required><option value=""></option><?php foreach(array('south_african_id','passport','national_identity_document') as $type): ?><option value="<?php echo $e($type); ?>"><?php echo $e($this->language->languageText('mod_registration_service_identity_type_'.$type,'registration-service')); ?></option><?php endforeach; ?></select></label><label class="chisimba-form-field"><?php echo $e($this->language->languageText('mod_registration_service_identity_document_number','registration-service')); ?><input name="identity_document_number" required></label></div><div class="chisimba-form-actions"><button class="button" type="submit"><?php echo $e($t('audit_save_identity')); ?></button></div></form></details><?php endif; ?>
</main>
<style>.certificate-audit{max-width:76rem;margin:0 auto}.certificate-audit-results{display:grid;gap:1rem;margin-top:1rem}.certificate-audit-record h2{margin:0}.certificate-audit-record__heading{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1rem}.certificate-audit-record dl{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;margin:0}.certificate-audit-record dl div{display:grid;gap:.25rem}.certificate-audit-record dt{font-weight:700}.certificate-audit-record dd{margin:0}@media(max-width:55rem){.certificate-audit-record dl{grid-template-columns:1fr 1fr}}@media(max-width:34rem){.certificate-audit-record dl{grid-template-columns:1fr}.certificate-audit-record__heading{align-items:stretch;flex-direction:column}}</style>
