<?php
/**
 * Scoped map library and Kenga migration journey.
 *
 * @author Derek Keats
 * @package knowledgemap
 */
$e=fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$url=fn($params=array())=>html_entity_decode($this->uri($params,'knowledgemap'),ENT_QUOTES,'UTF-8');
$scopeType=$knowledgeMapScope['type'];$icons=$this->getObject('iconservice','ui');
$hidden='<input type="hidden" name="csrf_token" value="'.$e($knowledgeMapCsrf).'"/><input type="hidden" name="scope" value="'.$e($scopeType).'"/>';
?>
<main class="chisimba-workspace chisimba-flow chisimba-structural-main chisimba-structural-main--full knowmap-library">
    <header class="chisimba-page-header chisimba-card">
        <div><p class="chisimba-eyebrow"><?php echo $e($knowledgeMapScope['label']); ?></p><h1>Active Knowledge Maps</h1><p>Shape knowledge visually, share it, and activate work from any node.</p></div>
        <form class="chisimba-form-field knowmap-scope" method="get" action="index.php"><input type="hidden" name="module" value="knowledgemap"/><label for="knowmap-scope">Map scope</label><div class="chisimba-cluster"><select id="knowmap-scope" name="scope"><option value="personal" <?php echo $scopeType==='personal'?'selected':''; ?>>Personal — my maps and invitations</option><?php $context=(string)$this->getObject('dbcontext','context')->getContextCode();if($context!==''&&$context!=='root'): ?><option value="context" <?php echo $scopeType==='context'?'selected':''; ?>>Course — maps in this course</option><?php endif;if($this->getObject('user','security')->isAdmin()): ?><option value="site" <?php echo $scopeType==='site'?'selected':''; ?>>Site — organisation maps</option><?php endif; ?></select><button class="button" type="submit"><?php echo $icons->render('eye',array('decorative'=>true)); ?> View maps</button></div></form>
    </header>
    <?php if($knowledgeMapMessage!==''): ?><div class="chisimba-notice chisimba-notice--success" role="status"><?php echo $e($knowledgeMapMessage); ?></div><?php endif; ?>
    <?php if($knowledgeMapError!==''): ?><div class="chisimba-notice chisimba-notice--error" role="alert"><?php echo $e($knowledgeMapError); ?></div><?php endif; ?>
    <?php if($knowledgeMapCanCreate): ?><section class="knowmap-onboarding">
        <details class="chisimba-card" open><summary><strong>Create a knowledge map</strong></summary><form class="chisimba-form" method="post" action="<?php echo $e($url(array('action'=>'create'))); ?>"><?php echo $hidden; ?><div class="chisimba-form-field"><label for="knowmap-title">Map title</label><input id="knowmap-title" name="title" maxlength="255" required/></div><div class="chisimba-form-field"><label for="knowmap-description">Purpose or description</label><textarea id="knowmap-description" name="description"></textarea></div><button class="button" type="submit"><?php echo $icons->render('circle-plus',array('decorative'=>true)); ?> Create map</button></form></details>
        <details class="chisimba-card"><summary><strong>Bring over a Kenga map</strong></summary><p>Choose the JSON file produced by Kenga Knowledge Maps 2.2.x. Validation happens before anything is created.</p><form class="chisimba-form" method="post" enctype="multipart/form-data" action="<?php echo $e($url(array('action'=>'import'))); ?>"><?php echo $hidden; ?><div class="chisimba-form-field"><label for="knowmap-import">Kenga JSON export</label><input id="knowmap-import" type="file" name="mapfile" accept="application/json,.json" required/></div><button class="button chisimba-button-secondary" type="submit"><?php echo $icons->render('upload',array('decorative'=>true)); ?> Validate import</button></form></details>
    </section><?php endif; ?>
    <?php if(isset($knowledgeMapImportPreview)): ?><section class="chisimba-card knowmap-import-preview"><p class="chisimba-eyebrow">Import preview</p><h2><?php echo $e($knowledgeMapImportPreview['document']['metadata']['title']??'Imported knowledge map'); ?></h2><div class="chisimba-cluster"><span class="chisimba-pill"><?php echo $e($knowledgeMapImportPreview['counts']['nodes']); ?> nodes</span><span class="chisimba-pill"><?php echo $e($knowledgeMapImportPreview['counts']['relationships']); ?> relationships</span></div><?php foreach($knowledgeMapImportPreview['warnings'] as $warning): ?><p class="chisimba-notice"><?php echo $e($warning); ?></p><?php endforeach; ?><form method="post" action="<?php echo $e($url(array('action'=>'import'))); ?>"><?php echo $hidden; ?><input type="hidden" name="confirm_import" value="1"/><input type="hidden" name="import_payload" value="<?php echo $e($knowledgeMapImportPayload); ?>"/><button class="button" type="submit" <?php echo $knowledgeMapImportPreview['duplicate']?'disabled':''; ?>>Create imported map</button></form></section><?php endif; ?>
    <section><div class="chisimba-page-header"><div><p class="chisimba-eyebrow">Map library</p><h2>Available maps</h2></div></div><div class="knowmap-grid">
    <?php foreach($knowledgeMaps as $map): ?><article class="chisimba-card knowmap-card"><p class="chisimba-eyebrow"><?php echo $e(ucfirst($map['scopetype']).' · '.ucfirst($map['permission'])); ?></p><h3><?php echo $e($map['title']); ?></h3><?php if($map['description']!==''): ?><p><?php echo nl2br($e($map['description'])); ?></p><?php endif; ?><p class="knowmap-card__meta">Updated <?php echo $e(date('j M Y',strtotime($map['datemodified']))); ?></p><a class="button chisimba-button-secondary chisimba-button-compact" href="<?php echo $e($url(array('action'=>'view','mapid'=>$map['id']))); ?>"><?php echo $icons->render('arrow-right',array('decorative'=>true)); ?><span>Open map</span></a></article><?php endforeach; ?>
    <?php if(!$knowledgeMaps): ?><div class="chisimba-card"><h3>No maps here yet</h3><p>Create a map or accept an invitation to begin.</p></div><?php endif; ?></div></section>
</main>
