<?php
/**
 * Read-only projection and management shell for one Active Knowledge Map.
 *
 * @author Derek Keats
 * @package knowledgemap
 */
$e=fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$url=fn($params=array())=>html_entity_decode($this->uri($params,'knowledgemap'),ENT_QUOTES,'UTF-8');
$json=$e(json_encode($knowledgeMapDocument,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE));
$icons=$this->getObject('iconservice','ui');
$exitUrl=$knowledgeMapRecord['scopetype']==='context'?$this->uri(array(),'context'):'index.php';
?>
<main class="chisimba-structural-main chisimba-structural-main--full knowmap-view" data-knowmap-document="<?php echo $json; ?>" data-knowmap-editable="<?php echo $knowledgeMapCanEdit?'1':'0'; ?>" data-knowmap-save-url="<?php echo $e($url(array('action'=>'save'))); ?>" data-knowmap-csrf="<?php echo $e($knowledgeMapCsrf); ?>">
    <header class="chisimba-toolbar knowmap-view__toolbar">
        <a class="button chisimba-button-secondary chisimba-button-compact" href="<?php echo $e($url(array('scope'=>$knowledgeMapRecord['scopetype']))); ?>"><?php echo $icons->render('layout-dashboard',array('decorative'=>true)); ?><span>All maps</span></a>
        <div class="knowmap-view__identity"><p class="chisimba-eyebrow"><?php echo $e(ucfirst($knowledgeMapRecord['scopetype'])); ?> map</p><h1><?php echo $e($knowledgeMapRecord['title']); ?></h1></div>
        <?php if($knowledgeMapCanEdit): ?><div class="chisimba-toolbar__group"><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-action="add-child" aria-label="Add child" title="Add child"><?php echo $icons->render('circle-plus',array('decorative'=>true)); ?></button><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-action="add-sibling" aria-label="Add sibling" title="Add sibling"><?php echo $icons->render('copy-plus',array('decorative'=>true)); ?></button><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-action="collapse" aria-label="Collapse or expand branch" title="Collapse or expand branch"><?php echo $icons->render('fold-vertical',array('decorative'=>true)); ?></button><button class="chisimba-icon-button chisimba-icon-button--small knowmap-delete-control" type="button" data-knowmap-action="delete" aria-label="Delete selected node" title="Delete selected node"><?php echo $icons->render('trash-2',array('decorative'=>true)); ?></button></div><?php endif; ?>
        <?php if($knowledgeMapCanEdit): ?><div class="knowmap-style-menu"><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-action="style" aria-label="Node typography" title="Node typography" aria-expanded="false"><?php echo $icons->render('type',array('decorative'=>true)); ?></button><div class="chisimba-popover knowmap-style-popover" data-knowmap-style-popover hidden><div class="chisimba-form-field"><label for="knowmap-font-family">Font</label><select id="knowmap-font-family" data-knowmap-style="fontFamily"><option value="Inter">Inter</option><option value="Arial">Arial</option><option value="Georgia">Georgia</option><option value="Verdana">Verdana</option><option value="monospace">Monospace</option></select></div><div class="chisimba-form-field"><label for="knowmap-font-size">Size</label><select id="knowmap-font-size" data-knowmap-style="fontSize"><option value="12">12</option><option value="14">14</option><option value="16">16</option><option value="18">18</option><option value="22">22</option><option value="28">28</option></select></div><div class="chisimba-form-field knowmap-font-colour"><label for="knowmap-font-colour"><?php echo $icons->render('palette',array('decorative'=>true)); ?><span>Font colour</span></label><input id="knowmap-font-colour" type="color" data-knowmap-style="fontColor" value="#172033"/></div></div></div><?php endif; ?>
        <label class="knowmap-search"><?php echo $icons->render('search',array('decorative'=>true)); ?><span class="visually-hidden">Search nodes</span><input type="search" data-knowmap-search placeholder="Search nodes"/></label>
        <div class="chisimba-toolbar__group"><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-zoom="out" aria-label="Zoom out" title="Zoom out"><?php echo $icons->render('zoom-out',array('decorative'=>true)); ?></button><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-zoom="fit" aria-label="Fit map" title="Fit map"><?php echo $icons->render('maximize-2',array('decorative'=>true)); ?></button><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-zoom="in" aria-label="Zoom in" title="Zoom in"><?php echo $icons->render('zoom-in',array('decorative'=>true)); ?></button></div>
        <div class="chisimba-toolbar__group knowmap-view__persistent"><a class="chisimba-icon-button chisimba-icon-button--small" href="<?php echo $e($exitUrl); ?>" aria-label="Exit to Chisimba" title="Exit to Chisimba"><?php echo $icons->render('log-out',array('decorative'=>true)); ?></a><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-action="chrome" aria-label="Hide top controls" title="Hide top controls" aria-expanded="true"><?php echo $icons->render('panel-top-close',array('decorative'=>true)); ?></button><button class="chisimba-icon-button chisimba-icon-button--small" type="button" data-knowmap-action="panel" aria-label="Hide details panel" title="Hide details panel" aria-expanded="true"><?php echo $icons->render('panel-right-close',array('decorative'=>true)); ?></button><?php if($knowledgeMapCanEdit): ?><span class="knowmap-save-status" data-knowmap-save-status>Saved</span><button class="chisimba-icon-button chisimba-icon-button--small knowmap-save-control" type="button" data-knowmap-action="save" aria-label="Save map" title="Save map"><?php echo $icons->render('save',array('decorative'=>true)); ?></button><?php endif; ?></div>
    </header>
    <?php if($knowledgeMapMessage!==''): ?><div class="chisimba-notice chisimba-notice--success" role="status"><?php echo $e($knowledgeMapMessage); ?></div><?php endif; ?>
    <div class="knowmap-view__body"><section class="knowmap-canvas chisimba-spatial-workspace" tabindex="0" aria-label="<?php echo $e($knowledgeMapRecord['title']); ?> knowledge map"><svg class="knowmap-lines" aria-hidden="true"></svg><div class="knowmap-nodes"></div></section><aside class="chisimba-card knowmap-inspector"><p class="chisimba-eyebrow">Selected node</p><h2 data-knowmap-selection-title>Select a node</h2><p data-knowmap-selection-description>Choose a node to inspect its knowledge and available actions.</p><?php if($knowledgeMapCanEdit): ?><form class="chisimba-form knowmap-node-form" data-knowmap-node-form hidden><div class="chisimba-form-field"><label for="knowmap-node-title">Title</label><input id="knowmap-node-title" name="title" maxlength="255" required/></div><div class="chisimba-form-field"><label for="knowmap-node-description">Description</label><textarea id="knowmap-node-description" name="description"></textarea></div><div class="chisimba-form-field"><label for="knowmap-node-link">Link</label><input id="knowmap-node-link" name="link" type="url" placeholder="https://example.org"/></div><div class="chisimba-form-field"><label for="knowmap-node-colour">Branch colour</label><input id="knowmap-node-colour" name="color" type="color" value="#f3f8ef"/></div><button class="button chisimba-button-secondary" type="submit">Apply node changes</button></form><?php endif; ?><div class="chisimba-stack knowmap-active-actions"><button class="button chisimba-button-secondary" type="button" disabled>Push from here</button><button class="button chisimba-button-secondary" type="button" disabled>Pull into here</button><small>No compatible providers are installed yet.</small></div><?php if($knowledgeMapCanManage): ?><details><summary>Sharing and permissions</summary><p>Invite any Chisimba user with <code>view</code>, <code>edit</code>, or <code>manage</code> access, one username per line.</p><form class="chisimba-form" method="post" action="<?php echo $e($url(array('action'=>'share','mapid'=>$knowledgeMapRecord['id']))); ?>"><input type="hidden" name="csrf_token" value="<?php echo $e($knowledgeMapCsrf); ?>"/><input type="hidden" name="mapid" value="<?php echo $e($knowledgeMapRecord['id']); ?>"/><div class="chisimba-form-field"><label for="knowmap-grants">Invited users</label><textarea id="knowmap-grants" name="grants" placeholder="jane:edit&#10;john:view"><?php foreach($knowledgeMapGrants as $grant)if($grant['principaltype']==='user'){$details=$this->getObject('user','security')->getUserDetails($grant['principalid']);echo $e(($details['username']??$grant['principalid']).':'.$grant['permission'])."\n";} ?></textarea></div><button class="button" type="submit">Save sharing</button></form></details><?php endif; ?><details><summary>Embed this map</summary><p><code>[knowmap id=<?php echo $e($knowledgeMapRecord['id']); ?>]</code></p><p>The embedded version is read-only and applies the same viewing permissions.</p></details></aside></div>
</main>
