<?php
/** Read-only content export. No account credentials, audience or plugin settings. @author Derek Keats */
if(PHP_SAPI!=='cli')exit(1);define('SHORTINIT',true);require '/var/www/learnthebirds.com/wp-load.php';global $wpdb;
$out=['version'=>1,'source'=>'https://learnthebirds.com','posts'=>[],'terms'=>[],'attachments'=>[],'media_urls'=>[],'issues'=>[]];
function meta($id,$key){global $wpdb;return (string)$wpdb->get_var($wpdb->prepare("SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id=%d AND meta_key=%s ORDER BY meta_id DESC LIMIT 1",$id,$key));}
function media($relative,$url=''){
 global $out;$relative=rawurldecode($relative);$root=realpath('/var/www/learnthebirds.com/wp-content/uploads');$path=realpath($root.'/'.$relative);
 if(!$path||!str_starts_with($path,$root.'/')||!is_file($path)){$out['issues'][]='Missing media '.$relative;return null;}
 $id=hash('sha256',$relative);$out['attachments'][$id]=['relative_path'=>$relative,'sha256'=>hash_file('sha256',$path),'bytes'=>filesize($path)];if($url)$out['media_urls'][$url]=$id;return $id;
}
function inlineMedia($html){global $out;preg_match_all('~https?://(?:www\.)?learnthebirds\.com/wp-content/uploads/[^\s<>"\'\)]+~i',html_entity_decode($html,ENT_QUOTES,'UTF-8'),$m);foreach(array_unique($m[0]) as $url){$url=rtrim($url,',;');$path=parse_url($url,PHP_URL_PATH);$relative=substr($path,strlen('/wp-content/uploads/'));if(preg_match('~\.(?:jpe?g|png|webp|gif|svg|pdf|mp[34]|m4v|ogg|wav)$~i',$relative))media($relative,$url);}}
function imageDetails($image){global $wpdb;if(!is_array($image))return $image;$id=(int)($image['id']??0);if($id){$image['caption']=$wpdb->get_var($wpdb->prepare("SELECT post_excerpt FROM {$wpdb->posts} WHERE ID=%d AND post_type='attachment'",$id))??'';if(empty($image['alt']))$image['alt']=meta($id,'_wp_attachment_image_alt');}return $image;}
function enrich($settings){if(isset($settings['image']))$settings['image']=imageDetails($settings['image']);foreach(['wp_gallery','carousel','image_carousel'] as $key)if(isset($settings[$key])&&is_array($settings[$key]))$settings[$key]=array_map('imageDetails',$settings[$key]);return $settings;}
function widgets($nodes){$out=[];foreach((array)$nodes as $n){if(!is_array($n))continue;if(isset($n['widgetType']))$out[]=['type'=>$n['widgetType'],'setting_keys'=>array_keys($n['settings']??[]),'settings'=>array_intersect_key(enrich($n['settings']??[]),array_flip(['editor','title','title_text','image','caption','text','description','youtube_url','vimeo_url','hosted_url','video_type','link','url','html','shortcode','wp_gallery','tabs','slides','image_carousel','blockquote_content','blockquote_author','skin','youtube_link','vimeo_link','video_url','video','source','video_source','video_link','caption_source','custom_caption','carousel','author_name']))];$out=array_merge($out,widgets($n['elements']??[]));}return $out;}
$pattern=$wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='permalink_structure'");$out['permalink_structure']=$pattern;$out['timezone']=$wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='timezone_string'");$out['gmt_offset']=$wpdb->get_var("SELECT option_value FROM {$wpdb->options} WHERE option_name='gmt_offset'");
foreach($wpdb->get_results("SELECT ID,post_title,post_content,post_excerpt,post_name,post_status,post_date,post_date_gmt,post_modified_gmt,post_author,(post_password<>'') AS protected FROM {$wpdb->posts} WHERE post_type='post' AND post_status IN ('publish','draft') ORDER BY ID",ARRAY_A) as $p){
 $p['author_name']=$wpdb->get_var($wpdb->prepare("SELECT display_name FROM {$wpdb->users} WHERE ID=%d",$p['post_author']));$p['featured']=null;$fid=(int)meta($p['ID'],'_thumbnail_id');if($fid){$relative=meta($fid,'_wp_attached_file');$p['featured']=media($relative);$p['featured_alt']=meta($fid,'_wp_attachment_image_alt');}
 $p['widgets']=widgets(json_decode(meta($p['ID'],'_elementor_data'),true));$p['terms']=[];
 foreach($wpdb->get_results($wpdb->prepare("SELECT t.term_id,t.name,t.slug,tt.taxonomy,tt.parent FROM {$wpdb->term_relationships} r JOIN {$wpdb->term_taxonomy} tt ON tt.term_taxonomy_id=r.term_taxonomy_id JOIN {$wpdb->terms} t ON t.term_id=tt.term_id WHERE r.object_id=%d AND tt.taxonomy IN ('category','post_tag')",$p['ID']),ARRAY_A) as $t){$p['terms'][]=$t['term_id'];$out['terms'][$t['term_id']]=$t;}
 inlineMedia($p['post_content']);inlineMedia(json_encode($p['widgets'],JSON_UNESCAPED_SLASHES));$out['posts'][]=$p;
}
// Include category ancestors even if only child categories were assigned.
foreach($out['terms'] as $term){$parent=$term['parent'];$seen=[];while($parent&&!isset($out['terms'][$parent])){if(isset($seen[$parent]))throw new RuntimeException('Category cycle');$seen[$parent]=1;$t=$wpdb->get_row($wpdb->prepare("SELECT t.term_id,t.name,t.slug,tt.taxonomy,tt.parent FROM {$wpdb->terms} t JOIN {$wpdb->term_taxonomy} tt ON tt.term_id=t.term_id WHERE t.term_id=%d AND tt.taxonomy='category'",$parent),ARRAY_A);if(!$t)throw new RuntimeException('Missing category parent');$out['terms'][$parent]=$t;$parent=$t['parent'];}}
echo json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);
