<?php
/** API-independent notification domain service. @author Derek Keats @package notifications */
if(empty($GLOBALS['kewl_entry_point_run']))die('You cannot view this page directly');
class notificationservice extends ChisimbaObject
{
 private $events;private $recipients;
 /** Load owned persistence gateways. */
 public function init(){$this->events=$this->getObject('dbnotificationevents');$this->recipients=$this->getObject('dbnotificationrecipients');}
 /** Publish one idempotent event to unique recipients. */
 public function publish(array $input){$valid=$this->normalise($input);if(!$valid['ok'])return $valid;$event=$valid['event'];$existing=$this->events->byKey($event['idempotency_key']);if($existing)return array('ok'=>true,'code'=>'already_published','eventId'=>$existing['id']);$now=date('Y-m-d H:i:s');$event['id']=bin2hex(random_bytes(16));$event['datecreated']=$now;if($this->events->createEvent($event)===false)return array('ok'=>false,'code'=>'event_store_failed');foreach($valid['recipients'] as $userId){$this->recipients->addRecipient(array('id'=>bin2hex(random_bytes(16)),'event_id'=>$event['id'],'user_id'=>$userId,'state'=>'unread','read_at'=>null,'archived_at'=>null,'datecreated'=>$now,'datemodified'=>$now));}return array('ok'=>true,'code'=>'published','eventId'=>$event['id'],'recipientCount'=>count($valid['recipients']));}
 /** Return an API-ready feed page for one authenticated user. */
 public function feed($userId,$limit=25,$cursorToken='',$unreadOnly=false){$cursor=$this->decodeCursor($cursorToken);if($cursorToken!==''&&!$cursor)return array('ok'=>false,'code'=>'invalid_cursor');$rows=$this->recipients->feed($userId,$limit,$cursor,$unreadOnly);$hasMore=count($rows)>$limit;if($hasMore)array_pop($rows);$items=array();foreach($rows as $row){$payload=json_decode((string)$row['payload_json'],true);$items[]=array('id'=>$row['notification_id'],'eventId'=>$row['event_id'],'type'=>$row['event_type'],'state'=>$row['state'],'actorUserId'=>$row['actor_user_id']?:null,'contextCode'=>$row['context_code']?:null,'source'=>array('type'=>$row['source_type'],'id'=>$row['source_id']),'title'=>$row['title'],'summary'=>$row['summary'],'targetUrl'=>$row['target_url']?:null,'payload'=>is_array($payload)?$payload:array(),'createdAt'=>$row['datecreated'],'readAt'=>$row['read_at']?:null);}$next=null;if($hasMore&&$rows){$last=end($rows);$next=$this->encodeCursor($last['datecreated'],$last['notification_id']);}return array('ok'=>true,'items'=>$items,'page'=>array('nextCursor'=>$next,'hasMore'=>$hasMore));}
 /** Return unread count for one user. */
 public function unreadCount($userId){return $this->recipients->unreadCount($userId);}
 /** Mark one notification read for its owner. */
 public function markRead($notificationId,$userId){if(!preg_match('/^[a-f0-9]{32}$/',(string)$notificationId))return false;$this->recipients->markRead($notificationId,$userId,date('Y-m-d H:i:s'));return true;}
 private function normalise(array $input){$key=trim((string)($input['idempotencyKey']??''));$type=trim((string)($input['type']??''));$sourceType=trim((string)($input['sourceType']??''));$sourceId=trim((string)($input['sourceId']??''));$title=trim((string)($input['title']??''));$summary=trim((string)($input['summary']??''));$users=array_values(array_unique(array_filter(array_map('strval',(array)($input['recipientUserIds']??array())))));if($key===''||strlen($key)>191||!preg_match('/^[a-z][a-z0-9_.-]{2,127}$/',$type)||$sourceType===''||$sourceId===''||$title===''||$summary===''||!$users)return array('ok'=>false,'code'=>'invalid_notification');$payload=json_encode((array)($input['payload']??array()),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if($payload===false)return array('ok'=>false,'code'=>'invalid_payload');return array('ok'=>true,'event'=>array('idempotency_key'=>$key,'event_type'=>$type,'actor_user_id'=>($input['actorUserId']??null)?:null,'context_code'=>($input['contextCode']??null)?:null,'source_type'=>mb_substr($sourceType,0,64),'source_id'=>mb_substr($sourceId,0,191),'title'=>mb_substr($title,0,255),'summary'=>mb_substr($summary,0,10000),'target_url'=>($input['targetUrl']??null)?:null,'payload_json'=>$payload),'recipients'=>$users);}
 private function encodeCursor($date,$id){return rtrim(strtr(base64_encode(json_encode(array('date'=>$date,'id'=>$id))),'+/','-_'),'=');}
 private function decodeCursor($token){if($token==='')return null;$raw=base64_decode(strtr($token,'-_','+/'),true);$value=$raw===false?null:json_decode($raw,true);return is_array($value)&&preg_match('/^\d{4}-\d{2}-\d{2} /',(string)($value['date']??''))&&preg_match('/^[a-f0-9]{32}$/',(string)($value['id']??''))?$value:null;}
}
?>
