<?php
if (!$GLOBALS['kewl_entry_point_run']) { die('You cannot view this page directly'); }
$this->setLayoutTemplate('gradebook_layout_tpl.php');
$this->loadClass('htmlheading', 'htmlelements');
$this->loadClass('htmltable', 'htmlelements');
$rows = isset($assessmentPlanRows) && is_array($assessmentPlanRows) ? $assessmentPlanRows : array();
$message = (string) $this->getParam('planmessage', '');
$error = (string) $this->getParam('planerror', '');
$groups = array('formative' => array(), 'summative' => array(), 'unclassified' => array());
foreach ($rows as $row) { $groups[isset($groups[$row['classification']]) ? $row['classification'] : 'unclassified'][] = $row; }
$iconUri = $this->getResourceUri('icons/lucide/', 'ui');
$groupIcons = array('formative' => 'book-open.svg', 'summative' => 'list-checks.svg', 'unclassified' => 'circle-alert.svg');
$heading = new htmlheading(); $heading->type = 1; $heading->str = $this->objLanguage->languageText('mod_gradebook_assessmentsheet', 'gradebook'); echo $heading->show();
?>
<style>
.assessment-sheet-workspace{max-width:70rem;margin:1.25rem auto 2rem}.assessment-sheet-intro{max-width:52rem;margin:0 0 1.4rem;color:var(--chisimba-text,#444)}.assessment-sheet-notice{margin:0 0 1rem;padding:.75rem 1rem;border:1px solid var(--chisimba-border,#ddd);border-radius:.55rem;background:var(--chisimba-surface-subtle,#f8f9fa)}.assessment-sheet-panel{margin:1rem 0 1.35rem;border:1px solid var(--chisimba-border,#ddd);border-radius:.7rem;background:var(--chisimba-surface,#fff);box-shadow:0 .15rem .6rem rgba(17,17,17,.06);overflow:hidden}.assessment-sheet-panel-head{display:flex;align-items:center;gap:.65rem;padding:.85rem 1rem;border-bottom:1px solid var(--chisimba-border,#ddd);background:var(--chisimba-surface-subtle,#f8f9fa)}.assessment-sheet-panel-head img{width:1.35rem;height:1.35rem}.assessment-sheet-panel-head h2{margin:0;font-size:1.1rem}.assessment-sheet-subtotal{margin-left:auto;font-weight:700;white-space:nowrap}.assessment-sheet-provider{padding:1rem 1rem 0}.assessment-sheet-provider:last-child{padding-bottom:1rem}.assessment-sheet-provider h3{margin:0 0 .45rem;font-size:.95rem;color:var(--chisimba-text-muted,#666)}.assessment-sheet-table{width:100%;border-collapse:collapse}.assessment-sheet-table th{padding:.5rem .7rem;text-align:left;font-size:.8rem;color:var(--chisimba-text-muted,#666);font-weight:700}.assessment-sheet-table th:last-child,.assessment-sheet-table td:last-child{text-align:right}.assessment-sheet-table td{padding:.72rem;border-top:1px solid var(--chisimba-border,#ddd);vertical-align:middle}.assessment-sheet-title{font-weight:650}.assessment-weight-wrap{display:inline-flex;align-items:center;gap:.35rem}.assessment-weight{width:5.75rem;padding:.42rem .5rem;text-align:right;font-variant-numeric:tabular-nums}.assessment-sheet-summary{display:flex;flex-wrap:wrap;gap:.75rem 1.5rem;align-items:center;margin:1.25rem 0;padding:1rem;border-radius:.65rem;background:var(--chisimba-primary-soft,#e7f4fd);border:1px solid #b9def7;font-variant-numeric:tabular-nums}.assessment-sheet-summary strong{color:var(--chisimba-primary-dark,#005b9f)}.assessment-sheet-actions{display:flex;flex-wrap:wrap;gap:.75rem;align-items:center;margin-top:1.25rem}.assessment-sheet-actions button{display:inline-flex;align-items:center;gap:.45rem}.assessment-sheet-actions img{width:1rem;height:1rem;filter:brightness(0) invert(1)}.assessment-sheet-back{margin-top:1.25rem}.assessment-sheet-empty{padding:1rem;border:1px dashed var(--chisimba-border-strong,#ccc);border-radius:.65rem;background:var(--chisimba-surface-subtle,#f8f9fa)}@media(max-width:42rem){.assessment-sheet-provider{padding:.85rem .7rem 0}.assessment-sheet-table th:nth-child(2),.assessment-sheet-table td:nth-child(2){display:none}.assessment-sheet-table td,.assessment-sheet-table th{padding:.65rem .45rem}.assessment-sheet-summary{display:block}.assessment-sheet-summary span{display:block;margin:.35rem 0}}
</style>
<div class="assessment-sheet-workspace">
<p class="assessment-sheet-intro"><?php echo $this->objLanguage->languageText('mod_gradebook_assessmentsheet_description', 'gradebook'); ?></p>
<?php if ($message !== '') { ?><p class="confirm assessment-sheet-notice"><?php echo $this->objLanguage->languageText('mod_gradebook_planmessage_'.$message, 'gradebook'); ?></p><?php } ?>
<?php if ($error !== '') { ?><p class="error assessment-sheet-notice"><?php echo $this->objLanguage->languageText('mod_gradebook_planerror_'.$error, 'gradebook'); ?></p><?php } ?>
<?php if (empty($rows)) { ?><p class="assessment-sheet-empty"><?php echo $this->objLanguage->languageText('mod_gradebook_noassessmentplanitems', 'gradebook'); ?></p><?php } else { ?>
<form method="post" action="<?php echo $this->uri(array('action'=>'assessmentSheetSave')); ?>">
<input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($assessmentPlanCsrf, ENT_QUOTES, 'UTF-8'); ?>">
<?php foreach ($groups as $classification => $groupRows): if (empty($groupRows)) continue; $providers = array(); foreach ($groupRows as $row) { $providers[$row['provider']][] = $row; } ?>
<section class="assessment-sheet-panel assessment-sheet-panel-<?php echo $classification; ?>">
<header class="assessment-sheet-panel-head"><img src="<?php echo $iconUri.$groupIcons[$classification]; ?>" alt="" aria-hidden="true"><h2><?php echo $this->objLanguage->languageText('mod_gradebook_classification_'.$classification, 'gradebook'); ?></h2><span class="assessment-sheet-subtotal"><span class="assessment-sheet-subtotal-value" data-classification="<?php echo $classification; ?>">0</span>%</span></header>
<?php foreach ($providers as $provider => $providerRows): ?>
<div class="assessment-sheet-provider"><h3><?php echo htmlspecialchars($provider, ENT_QUOTES, 'UTF-8'); ?></h3><table class="assessment-sheet-table"><thead><tr><th><?php echo $this->objLanguage->languageText('mod_gradebook_assessment', 'gradebook'); ?></th><th><?php echo $this->objLanguage->languageText('mod_gradebook_provider', 'gradebook'); ?></th><th><?php echo $this->objLanguage->languageText('mod_gradebook_contribution', 'gradebook'); ?></th></tr></thead><tbody>
<?php foreach ($providerRows as $row): $item = $row['item']; ?><tr><td class="assessment-sheet-title"><?php echo htmlspecialchars($row['title'], ENT_QUOTES, 'UTF-8'); ?></td><td><?php echo htmlspecialchars($provider, ENT_QUOTES, 'UTF-8'); ?></td><td><label class="assessment-weight-wrap"><input class="assessment-weight" data-classification="<?php echo $classification; ?>" type="number" min="0" max="100" step="0.001" name="weight[<?php echo htmlspecialchars($item['id'], ENT_QUOTES, 'UTF-8'); ?>]" value="<?php echo htmlspecialchars($item['weight'], ENT_QUOTES, 'UTF-8'); ?>"><span>%</span></label></td></tr><?php endforeach; ?>
</tbody></table></div><?php endforeach; ?>
</section><?php endforeach; ?>
<aside class="assessment-sheet-summary" aria-live="polite"><span><strong><?php echo $this->objLanguage->languageText('mod_gradebook_totalallocated', 'gradebook'); ?></strong>: <span id="assessment-sheet-total">0</span>%</span><span><strong><?php echo $this->objLanguage->languageText('mod_gradebook_remaining', 'gradebook'); ?></strong>: <span id="assessment-sheet-remaining">100</span>%</span></aside>
<p class="assessment-sheet-actions"><button type="submit"><img src="<?php echo $iconUri; ?>list-checks.svg" alt="" aria-hidden="true"><span><?php echo $this->objLanguage->languageText('mod_gradebook_saveassessmentsheet', 'gradebook'); ?></span></button></p>
</form><?php } ?>
<p class="assessment-sheet-back"><a href="<?php echo $this->uri(array('action'=>'assessmentPlan')); ?>"><?php echo $this->objLanguage->languageText('mod_gradebook_backtoassessmentplan', 'gradebook'); ?></a></p>
</div>
<script>(function(){function update(){var total=0,subtotals={},els=document.getElementsByClassName('assessment-weight');for(var i=0;i<els.length;i++){var value=parseFloat(els[i].value)||0,classification=els[i].getAttribute('data-classification');total+=value;subtotals[classification]=(subtotals[classification]||0)+value;}var format=function(value){return value.toFixed(3).replace(/\.?(?:0+)$/,'');};document.getElementById('assessment-sheet-total').textContent=format(total);document.getElementById('assessment-sheet-remaining').textContent=format(100-total);var labels=document.getElementsByClassName('assessment-sheet-subtotal-value');for(var j=0;j<labels.length;j++){labels[j].textContent=format(subtotals[labels[j].getAttribute('data-classification')]||0);}}var fields=document.getElementsByClassName('assessment-weight');for(var i=0;i<fields.length;i++){fields[i].addEventListener('input',update);}if(document.getElementById('assessment-sheet-total')){update();}}());</script>
