<?php
/** Cross-course author overview for My Teaching. @author Derek Keats */
if(empty($GLOBALS['kewl_entry_point_run']))die('You cannot view this page directly');
class teachingcourseoverview extends ChisimbaObject
{
 private $user;private $userContext;private $contexts;private $contextImages;private $insights;private $language;
 public function init(){$this->user=$this->getObject('user','security');$this->userContext=$this->getObject('usercontext','context');$this->contexts=$this->getObject('dbcontext','context');$this->contextImages=$this->getObject('contextimage','context');$this->insights=$this->getObject('teachinginsights','myteaching');$this->language=$this->getObject('language','language');}
 public function courses($userId){$courses=array();foreach(array_values(array_unique((array)$this->userContext->getContextWhereLecturer($userId))) as $code){$details=$this->contexts->getContextDetails($code);if(!is_array($details)||empty($details['title']))continue;$courses[]=array('code'=>(string)$code,'title'=>(string)$details['title'],'status'=>(string)($details['status']??''),'image'=>$this->contextImages->getContextImage($code));}usort($courses,fn($a,$b)=>strcasecmp($a['title'],$b['title']));return $courses;}
 private function text($key,$fallback){return $this->language->code2Txt('mod_myteaching_'.$key,'myteaching',null,$fallback);}
 public function show(){if(!$this->user->isLoggedIn())return '';$courses=$this->courses($this->user->userId());$insights=array();foreach($this->insights->courseInsights($this->user->userId()) as $row)$insights[$row['code']]=$row;$current=(string)$this->contexts->getContextCode();$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$html='<section class="student-learning-overview myteaching-overview" aria-labelledby="my-teaching-title"><header class="student-learning-overview__header"><div><p class="student-learning-overview__eyebrow">Your teaching</p><h1 id="my-teaching-title">My Teaching</h1><p>'.$e($this->text('intro','See your [-contexts-], their participation and work awaiting attention.')).'</p></div><span class="student-learning-overview__count">'.count($courses).' '.$e($this->text(count($courses)===1?'course':'courses',count($courses)===1?'[-context-]':'[-contexts-]')).'</span></header><div class="student-learning-overview__grid">';foreach($courses as $course){$manage=$this->uri(array('action'=>'joincontext','contextcode'=>$course['code'],'contextmodule'=>'context','contextaction'=>'controlpanel'),'context');$active=$current!==''&&$current!=='root'&&$current===$course['code'];$enter=$active?$this->uri(array('action'=>'leavecontext'),'context'):$this->uri(array('action'=>'joincontext','contextcode'=>$course['code']),'context');$enterLabel=$active?$this->language->code2Txt('phrase_leavecourse','system',null,'Leave [-context-]'):$this->text('enter','Enter [-context-]');$image=$course['image']?'<img class="myteaching-course__image" src="'.$e($course['image']).'" alt="" loading="lazy">':'';$metrics=isset($insights[$course['code']])?$this->insights->renderCard($insights[$course['code']]):'';$html.='<article class="student-learning-course myteaching-course">'.$image.'<div class="student-learning-course__topline"><span>'.($course['status']==='Unpublished'?'Unpublished':'Published').'</span></div><h2>'.$e($course['title']).'</h2>'.$metrics.'<div class="myteaching-course__actions"><a class="button student-learning-course__action" href="'.$e($enter).'">'.$e($enterLabel).'</a><a class="button chisimba-button-secondary student-learning-course__action" href="'.$e($manage).'">'.$e($this->text('managecourse','Manage [-context-]')).'</a></div></article>';}$html.='</div>';if(!$courses)$html.='<div class="dashboard-empty-state"><div><h2>'.$e($this->text('empty','No teaching [-contexts-]')).'</h2><p>'.$e($this->text('emptyhelp','[-contexts-] will appear here when this account is added to a teaching team.')).'</p></div></div>';return $html.'</section>';}
}
?>
