<?php
/** Cross-course author overview for My Teaching. @author Derek Keats */
if(empty($GLOBALS['kewl_entry_point_run']))die('You cannot view this page directly');
class teachingcourseoverview extends ChisimbaObject
{
 private $user;private $userContext;private $contexts;private $contextImages;private $insights;
 public function init(){$this->user=$this->getObject('user','security');$this->userContext=$this->getObject('usercontext','context');$this->contexts=$this->getObject('dbcontext','context');$this->contextImages=$this->getObject('contextimage','context');$this->insights=$this->getObject('teachinginsights','myteaching');}
 public function courses($userId){$courses=array();foreach(array_values(array_unique((array)$this->userContext->getContextWhereLecturer($userId))) as $code){$details=$this->contexts->getContextDetails($code);if(!is_array($details)||empty($details['title']))continue;$courses[]=array('code'=>(string)$code,'title'=>(string)$details['title'],'status'=>(string)($details['status']??''),'image'=>$this->contextImages->getContextImage($code));}usort($courses,fn($a,$b)=>strcasecmp($a['title'],$b['title']));return $courses;}
 public function show(){if(!$this->user->isLoggedIn())return '';$courses=$this->courses($this->user->userId());$insights=array();foreach($this->insights->courseInsights($this->user->userId()) as $row)$insights[$row['code']]=$row;$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$html='<section class="student-learning-overview myteaching-overview" aria-labelledby="my-teaching-title"><header class="student-learning-overview__header"><div><p class="student-learning-overview__eyebrow">Your teaching</p><h1 id="my-teaching-title">My Teaching</h1><p>See your courses, their participation and work awaiting attention.</p></div><span class="student-learning-overview__count">'.count($courses).' '.(count($courses)===1?'course':'courses').'</span></header><div class="student-learning-overview__grid">';foreach($courses as $course){$url=$this->uri(array('action'=>'joincontext','contextcode'=>$course['code'],'contextmodule'=>'context','contextaction'=>'controlpanel'),'context');$image=$course['image']?'<img class="myteaching-course__image" src="'.$e($course['image']).'" alt="" loading="lazy">':'';$metrics=isset($insights[$course['code']])?$this->insights->renderCard($insights[$course['code']]):'';$html.='<article class="student-learning-course myteaching-course">'.$image.'<div class="student-learning-course__topline"><span>'.($course['status']==='Unpublished'?'Unpublished':'Published').'</span></div><h2>'.$e($course['title']).'</h2>'.$metrics.'<a class="button student-learning-course__action" href="'.$e($url).'">Manage course</a></article>';}$html.='</div>';if(!$courses)$html.='<div class="dashboard-empty-state"><div><h2>No teaching courses</h2><p>Courses will appear here when this account is added to a teaching team.</p></div></div>';return $html.'</section>';}
}
?>
