<?php
/** Webinar-owned editing, using shared form, rich-text, media and Help primitives. */
$r=$this->getObject('webinarrenderer','webinar');$e=['webinarrenderer','escape'];$s=$this->getObject('webinareditservice','webinar');$record=$this->getVar('webinarEditRecord');$kind=$this->getVar('webinarEditKind');$d=$record?json_decode($record['payload'],true):[];$c=$s->classification();
$input=$this->getVar('webinarEditInput')?:['title'=>html_entity_decode($record['title']??'',ENT_QUOTES|ENT_HTML5,'UTF-8'),'description'=>$d['description']??'','image'=>html_entity_decode($d['image']??'',ENT_QUOTES,'UTF-8'),'image_alt'=>$d['image_alt']??'','status'=>$record['status']??'draft','starts_at'=>substr(str_replace(' ','T',$record['presented_at']??''),0,16),'ends_at'=>substr(str_replace(' ','T',$d['ends_at']??''),0,16),'timezone'=>$d['timezone']??'Africa/Johannesburg','recording'=>$d['recording']??'','joining_url'=>$d['joining_url']??'','registration_open'=>!empty($d['registration_open'])?'1':'','cancelled'=>!empty($d['cancelled'])?'1':'','speakers'=>$d['speakers']??[],'tags'=>$record&&$kind==='webinar'?implode(', ',array_column($c->forItem('webinar',$record['id'],'tag',true),'name')):'','categories'=>$record&&$kind==='webinar'?array_column($c->forItem('webinar',$record['id'],'category',true),'id'):[],'version'=>$record?webinareditservice::version($record):'','create_id'=>bin2hex(random_bytes(16))];
$field=function($name,$label,$type='text',$required=false)use($input,$e,$r){$id=$name==='image'?'comp_webinar_image':'webinar-'.$name;return '<div class="chisimba-form-field"><label for="'.$id.'">'.$e($r->text($label)).'</label><input id="'.$id.'" type="'.$type.'" name="'.$name.'" value="'.$e($input[$name]??'').'"'.($required?' required':'').'></div>';};
$button=function($name,$value,$label,$icon,$extra='')use($r,$e){return '<button class="button" type="submit" name="'.$name.'" value="'.$value.'" '.$extra.'>'.$this->getObject('iconservice','ui')->render($icon,['decorative'=>true]).'<span>'.$e($r->text($label)).'</span></button>';};
echo '<section class="chisimba-form-card chisimba-form-card--wide"><header class="chisimba-form-actions"><h1>'.$e($r->text($kind==='speaker'?($record?'edit_speaker':'add_speaker'):($record?'edit':'add'))).'</h1>'.$this->getObject('contextualhelp','help')->show('webinar','editing',true).'</header><p class="chisimba-field-help">'.$e($r->text('editor_scope')).'</p>';
$error=$this->getVar('webinarEditError');echo '<p role="alert" data-webinar-error>'.$e($error?$r->text($error):'').'</p><p role="status" data-webinar-status>'.$e($this->getParam('saved')==='1'?$r->text('editor_saved'):'').'</p>';
echo '<form method="post" class="chisimba-form chisimba-form--wide" data-webinar-editor data-failed="'.$e($r->text('editor_network')).'" data-saving="'.$e($r->text('editor_saving')).'" data-unsaved="'.$e($r->text('editor_unsaved')).'" data-suggestions="'.$e($this->uri(['action'=>'tag_suggestions'],'webinar')).'" action="'.$e($this->uri(['action'=>'save'],'webinar')).'">';
foreach(['id'=>$record['id']??'','kind'=>$kind,'version'=>$input['version']??'','create_id'=>$input['create_id']??bin2hex(random_bytes(16)),'aux_create_id'=>bin2hex(random_bytes(16)),'csrf_token'=>$this->getVar('webinarEditCsrf'),'status'=>$input['status']??'draft'] as $key=>$value)echo '<input type="hidden" name="'.$key.'" value="'.$e($value).'">';
echo '<div class="chisimba-form-actions">'.$button('publish_action','draft','save_draft','save','formnovalidate').$button('publish_action','published','publish','send').$r->button($kind==='speaker'?'manage_speakers':'manage','list',['action'=>'manage','kind'=>$kind]).'</div>';
echo $field('title',$kind==='speaker'?'speaker_name':'editor_title','text',true).'<div class="chisimba-publishing-layout"><div>';
$area=$this->newObject('htmlarea','htmlelements');$area->name='description';$area->cssId='webinar-description';$area->width='100%';$area->setContent($input['description']);
echo '<div class="chisimba-form-field"><label for="webinar-description">'.$e($r->text($kind==='speaker'?'speaker_bio':'description')).'</label>'.$area->show().'</div>';
echo '<fieldset class="chisimba-card"><legend>'.$e($r->text($kind==='speaker'?'speaker_photo':'banner')).'</legend>'.$field('image','image_url').'<img data-webinar-image class="chisimba-featured-image-preview" hidden alt=""><button type="button" class="button" data-composition-media="comp_webinar_image">'.$this->getObject('iconservice','ui')->render('image',['decorative'=>true]).'<span>'.$e($r->text('choose_image')).'</span></button>'.$field('image_alt','image_alt').'<p>'.$e($r->text('image_help')).'</p></fieldset>';
if($kind==='webinar'){
 echo '<fieldset class="chisimba-card"><legend>'.$e($r->text('speakers')).'</legend><div class="chisimba-choice-list" data-webinar-speakers>';
 foreach($this->getObject('webinarstore','webinar')->published('speaker') as $speaker)echo '<label><input type="checkbox" name="speakers[]" value="'.$e($speaker['id']).'"'.(in_array($speaker['id'],is_array($input['speakers'])?$input['speakers']:[],true)?' checked':'').'> '.$e(html_entity_decode($speaker['title'],ENT_QUOTES|ENT_HTML5,'UTF-8')).'</label>';
 echo '</div><details><summary>'.$e($r->text('add_speaker')).'</summary><div class="chisimba-form-field"><label for="new-speaker-name">'.$e($r->text('speaker_name')).'</label><input id="new-speaker-name" name="speaker_name" type="text"></div><div class="chisimba-form-field"><label for="new-speaker-bio">'.$e($r->text('speaker_bio')).'</label><textarea id="new-speaker-bio" name="speaker_bio" rows="5"></textarea></div>'.$button('operation','speaker_add','add_speaker','user-plus','formnovalidate formaction="'.$e($this->uri(['action'=>'editor_aux'],'webinar')).'"').'</details></fieldset>';
}
echo '</div><aside class="chisimba-publishing-sidebar">';
if($kind==='webinar'){
 echo '<fieldset class="chisimba-card"><legend>'.$e($r->text('schedule')).'</legend>'.$field('starts_at','start_time','datetime-local',true).$field('ends_at','end_time','datetime-local',true).'<div class="chisimba-form-field"><label for="webinar-timezone">'.$e($r->text('timezone')).'</label><select id="webinar-timezone" name="timezone">';foreach(DateTimeZone::listIdentifiers() as $zone)echo '<option value="'.$e($zone).'"'.($zone===$input['timezone']?' selected':'').'>'.$e($zone).'</option>';echo '</select></div><p>'.$e($r->text('schedule_help')).'</p></fieldset>';
 echo '<fieldset class="chisimba-card"><legend>'.$e($r->text('booking')).'</legend><div class="chisimba-choice-list">';foreach(['registration_open','cancelled'] as $key)echo '<label><input type="checkbox" name="'.$key.'" value="1"'.(($input[$key]??'')==='1'?' checked':'').'> '.$e($r->text($key)).'</label>';echo '</div>'.$field('joining_url','joining_url','url').'<p>'.$e($r->text('joining_help')).'</p></fieldset>'.$field('recording','recording_url','url');
 $categories=$c->creationChoices('webinar','site','site','category');echo '<fieldset class="chisimba-card"><legend>'.$e($r->text('categories')).'</legend><div class="chisimba-choice-list" data-webinar-categories>';foreach($categories as $term)echo '<label><input type="checkbox" name="categories[]" value="'.$e($term['id']).'"'.(in_array($term['id'],is_array($input['categories'])?$input['categories']:[],true)?' checked':'').'> '.$e($term['name']).'</label>';echo '</div>';
 if($c->mayManage('site','site','category')){echo '<details><summary>'.$e($r->text('add_category')).'</summary><div class="chisimba-form-field"><label for="category-name">'.$e($r->text('category_name')).'</label><input id="category-name" name="category_name" type="text"></div><div class="chisimba-form-field"><label for="category-parent">'.$e($r->text('category_parent')).'</label><select id="category-parent" name="category_parent"><option value="">'.$e($r->text('category_root')).'</option>';foreach($categories as $term)echo '<option value="'.$e($term['id']).'">'.$e($term['name']).'</option>';echo '</select></div>'.$button('operation','category_add','add_category','plus','formnovalidate formaction="'.$e($this->uri(['action'=>'editor_aux'],'webinar')).'"').'</details>';}
 echo '</fieldset>'.$field('tags','tags').'<datalist id="webinar-tag-choices"></datalist><p>'.$e($r->text('tags_help')).'</p>';
}
echo '<div class="chisimba-form-actions">'.$button('publish_action','draft','save_draft','save','formnovalidate').$button('publish_action','published','publish','send').'</div><p>'.$e($r->text('publish_help')).'</p><nav class="chisimba-form-actions">'.$r->button($kind==='speaker'?'manage_speakers':'manage','list',['action'=>'manage','kind'=>$kind]).'<a class="button" data-webinar-preview'.(!$record?' hidden':'').' target="_blank" rel="noopener" href="'.$e($record?$this->uri(['action'=>'preview','id'=>$record['id']],'webinar'):'#').'">'.$this->getObject('iconservice','ui')->render('eye',['decorative'=>true]).'<span>'.$e($r->text('preview')).'</span></a></nav></aside></div><input type="hidden" name="editor_complete" value="1"></form></section>';
$picker=html_entity_decode($this->uri(['action'=>'filepicker'],'filemanager'),ENT_QUOTES,'UTF-8');
$this->appendArrayVar('headerParams','<script>window.ChisimbaCompositionPicker='.json_encode($picker,JSON_HEX_TAG|JSON_HEX_AMP).';</script><script defer src="'.$e($this->getResourceUri('composition.js','contentblocks')).'"></script><script defer src="'.$e($this->getResourceUri('editor.js','webinar')).'"></script>');
