<?php
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$url=fn($params=array())=>html_entity_decode($this->uri($params,'kanban'),ENT_QUOTES,'UTF-8');
$scopeType=$kanbanScope['type'];
$hidden=function($boardId='')use($e,$kanbanCsrf,$scopeType){return '<input type="hidden" name="csrf_token" value="'.$e($kanbanCsrf).'"/><input type="hidden" name="scope" value="'.$e($scopeType).'"/>'.($boardId!==''?'<input type="hidden" name="boardid" value="'.$e($boardId).'"/>':'');};
$labels=array('not_started'=>'Not started','in_progress'=>'In progress','completed'=>'Completed');
$recoveryText=$this->getObject('language','language');
// Language strings may contain HTML entities; JSON/textContent needs plain text.
$recoveryMessages=array();
foreach(array('kept','unavailable','restored','conflict','restore','discard','signin','uncertain','saving') as $key)$recoveryMessages[$key]=html_entity_decode($recoveryText->languageText('mod_kanban_draft_'.$key,'kanban'),ENT_QUOTES|ENT_HTML5,'UTF-8');
$icons=$this->getObject('iconservice','ui');
$viewText=fn($key)=>$e($this->getObject('language','language')->languageText('mod_kanban_view_'.$key,'kanban'));
?>
<main class="chisimba-workspace chisimba-flow chisimba-structural-main chisimba-structural-main--full kanban-workspace" data-kanban data-actor="<?php echo $e($this->getObject('user','security')->userId()); ?>" data-scope-id="<?php echo $e($kanbanScope['id']); ?>" data-draft-scope="<?php echo $e($kanbanScope['type'].':'.$kanbanScope['id']); ?>" data-recovery-messages="<?php echo $e(json_encode($recoveryMessages)); ?>" data-token-url="<?php echo $e($url(array('action'=>'formtoken'))); ?>" data-move-url="<?php echo $e($url(array('action'=>'movetask'))); ?>" data-csrf="<?php echo $e($kanbanCsrf); ?>" data-scope="<?php echo $e($scopeType); ?>" style="width:100%;max-width:none;overflow:auto;background:var(--chisimba-background)">
    <header class="chisimba-page-header chisimba-card kanban-page-header">
        <div><p class="chisimba-eyebrow"><?php echo $e($kanbanScope['label']); ?></p><h1>Kanban boards</h1><p>Plan work in personal, course or site scope.</p></div>
        <div class="kanban-scope-controls"><?php echo $this->getObject('contextualhelp','help')->show('kanban','recovery',true); ?>
            <form class="chisimba-form-field chisimba-form-field--compact kanban-scope-form" method="get" action="index.php"><input type="hidden" name="module" value="kanban"/><label for="kanban-scope">Board scope</label><div class="chisimba-cluster kanban-compact-actions"><select id="kanban-scope" name="scope"><option value="personal" <?php echo $scopeType==='personal'?'selected':''; ?>>Personal — only your boards</option><?php if((string)$this->getObject('dbcontext','context')->getContextCode()!=='root'&&(string)$this->getObject('dbcontext','context')->getContextCode()!==''): ?><option value="context" <?php echo $scopeType==='context'?'selected':''; ?>>Course — boards for this course</option><?php endif; ?><?php if($this->getObject('user','security')->isAdmin()): ?><option value="site" <?php echo $scopeType==='site'?'selected':''; ?>>Site — organisation-wide boards</option><?php endif; ?></select><button class="button" type="submit"><?php echo $icons->render('eye',array('decorative'=>true)); ?><span>View boards</span></button><button class="button chisimba-button-secondary" type="button" data-kanban-fullscreen aria-pressed="false">Full screen</button></div></form>
        </div>
    </header>
    <?php if($kanbanMessage!==''): ?><div class="chisimba-notice chisimba-notice--success" role="status"><?php echo $e($kanbanMessage); ?></div><?php endif; ?>
    <?php if($kanbanError!==''): ?><div class="chisimba-notice chisimba-notice--error" role="alert"><?php echo $e($kanbanError); ?></div><?php endif; ?>
    <?php if(!empty($kanbanRecovery)): ?>
    <section class="chisimba-form-card" aria-label="<?php echo $e($recoveryText->languageText('mod_kanban_recovery_title','kanban')); ?>">
        <h2><?php echo $e($recoveryText->languageText('mod_kanban_recovery_title','kanban')); ?></h2>
        <p><?php echo $e($recoveryText->languageText('mod_kanban_recovery_copy','kanban')); ?></p>
        <?php foreach($kanbanRecovery as $field=>$value): ?><label class="chisimba-form-field"><?php echo $e($field); ?><textarea readonly><?php echo $e($value); ?></textarea></label><?php endforeach; ?>
    </section>
    <?php endif; ?>
    <form class="chisimba-cluster" method="get" action="<?php echo $e($url()); ?>"><input type="hidden" name="module" value="kanban"/><input type="hidden" name="scope" value="<?php echo $e($scopeType); ?>"/><label><input type="checkbox" name="archived" value="1" <?php echo !empty($_GET['archived'])?'checked':''; ?> onchange="this.form.submit()"/> Include archived boards</label></form>
    <?php if($kanbanCanCreate): ?><details class="chisimba-form-card kanban-create">
        <summary>Create a board</summary>
        <form class="chisimba-form" method="post" action="<?php echo $e($url(array('action'=>'saveproject'))); ?>">
            <?php echo $hidden(); ?>
            <div class="chisimba-form-field"><label for="kanban-new-title">Board title</label><input id="kanban-new-title" name="title" required maxlength="255"/></div>
            <div class="chisimba-form-field"><label for="kanban-new-description">Description</label><textarea id="kanban-new-description" name="description"></textarea></div>
            <div class="chisimba-form-actions"><button class="button" type="submit"><?php echo $icons->render('circle-plus',array('decorative'=>true)); ?> Create board</button></div>
        </form>
    </details><?php endif; ?>
    <?php if(!$kanbanBoards): ?><div class="chisimba-card"><h2>No boards yet</h2><p>Create the first board in this scope.</p></div><?php endif; ?>
    <?php foreach($kanbanBoards as $board): $manage=$board['permission']==='manage';$edit=$board['permission']!=='view';$counts=array('not_started'=>0,'in_progress'=>0,'completed'=>0);foreach($board['tasks'] as $countTask){if(isset($counts[$countTask['status']]))$counts[$countTask['status']]++;}$taskCount=array_sum($counts);$progress=$taskCount?(int)round(($counts['completed']/$taskCount)*100):0;$updated=!empty($board['datemodified'])?date('j M Y',strtotime($board['datemodified'])):'';$groupIds=array();foreach($kanbanBoards as $groupBoard)if($groupBoard['scopetype']===$board['scopetype']&&$groupBoard['scopeid']===$board['scopeid'])$groupIds[]=$groupBoard['id'];$groupPosition=array_search($board['id'],$groupIds,true); ?>
    <section id="board-<?php echo $e($board['id']); ?>" class="chisimba-card chisimba-focus-surface kanban-board <?php echo $taskCount===0?'kanban-board--empty':''; ?>" data-board-id="<?php echo $e($board['id']); ?>" data-board-scope-type="<?php echo $e($board['scopetype']); ?>" data-board-scope-id="<?php echo $e($board['scopeid']); ?>" data-task-total="<?php echo $e($taskCount); ?>">
        <header class="kanban-board__header">
            <div><p class="chisimba-eyebrow"><?php echo $e(ucfirst($board['scopetype'])); ?> · <?php echo $e(ucfirst($board['permission'])); ?></p><h2 class="chisimba-cluster"><?php echo $icons->render('folder-kanban',array('decorative'=>true)); ?><span><?php echo $e($board['title']); ?></span></h2><?php if($board['description']!==''): ?><p><?php echo nl2br($e($board['description'])); ?></p><?php endif; ?><div class="chisimba-cluster" aria-label="Board task status"><span class="chisimba-pill" data-board-total><?php echo $e($taskCount.' '.($taskCount===1?'task':'tasks')); ?></span><span class="chisimba-pill" data-board-status="not_started"><?php echo $e($counts['not_started'].' not started'); ?></span><span class="chisimba-pill" data-board-status="in_progress"><?php echo $e($counts['in_progress'].' in progress'); ?></span><span class="chisimba-pill chisimba-pill--success" data-board-status="completed"><?php echo $e($counts['completed'].' completed'); ?></span><span class="chisimba-pill chisimba-pill--success" data-board-progress><?php echo $e($progress.'% complete'); ?></span><?php if($updated!==''): ?><span class="chisimba-pill"><?php echo $e('Updated '.$updated); ?></span><?php endif; ?></div></div>
            <div class="kanban-board__summary-actions"><div class="kanban-progress"><strong data-board-progress-label><?php echo $e($progress.'%'); ?></strong><progress max="100" value="<?php echo $e($progress); ?>" aria-label="<?php echo $e($board['title'].' completion'); ?>"></progress></div><div class="chisimba-cluster kanban-compact-actions"><button class="button chisimba-button-secondary" type="button" data-board-focus aria-pressed="false" data-enter-label="<?php echo $viewText('focus'); ?>" data-exit-label="<?php echo $viewText('exit'); ?>" hidden><?php echo $icons->render('maximize',array('decorative'=>true)); ?><span data-board-focus-label><?php echo $viewText('focus'); ?></span></button><button class="button chisimba-button-secondary kanban-board__toggle" type="button" data-board-toggle aria-expanded="true"><?php echo $icons->render('chevron-up',array('decorative'=>true)); ?><span data-board-toggle-label>Collapse</span></button><?php if($manage): ?><form method="post" action="<?php echo $e($url(array('action'=>'reorderprojects'))); ?>" data-board-reorder><?php echo $hidden($board['id']); ?><input type="hidden" name="direction" value="up"/><button class="button chisimba-button-secondary" type="submit" <?php echo $groupPosition>0?'':'disabled'; ?>>Up</button></form><form method="post" action="<?php echo $e($url(array('action'=>'reorderprojects'))); ?>" data-board-reorder><?php echo $hidden($board['id']); ?><input type="hidden" name="direction" value="down"/><button class="button chisimba-button-secondary" type="submit" <?php echo $groupPosition<count($groupIds)-1?'':'disabled'; ?>>Down</button></form><?php endif; ?></div></div>
        </header>
        <div class="kanban-board__body">
        <?php if($manage): ?><div class="chisimba-cluster kanban-compact-actions kanban-board__management"><details><summary class="button chisimba-button-secondary">Edit</summary><form class="chisimba-form kanban-popover" method="post" action="<?php echo $e($url(array('action'=>'saveproject'))); ?>"><?php echo $hidden($board['id']); ?><div class="chisimba-form-field"><label>Title<input name="title" value="<?php echo $e($board['title']); ?>" required/></label></div><div class="chisimba-form-field"><label>Description<textarea name="description"><?php echo $e($board['description']); ?></textarea></label></div><button class="button" type="submit">Save</button></form></details><form method="post" action="<?php echo $e($url(array('action'=>'archiveproject','archived'=>'1'))); ?>"><?php echo $hidden($board['id']); ?><button class="button chisimba-button-secondary" type="submit"><?php echo empty($board['isarchived'])?'Archive':'Restore'; ?></button></form><form method="post" action="<?php echo $e($url(array('action'=>'deleteproject'))); ?>" data-confirm="Delete this board and all its tasks?"><?php echo $hidden($board['id']); ?><button class="button chisimba-button-danger" type="submit">Delete</button></form></div><?php endif; ?>
        <?php $targetType='kanban_board';$targetId=$board['id'];$targetLabel=$board['title'];$targetLinkedNotes=$board['linkednotes'];include __DIR__.'/note_connections_tpl.php'; ?>
        <?php if($manage): ?><details class="kanban-sharing"><summary>Sharing and permissions</summary><p>Enter one username per line followed by <code>:view</code>, <code>:edit</code>, or <code>:manage</code>. Saving replaces current direct-user grants. Group and course-role grants will use this same permission model when those resolvers are enabled.</p><form class="chisimba-form" method="post" action="<?php echo $e($url(array('action'=>'saveaccess'))); ?>"><?php echo $hidden($board['id']); ?><div class="chisimba-form-field"><label>Direct user grants<textarea name="grants" placeholder="jane:edit&#10;john:view"><?php foreach($this->getObject('dbkanbanaccess')->grants($board['id']) as $grant){if($grant['principaltype']==='user'){$details=$this->getObject('user','security')->getUserDetails($grant['principalid']);echo $e(($details['username']??$grant['principalid']).':'.$grant['permission'])."\n";}} ?></textarea></label></div><button class="button" type="submit">Save sharing</button></form><hr/><p>A public link lets anyone who has it view this board. It never allows editing. Creating a new link replaces the old one.</p><?php $publicToken=$this->getObject('dbkanbanaccess')->publicLinkToken($board['id']); ?><form class="chisimba-form kanban-public-link-form" method="post" action="<?php echo $e($url(array('action'=>'savepubliclink'))); ?>" data-public-link-form><?php echo $hidden($board['id']); ?><div class="kanban-public-link-form__controls"><label class="kanban-public-link-form__toggle"><input type="checkbox" name="publiclink" value="1" <?php echo $publicToken?'checked':''; ?>/> <span>Enable public view link</span></label><button class="button" type="submit" data-public-link-submit><?php echo $publicToken?'Replace public view link':'Create public view link'; ?></button></div><label class="chisimba-form-field kanban-public-link-form__url" data-public-link-url-container <?php echo $publicToken?'':'hidden'; ?>><span>Public view URL</span><input readonly data-public-link-url value="<?php echo $publicToken?$e($url(array('action'=>'publicview','token'=>$publicToken))):''; ?>"/></label><p data-public-link-feedback role="status" aria-live="polite"></p></form></details><?php endif; ?>
        <?php if($edit): ?><form class="chisimba-form kanban-add-task kanban-compact-actions" data-task-create method="post" action="<?php echo $e($url(array('action'=>'savetask'))); ?>">
            <?php echo $hidden($board['id']); ?>
            <div class="kanban-quick-entry"><div class="chisimba-form-field"><label>New task<input name="title" maxlength="255" placeholder="What needs doing?" required/></label></div><button class="button" type="submit">Add task</button></div>
            <details><summary>Add description or notes</summary><div class="chisimba-form-field"><label>Description<textarea name="description"></textarea></label></div><div class="chisimba-form-field"><label>Notes<textarea name="notes"></textarea></label></div></details>
            <p data-task-feedback role="status" aria-live="polite"></p>
        </form><?php endif; ?>
        <div class="kanban-columns">
        <?php foreach($labels as $status=>$label): ?>
            <section class="kanban-column" data-status="<?php echo $e($status); ?>"><h3 class="kanban-column__heading"><span><?php echo $e($label); ?></span><span class="chisimba-pill" data-column-count><?php echo $e($counts[$status]); ?></span></h3><div class="kanban-task-list">
            <?php foreach($board['tasks'] as $task): if($task['status']!==$status)continue; ?>
                <?php include __DIR__.'/task_card_tpl.php'; ?>
            <?php endforeach; ?>
            </div></section>
        <?php endforeach; ?>
        </div>
        </div>
    </section>
    <?php endforeach; ?>
</main>
<?php $noteWindow=$this->getObject('window','ui');$noteWindow->setId('kanban-note-window')->setTitle('Note')->setWidth('56rem')->setContent('<div class="kanban-note-modal" data-note-modal-content><p class="chisimba-muted" role="status">Loading note…</p></div>');echo $noteWindow->show(); ?>
