<?php
$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$icons=$this->getObject('iconservice','ui');
$labels=array('not_started'=>'Not started','in_progress'=>'In progress','completed'=>'Completed');
$board=$kanbanPublicBoard;$counts=array('not_started'=>0,'in_progress'=>0,'completed'=>0);foreach($board['tasks'] as $task)if(isset($counts[$task['status']]))$counts[$task['status']]++;$total=array_sum($counts);$progress=$total?(int)round(($counts['completed']/$total)*100):0;
?>
<main class="chisimba-workspace chisimba-flow chisimba-structural-main chisimba-structural-main--full kanban-workspace" style="width:100%;max-width:none;overflow:auto;background:var(--chisimba-background)">
    <header class="chisimba-page-header chisimba-card kanban-page-header"><div><p class="chisimba-eyebrow">Public, read-only board</p><h1><?php echo $icons->render('folder-kanban',array('decorative'=>true)); ?> <?php echo $e($board['title']); ?></h1><?php if($board['description']!==''): ?><p><?php echo nl2br($e($board['description'])); ?></p><?php endif; ?></div><p class="chisimba-notice">Anyone with this link can view this board. Editing is disabled.</p></header>
    <section class="chisimba-card kanban-board" data-task-total="<?php echo $e($total); ?>"><div class="chisimba-cluster" aria-label="Board task status"><span class="chisimba-pill"><?php echo $e($total.' '.($total===1?'task':'tasks')); ?></span><span class="chisimba-pill"><?php echo $e($progress.'% complete'); ?></span></div><div class="kanban-columns"><?php foreach($labels as $status=>$label): ?><section class="kanban-column" data-status="<?php echo $e($status); ?>"><h2 class="kanban-column__heading"><span><?php echo $e($label); ?></span><span class="chisimba-pill"><?php echo $e($counts[$status]); ?></span></h2><div class="kanban-task-list"><?php foreach($board['tasks'] as $task):if($task['status']!==$status)continue; ?><article class="kanban-task"><h3><?php echo $e($task['title']); ?></h3><?php if($task['description']!==''): ?><p><?php echo nl2br($e($task['description'])); ?></p><?php endif; ?><?php if($task['notes']!==''): ?><details><summary>Notes</summary><p><?php echo nl2br($e($task['notes'])); ?></p></details><?php endif; ?><?php if($task['subtasks']): ?><div class="kanban-subtasks"><strong>Subtasks</strong><?php foreach($task['subtasks'] as $sub): ?><label class="kanban-subtask"><input type="checkbox" disabled <?php echo !empty($sub['iscompleted'])?'checked':''; ?>/><span><?php echo $e($sub['title']); ?></span></label><?php endforeach; ?></div><?php endif; ?></article><?php endforeach; ?></div></section><?php endforeach; ?></div></section>
</main>
