<?php require __DIR__.'/common.php'; $book=$shopBook??[]; $virtual=ShopRules::options($book); $type=$book['product_type']??'physical'; $isCombo=($book['kind']??'')==='combo'||!empty($book['book_ids']); ?>
<main class="chisimba-workspace chisimba-stack"><header class="chisimba-cluster"><h1><?=$t($isCombo?'edit_combo':'edit_book')?></h1><a class="button chisimba-button-secondary" href="<?=$url('manage')?>"><?=$actionIcon('manage')?> <?=$t('manage')?></a><?=$this->getObject('contextualhelp','help')->show('shop','managing',true)?></header>
<form method="post" action="<?=$url('savebook')?>" class="chisimba-form-card chisimba-form chisimba-flow"><?php $csrf(); $hidden('id',$book['id']??''); $hidden('revision',$book['revision']??0); $hidden('kind',$isCombo?'combo':'book'); ?>
<?php $field('title',$book['title']??''); $field('description',$book['description']??'','textarea',false); ?>
<?php if (!$isCombo): ?>
<div class="chisimba-form-field"><label for="shop-product-type"><?=$t('product_type')?></label><select id="shop-product-type" name="product_type"><?php foreach(['physical','virtual'] as $value): ?><option value="<?=$value?>"<?=$type===$value?' selected':''?>><?=$t($value)?></option><?php endforeach; ?></select></div>
<fieldset data-shop-virtual class="chisimba-stack"><legend><?=$t('virtual_fulfilment')?></legend>
<div class="chisimba-form-field"><label for="shop-virtual-kind"><?=$t('virtual_kind')?></label><select id="shop-virtual-kind" name="virtual_kind"><?php foreach(['contribution','membership','download'] as $value): ?><option value="<?=$value?>"<?=($book['virtual_kind']??$virtual['kind']??'contribution')===$value?' selected':''?>><?=$t($value)?></option><?php endforeach; ?></select></div>
<div data-shop-membership class="chisimba-form-grid"><div class="chisimba-form-field"><label for="shop-membership-tier"><?=$t('membership_tier')?></label><select id="shop-membership-tier" name="membership_tier"><?php foreach($shopService->membershipTiers() as $code=>$tier): if((int)$tier['rank']===0)continue; ?><option value="<?=$esc($code)?>"<?=($book['membership_tier']??$virtual['tier']??'')===$code?' selected':''?>><?=$esc($tier['label'])?></option><?php endforeach; ?></select></div></div>
<div class="chisimba-form-field"><label for="shop-billing-period"><?=$t('billing_period')?></label><select id="shop-billing-period" name="billing_period"><?php foreach(['one_off','monthly','annual'] as $value): ?><option value="<?=$value?>"<?=($book['billing_period']??$virtual['billing_period']??'one_off')===$value?' selected':''?>><?=$t($value)?></option><?php endforeach; ?></select></div>
<div data-shop-download class="chisimba-stack"><?php $field('download_files',$book['download_files']??implode("\n",$virtual['file_ids']??[]),'textarea',false); ?><ul data-shop-download-list data-remove="<?=$t('remove_item')?>"><?php foreach($shopService->downloadFileNames($book['download_files']??implode("\n",$virtual['file_ids']??[])) as $fileId=>$filename): ?><li data-file-id="<?=$esc($fileId)?>"><?=$esc($filename)?></li><?php endforeach; ?></ul><p><?=$t('download_files_help')?></p><button type="button" class="button chisimba-button-secondary" hidden data-shop-download-picker="<?=$esc($this->uri(['action'=>'filepicker','target'=>'shop-download_files','policy'=>'download','location'=>'user'],'filemanager'))?>"><?=$t('choose_download')?></button></div>
<p><?=$t('virtual_help')?></p></fieldset>
<?php endif; ?>
<div class="chisimba-form-grid"><?php if (!$isCombo) $field('isbn' ,$book['isbn']??'','text',false); $field('price',$book['price']??(isset($book['price_minor'])?number_format($book['price_minor']/100,2,'.',''):'')); if (!$isCombo) $field('stock',$book['stock']??0,'number'); ?></div>
<?php if ($isCombo): ?><fieldset class="chisimba-form-field"><legend><?=$t('combo_books')?></legend><p><?=$t('combo_help')?></p>
<?php foreach ($shopBooks??[] as $child): if ($child['status']==='archived'||!ShopRules::physical($child)||($child['kind']??'')==='combo'||$child['id']===($book['id']??'')) continue; ?>
<label><input type="checkbox" name="book_ids[]" value="<?=$esc($child['id'])?>"<?=in_array($child['id'],$book['book_ids']??[],true)?' checked':''?>> <?=$esc($child['title'])?> · <?=$t($child['status'])?> · <?=$money($child['sale_price_minor']??$child['price_minor'])?></label>
<?php endforeach; ?></fieldset><p><label><input type="checkbox" name="cross_sell" value="1"<?=!empty($book['cross_sell'])?' checked':''?>> <?=$t('cross_sell')?></label></p><?php endif; ?>
<p><?=$t('price_hint')?></p><div class="chisimba-form-field"><label for="shop-sale-price"><?=$t('sale_price')?></label><input id="shop-sale-price" readonly value="<?=isset($book['sale_price_minor'])?$esc(number_format($book['sale_price_minor']/100,2,'.','')):''?>"><p><?=$t('sale_price_help')?> <a href="<?=$url('sales')?>"><?=$t('sales')?></a></p></div>
<?php $field('display_order',$book['display_order']??0,'number'); ?><p><?=$t('display_order_help')?></p>
<?php $field('image_url',$book['image_url']??'','url',false); ?>
<img data-shop-cover class="chisimba-featured-image-preview"<?=empty($book['image_url'])?' hidden':' src="'.$esc($book['image_url']).'"'?> alt="<?=$esc($book['title']??'')?>">
<div class="chisimba-form-actions chisimba-form-actions--equal"><button type="button" class="button chisimba-button-secondary" hidden data-shop-picker="<?=$esc($this->uri(['action'=>'filepicker','target'=>'shop-image_url','policy'=>'image','location'=>'user'],'filemanager'))?>"><?=$t('choose_image')?></button></div>
<p><?=$t('image_hint')?></p>
<div class="chisimba-form-field"><label for="shop-status"><?=$t('status')?></label><select id="shop-status" name="status"><?php foreach (['draft','published','archived'] as $status): ?><option value="<?=$esc($status)?>"<?=($book['status']??'draft')===$status?' selected':''?>><?=$t($status)?></option><?php endforeach; ?></select></div>
<div class="chisimba-form-actions chisimba-form-actions--equal"><button type="submit" class="button"><?=$actionIcon('save')?> <?=$t('save')?></button><a class="button chisimba-button-secondary" href="<?=$url('manage')?>"><?=$actionIcon('cancel')?> <?=$t('cancel')?></a></div></form></main>
