<?php
if(empty($GLOBALS['kewl_entry_point_run']))die('You cannot view this page directly');
class myadmin extends controller
{
 private $user;private $contextBlocks;private $dynamicBlocks;private $csrf;
 public function init(){$this->user=$this->getObject('user','security');$this->contextBlocks=$this->getObject('dbcontextblocks','context');$this->dynamicBlocks=$this->getObject('dynamicblocks','blocks');$this->objLanguage=$this->getObject('language','language');$this->csrf=$this->getObject('nativeauthwebcomposition','security')->build()['csrf'];}
 public function dispatch($action){$blockAction=in_array($action,array('renderblock','addblock','removeblock','moveblock'),true);if($blockAction&&$this->user->isAdmin()){$this->dispatchBlockAction($action);return null;}if(!$this->user->isAdmin())return 'noaccess_tpl.php';$notice='';if($action==='runmailqueue')$notice=$this->runMailQueue();if($action==='sendregistrationreminder')$notice=$this->sendRegistrationReminder();$managing=$action==='manage';$this->setVar('managingDashboard',$managing);$this->setVar('administrationOverview',$this->getObject('administrationoverview')->show($this->csrf->issue('myadmin_mail_queue'),$this->csrf->issue('myadmin_registration_reminder'),$notice));foreach(array('right'=>'upperBlocks','left'=>'lowerBlocks','middle'=>'wideBlocks') as $side=>$variable)$this->setVar($variable,$this->contextBlocks->getContextBlocks('myadmin',$side));$this->setVar('mayEditBlocks',$managing);$this->setVar('availableNarrowBlocks',$this->availableBlocks(false));$this->setVar('availableWideBlocks',$this->availableBlocks(true));return 'main_tpl.php';}
 private function runMailQueue(){if(strtoupper((string)($_SERVER['REQUEST_METHOD']??''))!=='POST'||!$this->csrf->consume('myadmin_mail_queue',(string)$this->getParam('csrf_token','')))return $this->objLanguage->languageText('mod_myadmin_queue_session','myadmin','Your session expired. Please try again.');$summary=$this->getObject('communicationworker','communications')->run(20);$values=array('selected'=>(int)$summary['selected'],'sent'=>(int)$summary['sent']);$message=$this->objLanguage->code2Txt('mod_myadmin_queue_run_result','myadmin',$values,'Mail queue checked: [-SELECTED-] selected and [-SENT-] sent.');return str_replace(array('[SELECTED]','[SENT]'),array($values['selected'],$values['sent']),$message);}
 private function sendRegistrationReminder(){if(strtoupper((string)($_SERVER['REQUEST_METHOD']??''))!=='POST'||!$this->csrf->consume('myadmin_registration_reminder',(string)$this->getParam('csrf_token','')))return $this->objLanguage->languageText('mod_myadmin_registration_reminder_session','myadmin','Your session expired. Please try again.');$result=$this->getObject('registrationservice','registration-service')->sendAdministratorReminder((string)$this->getParam('pending_id',''),$this->user->userId());return $this->objLanguage->languageText(!empty($result['ok'])?'mod_myadmin_registration_reminder_sent':'mod_myadmin_registration_reminder_failed','myadmin',!empty($result['ok'])?'The reminder was added to the mail queue.':'The reminder could not be sent. Check the mail queue and try again.');}
 private function dispatchBlockAction($action){$blockId=(string)$this->getParam('blockid','');$side=(string)$this->getParam('side','left');if(!in_array($side,array('left','right','middle'),true))return;if($action==='removeblock'){echo $this->contextBlocks->removeBlock($blockId)?'ok':'notok';return;}if($action==='moveblock'){$direction=$this->getParam('direction','down');$ok=$direction==='up'?$this->contextBlocks->moveBlockUp($blockId,'myadmin'):$this->contextBlocks->moveBlockDown($blockId,'myadmin');echo $ok?'ok':'notok';return;}$block=explode('|',$blockId);if(count($block)<3||!in_array($block[0],array('block','dynamicblock'),true))return;if($action==='addblock'){$result=$this->contextBlocks->addBlock($blockId,$side,'myadmin',$block[2]);echo $result===false?'':$result;return;}$domId=$side.'___'.str_replace('|','___',$blockId);$content=$block[0]==='dynamicblock'?$this->dynamicBlocks->showBlock($block[1]):$this->getObject('blocks','blocks')->showBlock($block[1],$block[2],null,20,true,false);echo '<div id="'.htmlspecialchars($domId,ENT_QUOTES,'UTF-8').'" class="block highlightblock">'.$content.'</div>';}
 private function availableBlocks($wide){if(!$this->user->isAdmin())return array();$options=array();foreach((array)($wide?$this->dynamicBlocks->getWideSiteBlocks():$this->dynamicBlocks->getSmallSiteBlocks()) as $block)$options[]=array('value'=>'dynamicblock|'.$block['id'].'|'.$block['module'],'title'=>(trim((string)($block['title']??''))?:$block['module']).' ('.$block['module'].')');$registry=$this->getObject('dbmoduleblocks','modulecatalogue');foreach((array)$registry->getBlocks($wide?'wide':'normal','site|user|postlogin','admin') as $block){if($block['moduleid']==='contentblocks')continue;$instance=$this->newObject('block_'.$block['blockname'],$block['moduleid']);if(method_exists($instance,'isAvailableForBlockChooser')&&!$instance->isAvailableForBlockChooser())continue;$title=html_entity_decode(trim((string)$instance->title)?:$block['blockname'],ENT_QUOTES|ENT_HTML5,'UTF-8');$options[]=array('value'=>'block|'.$block['blockname'].'|'.$block['moduleid'],'title'=>$title.' ('.$block['moduleid'].')');}usort($options,fn($a,$b)=>strcasecmp($a['title'],$b['title']));return $options;}
}
?>
