<?php
/**
 * Note editor, backlinks and access surface.
 *
 * @author Derek Keats
 * @package pagenotes
 */
$e=fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$url=fn($params=array())=>html_entity_decode($this->uri($params,'pagenotes'),ENT_QUOTES,'UTF-8');
$hidden='<input type="hidden" name="csrf_token" value="'.$e($notesCsrf).'"/><input type="hidden" name="actor" value="'.$e($notesActor).'"/><input type="hidden" name="noteid" value="'.$e($noteRecord['id']).'"/>';
$grantLines=[];foreach($noteGrants as $grant)if($grant['principaltype']==='user')$grantLines[]=$grant['principalid'].':'.$grant['permission'];
$icons=$this->getObject('iconservice','ui');
?>
<main class="chisimba-workspace chisimba-flow chisimba-structural-main chisimba-structural-main--full note-workspace">
 <header class="chisimba-page-header note-heading"><div><p class="chisimba-eyebrow"><?php echo $e(strtoupper($noteRecord['scopetype']));?> NOTE</p><h1 data-note-heading><?php echo $e($noteRecord['title']);?></h1><div class="note-meta"><span class="chisimba-pill"><?php echo $icons->render('link-2',array('decorative'=>true));?> <?php echo count($noteLinks);?> linked</span><span class="chisimba-pill"><?php echo $icons->render('clock-3',array('decorative'=>true));?> Updated <?php echo $e($noteRecord['datemodified']);?></span></div></div><a class="button chisimba-button-secondary" href="<?php echo $e($url(array('scope'=>$noteRecord['scopetype'],'scopeid'=>$noteRecord['scopeid'])));?>"><?php echo $icons->render('arrow-left',array('decorative'=>true));?> All notes</a></header>
 <?php if($notesMessage!==''):?><p class="success" role="status"><?php echo $e($notesMessage);?></p><?php endif;?><?php if($notesError!==''):?><p class="error" role="alert"><?php echo $e($notesError);?></p><?php endif;?>
 <div class="note-layout">
  <section class="dashboard-panel note-editor">
   <?php if($noteCanEdit):?><form method="post" action="<?php echo $e($url(array('action'=>'save')));?>" data-note-save class="chisimba-flow"><?php echo $hidden;?><label class="note-title-label">Note title<input type="text" name="title" maxlength="255" required value="<?php echo $e($noteRecord['title']);?>"/></label><div class="chisimba-editor-toolbar" role="toolbar" aria-label="Note formatting"><button type="button" class="chisimba-icon-button" data-command="undo" title="Undo" aria-label="Undo"><?php echo $icons->render('undo-2',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="redo" title="Redo" aria-label="Redo"><?php echo $icons->render('redo-2',array('decorative'=>true));?></button><span class="note-toolbar-divider" aria-hidden="true"></span><button type="button" class="chisimba-icon-button" data-command="bold" title="Bold" aria-label="Bold"><?php echo $icons->render('bold',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="italic" title="Italic" aria-label="Italic"><?php echo $icons->render('italic',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="formatBlock" data-value="h2" title="Heading" aria-label="Heading"><?php echo $icons->render('heading-2',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="insertUnorderedList" title="Bulleted list" aria-label="Bulleted list"><?php echo $icons->render('list',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="insertOrderedList" title="Numbered list" aria-label="Numbered list"><?php echo $icons->render('list-ordered',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="createLink" title="Add link" aria-label="Add link"><?php echo $icons->render('link',array('decorative'=>true));?></button><button type="button" class="chisimba-icon-button" data-command="removeFormat" title="Clear formatting" aria-label="Clear formatting"><?php echo $icons->render('remove-formatting',array('decorative'=>true));?></button></div><div class="chisimba-longform-editor chisimba-prose note-writing-surface" contenteditable="true" role="textbox" aria-multiline="true" aria-label="Note text" data-note-editor><?php echo $noteRecord['body'];?></div><input type="hidden" name="body" value="" data-note-body/><footer class="note-save-footer"><span class="chisimba-muted" data-word-count>0 words</span><div class="notes-actions"><span data-note-feedback role="status" aria-live="polite">All changes saved</span><button type="submit" class="button"><?php echo $icons->render('save',array('decorative'=>true));?> Save note</button></div></footer></form><?php else:?><div class="note-body chisimba-prose"><?php echo $noteRecord['body'];?></div><?php endif;?>
  </section>
  <aside class="note-sidebar chisimba-flow">
   <section class="dashboard-panel note-connections"><div class="note-section-heading"><div><p class="chisimba-eyebrow">CONNECTIONS</p><h2>Linked work</h2></div><span class="chisimba-pill"><?php echo count($noteLinks);?></span></div><p class="chisimba-muted">References to this note across Chisimba. The note itself remains here.</p><ul class="note-links" data-note-links><?php foreach($noteLinks as $link):?><li data-link-id="<?php echo $e($link['id']);?>"><div><span class="chisimba-pill"><?php echo $e(str_replace('_',' ',$link['targettype']));?></span><?php if($link['targeturl']!==''):?><a href="<?php echo $e($link['targeturl']);?>"><?php echo $e($link['targetlabel']);?></a><?php else:?><strong><?php echo $e($link['targetlabel']);?></strong><?php endif;?></div><?php if($noteCanEdit):?><form method="post" action="<?php echo $e($url(array('action'=>'detach')));?>" data-note-detach><?php echo $hidden;?><input type="hidden" name="linkid" value="<?php echo $e($link['id']);?>"/><button type="submit" class="chisimba-icon-button" title="Detach" aria-label="Detach <?php echo $e($link['targetlabel']);?>"><?php echo $icons->render('unlink',array('decorative'=>true));?></button></form><?php endif;?></li><?php endforeach;?></ul><?php if(!$noteLinks):?><p class="note-empty-hint">This note is not connected to other work yet.</p><?php endif;?>
   <?php if($noteCanEdit):?><details><summary class="button chisimba-button-secondary"><?php echo $icons->render('link-2',array('decorative'=>true));?> Attach work</summary><form method="post" action="<?php echo $e($url(array('action'=>'attach')));?>" data-note-attach class="chisimba-flow"><?php echo $hidden;?><label>Type<select name="targettype"><option value="kanban_board">Kanban board</option><option value="kanban_task">Kanban task</option><option value="kanban_subtask">Kanban subtask</option><option value="context">Course</option><option value="content_page">Content page</option><option value="page">Other Chisimba page</option></select></label><label>Stable item ID<input name="targetid" maxlength="255" required/></label><label>Label<input name="targetlabel" maxlength="255" required/></label><label>Link URL (optional)<input type="url" name="targeturl" maxlength="1000"/></label><button type="submit" class="button">Attach</button><span data-attach-feedback role="status" aria-live="polite"></span></form></details><?php endif;?></section>
   <?php if($noteCanManage):?><section class="dashboard-panel note-management"><p class="chisimba-eyebrow">MANAGE</p><details><summary class="button chisimba-button-secondary"><?php echo $icons->render('users',array('decorative'=>true));?> Sharing and permissions</summary><form method="post" action="<?php echo $e($url(array('action'=>'share')));?>" class="chisimba-flow"><?php echo $hidden;?><label>One username and permission per line<textarea name="grants" rows="5" placeholder="username:view"><?php echo $e(implode("\n",$grantLines));?></textarea></label><p>Use <code>view</code>, <code>edit</code> or <code>manage</code>.</p><button type="submit" class="button">Save sharing</button></form></details><form method="post" action="<?php echo $e($url(array('action'=>'archive')));?>"><?php echo $hidden;?><button type="submit" class="button chisimba-button-secondary"><?php echo $icons->render(empty($noteRecord['isarchived'])?'archive':'archive-restore',array('decorative'=>true));?> <?php echo empty($noteRecord['isarchived'])?'Archive note':'Restore note';?></button></form></section><?php endif;?>
  </aside>
 </div>
</main>
