<?php
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$l=$sitepagesLabels;$url=fn($p=[])=>html_entity_decode($this->uri($p,'sitepages'),ENT_QUOTES,'UTF-8');$edit=is_array($sitepagesEdit)?$sitepagesEdit:[];$icon=fn($name)=>$this->getObject('iconservice','ui')->render($name,['decorative'=>true]);
?>
<main class="chisimba-workspace chisimba-stack">
<header class="chisimba-page-heading"><h1><?= $e(!empty($sitepagesEditing) ? ($edit ? $l['editing'].' '.$edit['title'] : $l['new']) : $l['title']) ?></h1><nav class="chisimba-cluster">
<?php if(!empty($sitepagesEditing)): ?><a class="button chisimba-button-secondary" href="<?= $e($url(['action'=>'manage'])) ?>"><?= $icon('arrow-left') ?> <?= $e($l['allpages']) ?></a><?php endif; ?>
<?= $this->getObject('contextualhelp','help')->show('sitepages','pages',true) ?></nav></header>
<?php if($sitepagesFlash!==''):?><p class="chisimba-form-notice" role="status" <?= !empty($sitepagesError) ? 'data-composition-error' : '' ?>><?= $e($sitepagesFlash) ?></p><?php endif;?>
<?php if(!empty($sitepagesDenied)):?><p role="alert"><?= $e(!empty($sitepagesMissingEdit) ? $this->getObject('language','language')->languageText('mod_sitepages_notfound','sitepages') : $l['forbidden']) ?></p>
<?php elseif(empty($sitepagesEditing)): ?>
<div class="chisimba-cluster"><p><?= $e($l['intro']) ?></p><a class="button" href="<?= $e($url(['action'=>'manage','new'=>'1'])) ?>"><?= $icon('plus') ?> <?= $e($l['new']) ?></a></div>
<?php if(!$sitepagesRows): ?><p><?= $e($l['empty']) ?></p><?php endif; ?>
<div class="chisimba-stack">
<?php foreach($sitepagesRows as $row):?><article class="chisimba-form-card chisimba-form-card--wide chisimba-form-card--compact chisimba-wrap-anywhere"><div class="chisimba-page-heading"><h2><a href="<?= $e($url(['action'=>'manage','id'=>$row['id']])) ?>"><?= $e($row['title']) ?></a></h2><div class="chisimba-cluster"><span><?= $e($l[$row['status']==='published'?'published':'draft']) ?></span><a class="chisimba-icon-button" href="<?= $e($url(['action'=>'view','slug'=>$row['slug']])) ?>" aria-label="<?= $e($l['preview'].' '.$row['title']) ?>"><?= $icon('eye') ?></a><a class="chisimba-icon-button" href="<?= $e($url(['action'=>'manage','id'=>$row['id']])) ?>" aria-label="<?= $e($l['edit'].' '.$row['title']) ?>"><?= $icon('pencil') ?></a><form method="post" action="<?= $e($url(['action'=>'archive'])) ?>" onsubmit="return confirm(<?= $e(json_encode($l['confirmarchive'])) ?>)"><input type="hidden" name="csrf_token" value="<?= $e($sitepagesCsrf) ?>"><input type="hidden" name="id" value="<?= $e($row['id']) ?>"><button class="chisimba-icon-button chisimba-button-danger" type="submit" aria-label="<?= $e($l['archive'].' '.$row['title']) ?>"><?= $icon('archive-x') ?></button></form></div></div></article><?php endforeach;?></div>
<?php else: ?>
<form method="post" class="chisimba-form chisimba-composition-form chisimba-stack" data-composition-ajax data-composition-save data-composition-saving="<?= $e(html_entity_decode($this->getObject('language','language')->languageText('mod_sitepages_saving','sitepages'),ENT_QUOTES,'UTF-8')) ?>" data-composition-saved="<?= $e($this->getObject('language','language')->languageText('mod_sitepages_saved','sitepages')) ?>" data-composition-pending="<?= $e(html_entity_decode($this->getObject('language','language')->languageText('mod_sitepages_updating','sitepages'),ENT_QUOTES,'UTF-8')) ?>" data-composition-updated="<?= $e($this->getObject('language','language')->languageText('mod_sitepages_unsaved','sitepages')) ?>" data-composition-failure="<?= $e($this->getObject('language','language')->languageText('mod_sitepages_failed','sitepages')) ?>" action="<?= $e($url(['action'=>'save'])) ?>">
<?php if(!empty($sitepagesSaved)): ?><input type="hidden" data-composition-save-confirmed value="1"><?php endif; ?>
<input type="hidden" name="id" value="<?= $e($edit['id']??'') ?>"><input type="hidden" name="csrf_token" value="<?= $e($sitepagesCsrf) ?>"><input type="hidden" name="version" value="<?= $e($edit['version']??($edit?dbsitepages::version($edit):'')) ?>">
<div class="chisimba-cluster"><button class="button chisimba-button-primary" type="submit"><?= $icon('save') ?> <?= $e($l['save']) ?></button><?php if(!empty($edit['slug'])): ?><a class="button chisimba-button-secondary" href="<?= $e($url(['action'=>'view','slug'=>$edit['slug']])) ?>"><?= $icon('eye') ?> <?= $e($l['viewpage']) ?></a><?php endif; ?></div>
<section class="chisimba-form-card chisimba-form-card--wide chisimba-form-card--compact">
<div class="chisimba-form-field"><label for="page-title"><?= $e($l['pagetitle']) ?></label><input id="page-title" name="title" required maxlength="250" value="<?= $e($edit['title']??'') ?>"></div>
<details class="chisimba-disclosure" <?= (empty($edit['id']) || !empty($sitepagesError)) ? 'open' : '' ?>><summary><?= $e($l['settings']) ?> · <?= $e($l[($edit['status']??'draft')==='published'?'published':'draft']) ?></summary><div class="chisimba-form-grid"><div class="chisimba-form-field"><label for="page-slug"><?= $e($l['slug']) ?></label><input id="page-slug" name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value="<?= $e($edit['slug']??'') ?>"><p><?= $e($l['slughelp']) ?></p></div>
<div class="chisimba-form-field"><label for="page-status"><?= $e($l['status']) ?></label><select id="page-status" name="status"><option value="draft" <?= ($edit['status']??'')!=='published'?'selected':'' ?>><?= $e($l['draft']) ?></option><option value="published" <?= ($edit['status']??'')==='published'?'selected':'' ?>><?= $e($l['published']) ?></option></select></div>
</div></details></section>
<section aria-label="<?= $e($l['content']) ?>"><h2><?= $e($l['content']) ?></h2><p><?= $e($l['editorhint']) ?></p>
<p role="status" data-composition-status></p><div data-composition-history></div>
<?= $this->getObject('compositioneditor','contentblocks')->show($sitepagesBlocks??[],true,$this->getVar('sitepagesActive')??'',false,['openFirst'=>false,'saveLabel'=>$l['save']]) ?>
</section><input type="hidden" name="composition_complete" value="1"><div class="chisimba-form-actions"><button class="button chisimba-button-primary" type="submit"><?= $icon('save') ?><span><?= $e($l['save']) ?></span></button><a class="button chisimba-button-secondary" href="<?= $e($url(['action'=>'manage'])) ?>"><?= $icon('arrow-left') ?> <?= $e($l['allpages']) ?></a></div></form>
<?php endif;?></main>
