<?php
$allProducts=$this->getVar('paymentProducts',array());
$productPage=$this->getVar('paymentProductPage',array());
$products=$productPage['products']??array();
$filters=$productPage['filters']??array();
$csrf=htmlspecialchars($this->getVar('paymentCsrf',''),ENT_QUOTES,'UTF-8');
$courseCode=(string)$this->getVar('paymentCourseCode','');
$courseProduct=$this->getVar('paymentCourseProduct',null);
$escape=static fn($value)=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');
$pageUrl=function($page)use($filters){return $this->uri(array_filter(array('action'=>'products','q'=>$filters['query']??'','purpose'=>$filters['purpose']??'','purpose_id'=>$filters['purpose_id']??'','status'=>$filters['status']??'','page'=>$page),static fn($v)=>$v!==''));};
?>
<section class="payment-workbench">
  <header><p class="eyebrow">PAYMENT CONFIGURATION</p><h1>Products and prices</h1><p>A price version is permanent once created. Publish a new version when a price changes.</p><div class="chisimba-form-actions"><a class="button chisimba-button-secondary" href="<?=$this->uri(array('action'=>'operations'))?>">View payment activity</a></div></header>
  <?php if($courseCode!==''):?><div class="payment-context-notice"><strong>Pricing this course: <?=$escape($courseCode)?></strong><a href="<?=$this->uri(array('action'=>'controlpanel'),'context')?>">Back to course administration</a></div><?php endif;?>
  <?php if($this->getVar('paymentMessage','')):?><div class="success"><?=$escape($this->getVar('paymentMessage'))?></div><?php endif;?>
  <?php if($this->getVar('paymentError','')):?><div class="error"><?=$escape($this->getVar('paymentError'))?></div><?php endif;?>
  <div class="payment-admin-grid">
    <?php if(is_array($courseProduct)):?><article class="payment-card payment-course-product"><p class="eyebrow">COURSE PRODUCT</p><h2><?=$escape($courseProduct['name'])?></h2><dl><dt>Product code</dt><dd><?=$escape($courseProduct['code'])?></dd><dt>Billing</dt><dd><?=$escape(ucfirst(str_replace('_',' ',$courseProduct['billing_period'])))?></dd></dl><p>This is the canonical product for this course. Publish future price changes as new price versions.</p></article><?php else:?><article class="payment-card"><h2>New product</h2><form method="post" action="<?=$this->uri(array('action'=>'createproduct'))?>"><input type="hidden" name="csrf_token" value="<?=$csrf?>"><label>Product code<input name="code" required></label><label>Name<input name="name" required></label><label>Purpose<select name="purpose_type"><option value="membership">Membership</option><option value="private_course"<?=$courseCode!==''?' selected':''?>>Private course</option></select></label><label>Tier or course code<input name="purpose_id" value="<?=$escape($courseCode)?>" required></label><label>Billing period<select name="billing_period"><option value="monthly">Monthly</option><option value="annual">Annual</option><option value="one_off"<?=$courseCode!==''?' selected':''?>>One-off</option></select></label><label>Access duration in months<input type="number" name="duration_months" min="1" max="120"></label><button class="button" type="submit">Create product</button></form></article><?php endif;?>
    <article class="payment-card"><h2>Add a price version</h2><form method="post" action="<?=$this->uri(array('action'=>'addprice'))?>"><input type="hidden" name="csrf_token" value="<?=$csrf?>"><label>Product<select name="product_id"><?php foreach($allProducts as $p): if($courseCode!==''&&(string)$p['purpose_id']!==$courseCode)continue;?><option value="<?=$escape($p['id'])?>"><?=$escape($p['name'])?></option><?php endforeach;?></select></label><label>Version code<input name="version_code" placeholder="2026-08" required></label><label>Amount in cents<input type="number" name="amount_minor" min="1" required></label><label>Currency<input name="currency" value="ZAR" maxlength="3" required></label><label>Effective from<input name="effective_from" value="<?=date('Y-m-d H:i:s')?>" required></label><label>Effective until (optional)<input name="effective_until"></label><button class="button" type="submit">Publish price</button></form></article>
  </div>
  <article class="payment-card payment-products-list"><header><div><h2>Saved products</h2><p><?=$escape($productPage['total']??0)?> product<?=($productPage['total']??0)===1?'':'s'?> found</p></div></header>
    <form class="payment-product-filters" method="get" action="<?=$this->uri(array())?>"><input type="hidden" name="module" value="payment-service"><input type="hidden" name="action" value="products"><label>Search<input type="search" name="q" value="<?=$escape($filters['query']??'')?>" placeholder="Name, code or course"></label><label>Purpose<select name="purpose"><option value="">All purposes</option><option value="membership"<?=($filters['purpose']??'')==='membership'?' selected':''?>>Membership</option><option value="private_course"<?=($filters['purpose']??'')==='private_course'?' selected':''?>>Private course</option></select></label><label>Status<select name="status"><option value="">All statuses</option><option value="active"<?=($filters['status']??'')==='active'?' selected':''?>>Active</option><option value="inactive"<?=($filters['status']??'')==='inactive'?' selected':''?>>Inactive</option></select></label><?php if(($filters['purpose_id']??'')!==''):?><input type="hidden" name="purpose_id" value="<?=$escape($filters['purpose_id'])?>"><?php endif;?><div class="chisimba-form-actions"><button class="button" type="submit">Apply filters</button><a class="button chisimba-button-secondary" href="<?=$this->uri(array('action'=>'products'))?>">Clear</a></div></form>
    <?php if(!$products):?><div class="payment-empty-state"><strong>No products match these filters.</strong><p>Clear the filters or create a new product above.</p></div><?php else:?><div class="payment-table-scroll"><table><thead><tr><th>Product</th><th>Purpose</th><th>Period</th><th>Current price</th><th>Versions</th></tr></thead><tbody><?php foreach($products as $p):?><tr><td><strong><?=$escape($p['name'])?></strong><br><small><?=$escape($p['code'])?></small></td><td><?=$escape(str_replace('_',' ',$p['purpose_type']).' · '.$p['purpose_id'])?></td><td><?=$escape(str_replace('_',' ',$p['billing_period']))?></td><td><?php $cp=$p['current_price']??null; echo $cp?$escape($cp['currency']).' '.number_format($cp['amount_minor']/100,2):'Not priced';?></td><td><?=count($p['prices']??array())?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
    <?php if(($productPage['pages']??1)>1):?><nav class="payment-pagination" aria-label="Saved products pages"><?php if($productPage['page']>1):?><a class="chisimba-navigation-action" href="<?=$pageUrl($productPage['page']-1)?>">Previous</a><?php endif;?><span>Page <?=$escape($productPage['page'])?> of <?=$escape($productPage['pages'])?></span><?php if($productPage['page']<$productPage['pages']):?><a class="chisimba-navigation-action" href="<?=$pageUrl($productPage['page']+1)?>">Next</a><?php endif;?></nav><?php endif;?>
  </article>
</section>
