<?php
$this->appendArrayVar('headerParams','<style type="text/css">'
    .'.payment-workbench{box-sizing:border-box;width:100%}.payment-workbench>header{margin:0 0 1.25rem}.payment-workbench h1{margin:.15rem 0 .35rem}.payment-workbench .eyebrow{margin:0;color:var(--chisimba-primary);font-size:.8rem;font-weight:800;letter-spacing:.04em}'
    .'.payment-product-grid,.payment-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.payment-product-card,.payment-card,.payment-summary,.payment-status{box-sizing:border-box;margin:0 0 1rem;padding:1.25rem;border:1px solid var(--chisimba-border);border-radius:var(--chisimba-radius-md,.5rem);background:var(--chisimba-surface)}'
    .'.payment-product-card h2,.payment-card h2{margin-top:0}.payment-price{font-size:1.55rem;font-weight:800;color:var(--chisimba-ink)}.payment-summary{display:flex;justify-content:space-between;gap:1rem}.payment-workbench label{display:block;margin:0 0 .9rem;font-weight:700}.payment-workbench input,.payment-workbench select{box-sizing:border-box;display:block;width:100%;margin-top:.35rem}.payment-workbench form .button{margin-top:.35rem}'
    .'.payment-workbench table{width:100%;border-collapse:collapse}.payment-workbench th,.payment-workbench td{padding:.7rem;text-align:left;border-bottom:1px solid var(--chisimba-border);vertical-align:top}.payment-status-succeeded{border-left:.3rem solid var(--chisimba-success,#16803c)}.payment-status-failed,.payment-status-refunded,.payment-status-reversed,.payment-status-disputed{border-left:.3rem solid var(--chisimba-danger,#b42318)}'
    .'@media(max-width:48rem){.payment-product-grid,.payment-admin-grid{grid-template-columns:1fr}.payment-workbench table{display:block;overflow-x:auto}}'
    .'</style>');
$layout=$this->newObject('csslayout','htmlelements');$layout->setNumColumns(2);$layout->setLeftColumnContent('<aside class="chisimba-structural-sidebar payment-sidebar" aria-label="Account navigation">'.$this->getObject('postloginmenu','toolbar')->show().'</aside>');$layout->setMiddleColumnContent('<main class="chisimba-structural-main payment-main">'.$this->getContent().'</main>');echo $layout->show();
?>
