<?php
$this->appendArrayVar('headerParams','<style type="text/css">'
    .'.payment-workbench{box-sizing:border-box;width:100%}.payment-workbench>header{margin:0 0 1.25rem}.payment-workbench h1{margin:.15rem 0 .35rem}.payment-workbench .eyebrow{margin:0;color:var(--chisimba-primary);font-size:.8rem;font-weight:800;letter-spacing:.04em}'
    .'.payment-product-grid,.payment-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.payment-product-card,.payment-card,.payment-summary,.payment-status{box-sizing:border-box;margin:0 0 1rem;padding:1.25rem;border:1px solid var(--chisimba-border);border-radius:var(--chisimba-radius-md,.5rem);background:var(--chisimba-surface)}'
    .'.payment-product-card h2,.payment-card h2{margin-top:0}.payment-price{font-size:1.55rem;font-weight:800;color:var(--chisimba-ink)}.payment-summary{display:flex;justify-content:space-between;gap:1rem}.payment-workbench label{display:block;margin:0 0 .9rem;font-weight:700}.payment-workbench input,.payment-workbench select{box-sizing:border-box;display:block;width:100%;margin-top:.35rem}.payment-workbench form .button{margin-top:.35rem}'
    .'.payment-workbench table{width:100%;border-collapse:collapse}.payment-workbench th,.payment-workbench td{padding:.7rem;text-align:left;border-bottom:1px solid var(--chisimba-border);vertical-align:top}.payment-status-succeeded{border-left:.3rem solid var(--chisimba-success,#16803c)}.payment-status-failed,.payment-status-refunded,.payment-status-reversed,.payment-status-disputed{border-left:.3rem solid var(--chisimba-danger,#b42318)}'
    .'.payment-course-product dl{display:grid;grid-template-columns:max-content 1fr;gap:.45rem 1rem}.payment-course-product dt{font-weight:700}.payment-course-product dd{margin:0}'
    .'.payment-context-notice{display:flex;justify-content:space-between;gap:1rem;margin:0 0 1rem;padding:.85rem 1rem;border-left:.3rem solid var(--chisimba-primary);background:var(--chisimba-surface-muted,#f5f7fa)}.payment-product-filters{display:grid;grid-template-columns:minmax(14rem,2fr) minmax(10rem,1fr) minmax(10rem,1fr);align-items:end;gap:1rem;margin:1rem 0}.payment-product-filters label{margin:0}.payment-product-filters .chisimba-form-actions{align-self:end}.payment-products-list>header{display:flex;justify-content:space-between;gap:1rem}.payment-products-list>header p{margin:.25rem 0 0}.payment-table-scroll{overflow-x:auto}.payment-pagination{display:flex;justify-content:center;align-items:center;gap:1rem;margin-top:1rem}.payment-pagination .chisimba-navigation-action{padding:.55rem .8rem}.payment-empty-state{padding:1.25rem;text-align:center;background:var(--chisimba-surface-muted,#f5f7fa);border-radius:var(--chisimba-radius-md,.5rem)}'
    .'.payment-review-grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(18rem,.85fr);gap:1.25rem;align-items:start}.payment-review-course{margin:0}.payment-order-summary{position:sticky;top:1rem}.payment-order-summary dl{display:grid;grid-template-columns:max-content 1fr;gap:.75rem 1rem;margin:1.1rem 0}.payment-order-summary dt{font-weight:700;color:var(--chisimba-muted)}.payment-order-summary dd{margin:0;text-align:right}.payment-order-summary .payment-price{font-size:1.45rem}.payment-continue{box-sizing:border-box;width:100%;padding:.8rem 1rem}.payment-trust{display:flex;flex-direction:column;gap:.2rem;margin:1rem 0 0;padding-top:1rem;border-top:1px solid var(--chisimba-border);font-size:.9rem}.payment-trust span{color:var(--chisimba-muted)}'
    .'@media(max-width:48rem){.payment-product-grid,.payment-admin-grid,.payment-product-filters,.payment-review-grid{grid-template-columns:1fr}.payment-order-summary{position:static}.payment-workbench table{display:block;overflow-x:auto}.payment-context-notice{display:block}.payment-context-notice a{display:block;margin-top:.5rem}}'
    .'</style>');
$layout=$this->newObject('csslayout','htmlelements');$layout->setNumColumns(2);$layout->setLeftColumnContent('<aside class="chisimba-structural-sidebar payment-sidebar" aria-label="Account navigation">'.$this->getObject('postloginmenu','toolbar')->show().'</aside>');$layout->setMiddleColumnContent('<main class="chisimba-structural-main payment-main">'.$this->getContent().'</main>');echo $layout->show();
?>
